### PR TITLE
Decimals are now always correctly displayed when leaving the field #1748

### LINKED ISSUE #1748: [Panel] Number field removes decimal values when they are 0.
**Describe the bug**
When a number field is set to decimal values using the step option:

```
fields:
  price:
    label: Price
    type: number
    step: .01
```
and you select a number where the decimals are zero, e.g. 15,00, the zeros are removed when saving or reloading, also the number is stored without the decimals.

**To Reproduce**
1. Add above field in any blueprint
2. Visit page in panel and add number,  e.g 15,00
3. Save and reload
4. See zeros vanishing. They are also not stored.

**Expected behavior**
Zeros should be stored in the content file and not disappear.

**Kirby Version**
3.1.3

https://forum.getkirby.com/t/decimal-number-fields-dont-allow-00-anymore/14066

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

I found a way to display decimals correctly but at the same time still keeping the number input type. 

## Related issues

- Fixes #1748

### CODE REVIEW

File: panel/src/components/Forms/Input/NumberInput.vue [hunk 1]
```diff
@@ -69,20 +72,43 @@ export default {
...
+      }
+
+      return this.step.toString().split(".")[1].length || 0;
     },
-    onInput(value) {
+    format(value) {
       // don't convert empty values or the beginning of
       // a negative number to a Number
       if (value !== null && value !== "" && value !== "-" && value !== "-0") {
         value = Number(value);
```
Comment (distantnative) [inline panel/src/components/Forms/Input/NumberInput.vue]: I would write this with inmediate return statements.

File: panel/src/components/Forms/Input/NumberInput.vue [hunk 2]
```diff
@@ -69,20 +72,43 @@ export default {
...
       }
 
-      this.$emit("input", value);
+      const decimals = this.decimals();
+
+      if (decimals) {
+        value = parseFloat(value).toFixed(decimals);
```
Comment (distantnative) [inline panel/src/components/Forms/Input/NumberInput.vue]: same here in if and else

Comment (distantnative) [reply panel/src/components/Forms/Input/NumberInput.vue]: And in fact we can save the else statement and just return the normal one last.

Comment (bastianallgeier) [reply panel/src/components/Forms/Input/NumberInput.vue]: I didn't realize that the format method can be a lot simpler when we only use it on change.

File: panel/src/components/Forms/Input/NumberInput.vue [hunk 3]
```diff
@@ -80,21 +80,13 @@ export default {
       return this.step.toString().split(".")[1].length || 0;
     },
     format(value) {
-      // don't convert empty values or the beginning of
```
Comment (distantnative) [inline panel/src/components/Forms/Input/NumberInput.vue]: what happens to those string now that start with a minus sign or a zero? od't we have to treat them in a different way? or is that solved too with the new implementaition?

Comment (bastianallgeier) [reply panel/src/components/Forms/Input/NumberInput.vue]: They were only treated in the method so far, because the method was executed on input and that would stop them from being entered entirely without this exception. Now the transformation takes place on change and it's no longer a problem to sanitize them with parseInt or parseFloat.

**Review by distantnative — APPROVED** [review]

**Comment by distantnative** [comment]
LGTM
