### PR TITLE
Fixed files field options dropdown when upload disabled

### LINKED ISSUE #3768: [3.6.0-beta.2] files field with `uploads: false` doesn't work
**Describe the bug**  
Setting `uploads: false` on a files field results in an error.

**To Reproduce**  
1. Add a files field like this:
```yml
file:
  type: files
  multiple: false
  uploads: false
```
2. Click on "Select"
4. See error: `t.apply is not a function`

**Kirby Version**  
3.6.0 beta 2

**Console output**  
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'open')`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome
 - Version: 94.0.4606.61

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Fixed by using inline function instead of string since native button `click` prop requires inline function when there is only one option.

Please feel free to improve this PR if you have a better or more general solution.

### Fixes regressions from 3.6.0-beta.2

- Fixed files field option dropdown when upload disabled #3768 

## Breaking changes

None

## Related issues/ideas

- Fixes #3768 

## Ready?

- [ ] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Forms/Field/FilesField.vue [hunk 1]
```diff
@@ -71,7 +74,7 @@ export default {
       }
 
       return {
-        options: [{ icon: "check", text: this.$t("select"), click: "open" }]
+        options: [{ icon: "check", text: this.$t("select"), click: () => this.open() }]
```
Comment (afbora) [inline panel/src/components/Forms/Field/FilesField.vue:77]: Used inline function due to native button component click prop:

https://github.com/getkirby/kirby/blob/develop/panel/src/components/Navigation/ButtonNative.vue#L34-L37

**Review by bastianallgeier — APPROVED** [review]
