### PR TITLE
Panel navigation via Fiber

### LINKED ISSUE #3337: [3.6.0] `k-dropdown-content` background color broken
**Describe the bug**  

`k-dropdown-content` background color broken and might be related new `.k-dropdown-content[data-align=right]` class.

**To Reproduce**  
1. Go to panel
2. Click any three dots to open dropdown content
3. See error

**Screenshots**  

screen-capture-1067-Test - Mægazine-localhost

**Kirby Version**  
develop branch of 3.6.0

### PR DESCRIPTION
**Pull request by distantnative**
## Status: ready for review 👀

1. Add `'panel' => ['dev' => true]` to your config
2. run `npm run dev` as usual 
3. but then access `sandbox.test/panel` and not `localhost:3000`

## Benchmark

**Before PR**
```
dist/css/index.css   93.94kb / brotli: 13.85kb
dist/js/index.js     360.09kb / brotli: 65.87kb
dist/js/vendor.js    407.78kb / brotli: 110.02kb
```

**After PR**
```
dist/css/style.css   94.01kb / brotli: 13.89kb
dist/js/index.js     350.58kb / brotli: 64.19kb
dist/js/vendor.js    379.32kb / brotli: 103.63kb
```

###  Features
- Panel navigation now runs on Fiber - a new framework that allows us to handle routing, state data and much more from the backend. More exciting features and improvements built with Fiber to come.
- The Panel logic is now structured with a new feature called Panel areas. An area defines basic information e.g. for the menu entry as well as Panel routes that return dedicated Panel views or that can host other logic (e.g. our `logout` route which doesn't return a view but ends the user session and redirects to the `login` route). Our default areas are defined in `kirby/config/areas`. This feature is directly connected with the introduction of Fiber.
- New PHP plugin extension `areas` that allows defining custom Panel areas
- A new `router()` helper that takes a set of routes and request data and directly executes the matching routing action
- New `Panel` class alias for `Kirby\Panel\Panel`

### Enhancements
- The license code is now only displayed to admins, even if other users have access to the settings view in the Panel

### Refactoring and development features
- Local Panel development can now be done directly on the site domain when the [Kirby Sandbox](https://github.com/getkirby/sandbox) is used. Simply run Vite inside `kirby/panel` with `npm run dev` and open the Panel as normal.
- New Panel frontend method `this.$reload()` which refreshes all view data via Fiber. Supports partial refreshes via `this.$reload({ only: "$user" })`
- The Vue `k-app` component is now `k-inside` for creating the Panel wrapper setup when the user is logged in. Use `k-inside` - or new `k-outside` - to wrap views accordingly. 
- New `$store.dispatch("content/clear")` Vuex action
- New `k-login-alert` Vue component
- New JS helper to deep-merge objects (`helpers/object.js`)
- New `window.deprecated()` helper for the Panel frontend
- Our CI uses dynamically built production files for frontend testing now
- Upgraded `cypress` to 7.4.0
- Upgraded `vite` to 2.2.3

### Breaking changes

- Using custom Panel views (incl. routing, breadcrumbs...) in plugins has changed fundamentally. The old way of registering might still partly work but has shortcomings and will be completely removed in 3.7.0. Use Panel areas instead.
- `vue-router` has been completely removed, use Panel areas to define custom Panel routes
- Changes in the Vuex store and store modules
  - The `content` module doesn't handle content locking information anymore. This in now provided directly to the model views via Fiber.
  - The `language` module has been removed, use `this.$language` and `this.$languages` instead.
  - The `system` module has been removed, use `this.$system` instead.
  - The `translation` module has been removed, use `this.$$translation` instead.
  - The `user` module has been removed, use `this.$user` instead.
  - `$store.dispatch('breadcrumb')` has been deprecated and removed. Use Panel areas instead to define the view breadcrumb.
  - `$store.dispatch('title')` has been deprecated and removed. Use Panel areas instead to define the view title.
- Direct URLs for tabs in the Panel have changed, e.g. now `/panel/site/?tab=yourTabName`
- Direct URLs for the users view in the Panel filtered by a specific role have changed, e.g. now `/panel/users/?role=yourRole`
- All API endpoints for content locking/unlocking don't display an exception anymore when content locking isn't supported.
- The former development `panel/index.html` file was removed
- `k-browser-view` and `k-custom-view` Vue components have been removed
- The internal Panel sandbox has been removed

### Deprecations
- `GET (:all)/lock` and `GET (:all)/unlock` API endpoints have been deprecated and throw a warning in debug mode. They will be removed in 3.7.0.
- The frontend extension `panel.plugin({ view: [...] })` has been deprecated and will be removed in 3.7.0 - there are already some functionalities (e.g. menu entry) that aren't fully supported anymore. Use Panel areas instead.
- The `heartbeat` Vuex module has been deprecated and will be removed in 3.7.0

##  Related issues
- #3216 Browser back button updates URL, but not view
- #3337 `k-dropdown-content` background color broken

_* After this PR is ready to merge, issues may need to be retested._

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

File: config/views/login.php [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+    return [
+        'component' => 'LoginView',
+        'props' => [
+            'methods' => array_keys($kirby->system()->loginMethods()),
+            'pending' => [
+                'email'     => null,
+                'challenge' => null
+            ]
+
+        ],
```
Comment (lukasbestle) [inline config/views/login.php]: I haven't tested it yet, but this should work:

```suggestion
    $status = $kirby->auth()->status();

    return [
        'component' => 'LoginView',
        'props' => [
            'methods' => array_keys($kirby->system()->loginMethods()),
            'pending' => [
                'email'     => $status->email(),
                'challenge' => $status->challenge()
            ]
        ],
```

**Comment by bastianallgeier** [comment]
I wondered why the vendor file is so much bigger until I remembered that Inertia uses Axios. We used inertia-light in our last try: https://www.npmjs.com/package/inertia-light

**Comment by distantnative** [comment]
@bastianallgeier Exactly. That's why it's on the to do list to create a new lightweight version. Inertia has had a lot of changes/updates since then so the old lightweight is sadly quite outdated

**Comment by bastianallgeier** [comment]
LOL, it's even the first point in the list. I'm terrible. 🤣

**Comment by bastianallgeier** [comment]
Too bad that Pedro's version is outdated.

**Comment by afbora** [comment]
@distantnative How about adding the bug issues to be solved to the PR description?

**Comment by distantnative** [comment]
@afbora which ones do you have in mind?

**Comment by afbora** [comment]
As Lukas said, if we remove the `vue-router`, the #3216 problem will be fixed.

**Comment by distantnative** [comment]
Oh I didn't see that. Yes, please feel free to add it to the post on top. We can keep that one updated collectively :)

**Comment by distantnative** [comment]
@bastianallgeier can't edit the table on mobile but before I forget: the Panel routes currently use the go helper with fixed path for panel. But it could be someone else if someone used the option to set the Panel location/path

**Comment by bastianallgeier** [comment]
@distantnative just added it to the table.

**Comment by bastianallgeier** [comment]
@distantnative there are currently three issues that drive me insane and maybe you've already got an idea.

- A lot of the model (file, page, user) tests in the backend have a weird issue that seems to be related to the $this->panel()->url() method, but I cannot really figure it out. 
- The back button situation is just weird. For some reason Inertia does not seem to reload props on going back and it's causing all kinds of issues. This is a behaviour that seems to be exclusive to our Panel and I wonder if it's related to Vite.
- I cannot really test it though because whenever I build the dist files, I run into a third weird issue with the CSRF token not being used in Api calls and I cannot even login to test. 

I'm just leaving this here. Maybe you have ideas. Or maybe @afbora can help.

**Comment by afbora** [comment]
> A lot of the model (file, page, user) tests in the backend have a weird issue that seems to be related to the $this->panel()->url() method, but I cannot really figure it out.

This is a really weird issue. Since the [`$blueprint`](https://github.com/getkirby/kirby/blob/feature/inertia/src/Cms/File.php#L45) variable is defined first during the [`setProperties()`](https://github.com/getkirby/kirby/blob/feature/inertia/src/Cms/File.php#L127) method, `filename` has not been set yet.

In order for you to understand the error better, not the solution; 
If you define the `$filename` variable in the [File class](https://github.com/getkirby/kirby/blob/feature/inertia/src/Cms/File.php) before `$blueprint`, the error will go away 😅 

The new line that caused the error:
https://github.com/getkirby/kirby/blob/feature/inertia/src/Cms/Blueprint.php#L704

**Comment by bastianallgeier** [comment]
@afbora ahhh, that already helps a lot. So it's basically a dependency issue. The filename must be defined before the blueprint, but this is not happening because of the alphabetic order of the properties. Ok. I think that's fixable at least.

**Comment by afbora** [comment]
> * The back button situation is just weird. For some reason Inertia does not seem to reload props on going back and it's causing all kinds of issues. This is a behaviour that seems to be exclusive to our Panel and I wonder if it's related to Vite.

I had looked at this before but could not find any clue. This part was about history mode on `vue-router`, but I couldn't see anything like that on `vite` 🤷‍♂️

**Comment by bastianallgeier** [comment]
It could still be our setup, which might have remaining parts that work with vue-router but not great with Inertia yet. I will do more tests.

**Comment by bastianallgeier** [comment]
The deprecation warning about promises is a false positive in my opinion. We often use it in try/catch blocks like here: https://github.com/getkirby/kirby/blob/97edc9fd95455dab8f2b842c929b2cd142f9c962/panel/src/components/Dialogs/UserRenameDialog.vue#L49 (the success method is calling the inertia visit method under the hood) and Inertia seems to be looking for try/catch blocks as indicator for promises. It's a bit weird but I think we can ignore it. Especially when we are going to have our own library.

**Comment by distantnative** [comment]
@bastianallgeier I think clearing local storage isn't fully solved yet. It works for manual logouts but not for when a session timed out.

**Comment by bastianallgeier** [comment]
@distantnative that's true. I thought it's not possible. But maybe we can listen to the inertia visit event and clear storage whenever the login or logout route is visited. We don't really have any other chance as long as we are not storing changes in the session or in a file.

**Comment by bastianallgeier** [comment]
@distantnative cleaning it in the login view is actually the easiest way.

**Comment by bastianallgeier** [comment]
@distantnative I just wanted to work on the plugin views, but it seems like we are now using the Vue version without template compiler. Do you know how we get it up and running again?

**Comment by bastianallgeier** [comment]
@distantnative ha, I found it. It's working again.

**Comment by distantnative** [comment]
@bastianallgeier so for me `dist` files are working - but the back button issue remains

**Comment by afbora** [comment]
Does the `/panel/account` page work for you? I only see a blank white page.

**Comment by afbora** [comment]
An issue that you can reproduce when edit any page:

````
code: 400
details: []
exception: "Kirby\\Exception\\InvalidArgumentException"
file: "/test/kirby/inertia/kirby/src/Cms/Api.php"
key: "error.invalidArgument"
line: 142
message: "Invalid model type: kirby/inertia/panel/pages"
route: "(.*)/lock"
status: "error"
__proto__: Object
````

---

Issue Track Down:

https://github.com/getkirby/kirby/blob/feature/inertia/panel/src/components/Forms/FormButtons.vue#L89-L90

Previously Usage
````js
this.$route.path // output: /pages/home
````

Now Usage

````js
this.$view.path // output: /subfolder/panel/pages/home
````

**Comment by distantnative** [comment]
@afbora how does your URL look like that you use locally when in the Panel and running `npm run dev`?

For me it's working. I'm using `http://sandbox.test/panel`. Probably line in question is https://github.com/getkirby/kirby/blob/feature/inertia/src/Panel/Panel.php#L514

**Comment by afbora** [comment]
- Account view fixed 🎉 
- Lock issue continue (even if `content.locking` disabled)

@distantnative I've tested via `npm run build` and my local url is `http://localhost/test/kirby/inertia/`.

**Comment by afbora** [comment]
@distantnative In terms of giving you an idea; 
When I update the line you specified as below, it gives the correct `path` and locking works.
The request path contains all subfolders but the `$kirby->path()` contains only the folders after installation.

```php
$kirby->request()->url(['path' => $kirby->path()])->path()->slice(1)->toString(); // outputs: pages/home
```

https://github.com/getkirby/kirby/blob/feature/inertia/src/Panel/Panel.php#L514

**Comment by distantnative** [comment]
@afbora does this work too?

```php
Str::after($kirby->path(), '/')
```

**Comment by afbora** [comment]
@distantnative Yes, works great. But error is changed:

```
code: 501
details: []
exception: "Kirby\\Exception\\Exception"
file: "/test/kirby/inertia/kirby/config/api/routes/lock.php"
key: "error.lock.notImplemented"
line: 48
message: "An error occurred"
route: "(.*)/lock"
status: "error"
__proto__: Object
```

**Comment by afbora** [comment]
I've notice `error.lock.notImplemented` error arise when `content.locking` disabled (even `debug` disabled)

**Comment by distantnative** [comment]
The error should exist, but it actually should be caught in FormButtons.vue

**Comment by afbora** [comment]
Is it normal to see this error in console even though debug is disabled?

**Comment by distantnative** [comment]
@afbora doesn't sound right. how is it behaving on the `develop` branch?

**Comment by afbora** [comment]
@distantnative locking works as expected with enabled or disabled on develop branch.

File: config/areas/settings.php [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+            [
+                'pattern' => 'settings',
+                'action'  => function () use ($kirby) {
+                    return [
+                        'component' => 'k-settings-view',
+                        'props'     => [
+                            'languages' => $kirby->languages()->values(function ($language) {
+                                return [
+                                    'default' => $language->isDefault(),
+                                    'icon' => [
```
Comment (distantnative) [inline config/areas/settings.php]: @bastianallgeier Should we have that `icon` definition actually in the backend? (same with `image`). I guess that should rather be added with the Vue component view (defining it once instead adding it to each language and increasing the Inertia call load size).

Comment (bastianallgeier) [reply config/areas/settings.php]: That's true!

File: panel/src/config/fiber.js [hunk 3]
```diff
@@ -0,0 +1,373 @@
...
+    });
+
+    // set the lang attribute according to the current translation
+    if (data.$translation) {
+      document.querySelector("html").setAttribute("lang", data.$translation.code);
+    }
+
+    // set the document title according to $view.title
+    if (data.$view.title) {
+      document.title = data.$view.title + " | Kirby Panel";
```
Comment (distantnative) [inline panel/src/config/fiber.js]: So far the site title has been used here instead of the hardcoded "Kirby Panel" - I think we should bring that back.

File: config/api/routes/lock.php [hunk 4]
```diff
@@ -9,7 +8,13 @@
     [
         'pattern' => '(:all)/lock',
         'method'  => 'GET',
+        /**
+         * @deprecated 3.6.0
+         * @todo Remove in 3.7.0
+         */
         'action'  => function (string $path) {
+            deprecated('The `GET (:all)/lock` API endpoint has been deprecated and will be removed in 3.7.0');
```
Comment (lukasbestle) [inline config/api/routes/lock.php:16]: Why the deprecation of the lock/unlock getters? These API routes might still make sense for custom applications and integrations.

File: config/areas/account.php [hunk 5]
```diff
@@ -0,0 +1,38 @@
+<?php
+
```
Comment (lukasbestle) [inline config/areas/account.php:2]: For better performance the `Panel` class should be explicitly imported:

```suggestion

use Kirby\Panel\Panel;

```

File: config/areas/login.php [hunk 6]
```diff
@@ -0,0 +1,41 @@
+<?php
+
```
Comment (lukasbestle) [inline config/areas/login.php:2]:
```suggestion

use Kirby\Panel\Panel;

```

File: config/areas/site.php [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+            return $kirby->site()->title()->or(t('view.site'))->toString();
+        },
+        'icon'   => 'home',
+        'label'  => t('view.site'),
+        'menu'   => true,
+        'routes' => [
+            [
+                'pattern' => 'pages/(:any)',
+                'action'  => function (string $path) use ($kirby) {
+                    if (!$page = $kirby->page(str_replace('+', '/', $path))) {
```
Comment (lukasbestle) [inline config/areas/site.php]:
```suggestion
                    $page = $kirby->page(str_replace('+', '/', $path));

                    if (!$page) {
```

File: config/areas/site.php [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+                    return $page->panel()->route();
+                }
+            ],
+            [
+                'pattern' => 'pages/(:any)/files/(:any)',
+                'action'  => function (string $id, string $filename) use ($kirby) {
+                    $id       = str_replace('+', '/', $id);
+                    $filename = urldecode($filename);
+
+                    if (!$page = $kirby->page($id)) {
```
Comment (lukasbestle) [inline config/areas/site.php]:
```suggestion
                    $page = $kirby->page($id);
                    if (!$page) {
```

File: config/areas/site.php [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+                        return t('error.page.undefined');
+                    }
+
+                    if (!$file = $page->file($filename)) {
```
Comment (lukasbestle) [inline config/areas/site.php]:
```suggestion
                    $file = $page->file($filename);
                    if (!$file) {
```

File: config/areas/site.php [hunk 10]
```diff
@@ -0,0 +1,60 @@
...
+                'action'  => function () use ($kirby) {
+                    return $kirby->site()->panel()->route();
+                }
+            ],
+            [
+                'pattern' => 'site/files/(:any)',
+                'action'  => function (string $filename) use ($kirby) {
+                    $filename = urldecode($filename);
+
+                    if (!$file = $kirby->site()->file($filename)) {
```
Comment (lukasbestle) [inline config/areas/site.php]:
```suggestion
                    $filename = urldecode($filename);
                    $file = $kirby->site()->file($filename);

                    if (!$file) {
```

File: config/areas/users.php [hunk 11]
```diff
@@ -0,0 +1,91 @@
...
+                                ];
+                            },
+                        ]
+                    ];
+                }
+            ],
+            [
+                'pattern' => 'users/(:any)',
+                'action'  => function (string $id) use ($kirby) {
+                    if (!$user = $kirby->user($id)) {
```
Comment (lukasbestle) [inline config/areas/users.php]:
```suggestion
                    $user = $kirby->user($id);

                    if (!$user) {
```

File: config/areas/users.php [hunk 12]
```diff
@@ -0,0 +1,91 @@
...
+
+                    return $user->panel()->route();
+                }
+            ],
+            [
+                'pattern' => 'users/(:any)/files/(:any)',
+                'action'  => function (string $id, string $filename) use ($kirby) {
+                    $filename = urldecode($filename);
+
+                    if (!$user = $kirby->user($id)) {
```
Comment (lukasbestle) [inline config/areas/users.php]:
```suggestion
                    $user = $kirby->user($id);
                    if (!$user) {
```

File: config/areas/users.php [hunk 13]
```diff
@@ -0,0 +1,91 @@
...
+                        return t('error.user.undefined');
+                    }
+
+                    if (!$file = $user->file($filename)) {
```
Comment (lukasbestle) [inline config/areas/users.php:77]:
```suggestion
                    $file = $user->file($filename);
                    if (!$file) {
```

File: config/helpers.php [hunk 14]
```diff
@@ -622,6 +623,21 @@ function r($condition, $value, $alternative = null)
     return $condition ? $value : $alternative;
 }
 
+/**
+ * Create a micro-router
+ * and execute the routing action
+ * immediately
```
Comment (lukasbestle) [inline config/helpers.php]:
```suggestion
 * Creates a micro-router and executes
 * the routing action immediately
```

File: panel/src/api/request.js [hunk 15]
```diff
@@ -1,3 +1,18 @@
+
+export async function toJson(response) {
+  const text = await response.text();
+  let data;
+
+  try {
+    data = JSON.parse(text);
+  } catch (e) {
+    window.panel.$vue.$store.dispatch("fatal", text);
+    throw new Error("The JSON response of the API could not be parsed");
```
Comment (lukasbestle) [inline panel/src/api/request.js]: This duplicates `Vue.$api.onParserError()`. Is there any reason why we cannot reuse this method? This would reduce the risk of later regressions when we forget to change the code in one of the two places.

**Review by lukasbestle — COMMENTED** [review]
A few suggestions and comments:

File: panel/src/api/request.js (hunk 15 above)
Comment (distantnative) [reply panel/src/api/request.js]: Oh true, I didn't realise that with my change (basically combining the same code from API and Fiber in this `toJSON` method), I rendered `Vue.$api.onParserError()` as dead code. It never gets called actually anymore. We could either remove it or call it from `toJSON` - a bit weird cause then it gets called for FIber request failures as well, but it wouldn't really matter.

File: config/api/routes/lock.php (hunk 4 above)
Comment (distantnative) [reply config/api/routes/lock.php:16]: Our current content locking isn't great - I think we need to move rather soon a version based on storing unsaved changes not he server etc. - That will likely change a lot, which is why I would really like to discourage the use of these endpoints already by removing them.

And let's face it, any discussion here is pretty sure a theoretical one - we've never documented this properly, I don't think the content locking API has been useable at all for developers so far.

File: config/areas/site.php (hunk 7 above)
Comment (distantnative) [reply config/areas/site.php]: If we rewrite these, we should actually make the if statement consistent with our code styles, e.g. explicitly check for `$page === null` in this case then.

File: config/api/routes/lock.php (hunk 4 above)
Comment (lukasbestle) [reply config/api/routes/lock.php:16]: Makes sense 👍

File: config/areas/site.php (hunk 7 above)
Comment (lukasbestle) [reply config/areas/site.php]: Being less strict makes sense here – any falsy value should lead to an error, not just `null`. But I‘m fine with either solution.

File: panel/src/api/request.js (hunk 15 above)
Comment (lukasbestle) [reply panel/src/api/request.js]: TBH I don‘t fully understand how it all plays together. So I‘m fine with whatever makes the most sense for you.

File: panel/src/config/fiber.js [hunk 16]
```diff
@@ -0,0 +1,373 @@
...
+    url = this.toUrl(url, { data: data || {}, hash: false });
+
+    try {
+      // fetch the response (only GET request supported)
+      const response = await fetch(url, {
+        method: "get",
+        headers: {
+          ...headers,
+          "Accept": "text/html, application/xhtml+xml",
+          "X-Requested-With": "XMLHttpRequest",
```
Comment (lukasbestle) [inline panel/src/config/fiber.js]: I guess these lines are from Inertia. Do we really need them for our backend logic?

File: panel/src/store/modules/system.js [hunk 17]
```diff
@@ -1,76 +1,19 @@
...
-        return context.state.info;
-
-      } catch (error) {
-        context.commit("SET_INFO", {
-          isBroken: true,
-          error: error.message
-        });
-      }
+    async load() {
+      window.panel.deprecated("The $store.system module has been deprecated and removed. Use this.$reload('$sysytem') instead.");
```
Comment (lukasbestle) [inline panel/src/store/modules/system.js]:
```suggestion
      window.panel.deprecated("The $store.system module has been deprecated and removed. Use this.$reload('$system') instead.");
```

File: panel/src/store/modules/user.js [hunk 18]
```diff
@@ -1,92 +1,39 @@
...
-      });
+    language() {
+      window.panel.deprecated("The $store.user module has been deprecated and removed. Use this.$user and this.$language instead.");
     },
-    async load(context) {
-      const user = await Vue.$api.auth.user();
-      context.commit("SET_CURRENT", user);
-      return user;
+    async load() {
+      window.panel.deprecated("The $store.user module has been deprecated and removed. Use this.$user instead.");
```
Comment (lukasbestle) [inline panel/src/store/modules/user.js]:
```suggestion
      window.panel.deprecated("The $store.user module has been deprecated and removed. Use this.$reload('$user') instead.");
```

File: panel/src/store/modules/user.js [hunk 19]
```diff
@@ -1,92 +1,39 @@
...
-      }
-
-      try {
-        await Vue.$api.auth.logout();
-
-      } finally {
-        Vue.prototype.$go("/login");
-      }
+    async logout() {
+      window.panel.deprecated("The $store.user module has been deprecated and removed. Use this.$user instead.");
```
Comment (lukasbestle) [inline panel/src/store/modules/user.js]:
```suggestion
      window.panel.deprecated("The $store.user module has been deprecated and removed. Use this.$go('logout') instead.");
```

File: src/Cms/AppPlugins.php [hunk 20]
```diff
@@ -129,6 +130,17 @@ protected function extendApi($api): array
         }
     }
 
+    /**
+     * Registers additional custom panel areas
```
Comment (lukasbestle) [inline src/Cms/AppPlugins.php]:
```suggestion
     * Registers additional custom Panel areas
```

File: src/Panel/Model.php [hunk 21]
```diff
@@ -195,22 +212,39 @@ protected function imageSource(?string $query = null)
...
         ) {
-            $image = null;
+            return $image;
         }
 
-        // fallback for files
-        if (
-            $image === null &&
-            is_a($this->model, 'Kirby\Cms\File') === true &&
-            $this->model->isViewable() === true
```
Comment (lukasbestle) [inline src/Panel/Model.php:208]: What happened to this viewable check? Has it been moved elsewhere or is it no longer needed?

File: src/Panel/Model.php [hunk 22]
```diff
@@ -245,7 +279,7 @@ public function options(array $unlock = []): array
      */
     abstract public function path(): string;
 
-    /**
+    /*
```
Comment (lukasbestle) [inline src/Panel/Model.php]:
```suggestion
    /**
```

File: src/Panel/Page.php [hunk 23]
```diff
@@ -111,4 +127,73 @@ public function pickerData(array $params = []): array
...
+     * @return array
+     */
+    public function route(): array
+    {
+        $page = $this->model;
+
+        return [
+            'breadcrumb' => function () use ($page) {
+                return $page->panel()->breadcrumb();
+            },
```
Comment (lukasbestle) [inline src/Panel/Page.php]: Why do we need a callback here? Can't it be `$this->breadcrumb()`?

File: src/Panel/Redirect.php [hunk 24]
```diff
@@ -0,0 +1,13 @@
+<?php
+
+namespace Kirby\Panel;
+
+use Exception;
+
+class Redirect extends Exception
```
Comment (lukasbestle) [inline src/Panel/Redirect.php:7]: I feel like this class should be part of `Kirby\Exception`. But I'm not 100% sure.

File: src/Panel/Panel.php [hunk 25]
```diff
@@ -45,7 +199,264 @@ public static function customCss(App $kirby)
...
+                }
+
+                return [];
+            },
+            '$permissions' => function () use ($kirby) {
+                if ($user = $kirby->user()) {
+                    return $user->role()->permissions()->toArray();
+                }
+            },
+            '$license' => $kirby->system()->license(),
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: Should this be passed with every response, even if the user is not admin?

File: panel/src/config/fiber.js (hunk 16 above)
Comment (bastianallgeier) [reply panel/src/config/fiber.js]: I was wondering about it as well. I think we can remove them. Let's keep it as simple as possible.

File: config/areas/users.php (hunk 13 above)
Comment (bastianallgeier) [reply config/areas/users.php:77]: I really love the oneliner. Why would you change it?

File: src/Panel/Page.php (hunk 23 above)
Comment (bastianallgeier) [reply src/Panel/Page.php]: Yep, can just be the simple method call

File: src/Panel/Redirect.php (hunk 24 above)
Comment (bastianallgeier) [reply src/Panel/Redirect.php:7]: I was thinking about it as well, but we have this weird custom exception handling format in our exceptions and I wasn't sure if it fits in there well enough.

File: src/Panel/Panel.php (hunk 25 above)
Comment (bastianallgeier) [reply src/Panel/Panel.php]: No, it shouldn't!! We should convert this to a boolean. The license key is only needed in the settings view and we can check for admin rights there before we send it.

File: src/Panel/Page.php (hunk 23 above)
Comment (distantnative) [reply src/Panel/Page.php]: Isn't the more we put into callbacks the better? Since then this won't processed in partial reloads that don't need this key

File: config/areas/users.php (hunk 13 above)
Comment (lukasbestle) [reply config/areas/users.php:77]: Setting variables in `if` blocks is [discouraged](https://phpmd.org/rules/cleancode.html#ifstatementassignment) because it can cause unexpected issues that are hard to spot. So far we mostly use it like `if ($var = $object->method())` (which is fine in the cases we use it in IMO) but with the additional `!` thrown into the mix this gets quite complex and I fear that it might break in future PHP releases. In any case this is quite hard to parse mentally.

File: src/Panel/Page.php (hunk 23 above)
Comment (lukasbestle) [reply src/Panel/Page.php]: Ah, if that's the case, then yes.

But we shouldn't do premature optimization. If we have a use-case that actually needs page data without the breadcrumb, then it's great, but otherwise we should IMO keep it as simple as possible.

File: src/Panel/Redirect.php (hunk 24 above)
Comment (lukasbestle) [reply src/Panel/Redirect.php:7]: We also have `ErrorPageException` there. But you are right, maybe it's too Panel specific.
We should rename the class to `RedirectException` though (common naming scheme for all kinds of exceptions).

File: src/Panel/Page.php (hunk 23 above)
Comment (distantnative) [reply src/Panel/Page.php]: The use case is any partial request that doesn't asks for the breadcrumb. With closures, we can first slim town the whole data array to only contain the keys required for the partial request before we actually resolve the closures to actual values. If we don't use closures, we always already resolve all the data before we slim down the array to just the partial data. Which would reduce the meaningfulness of partial requests quite a bit. That's why we should probably use as many closures as possible in the Panel data arrays.

File: src/Panel/Panel.php [hunk 26]
```diff
@@ -45,7 +199,264 @@ public static function customCss(App $kirby)
...
+                    'locales' => $locales,
+                    'slugs'   => Str::$language,
+                    'title'   => $kirby->site()->title()->or('Kirby Panel')->toString()
+                ];
+            },
+            '$translation' => function () use ($kirby) {
+                if ($user = $kirby->user()) {
+                    $translation = $kirby->translation($user->language());
+                } else {
+                    $translation = $kirby->translation($kirby->option('panel.language', 'en'));
```
Comment (lukasbestle) [inline src/Panel/Panel.php]:
```suggestion
                    $translation = $kirby->translation($kirby->panelLanguage());
```

I think in general the current translation should be used and not dynamically determined. Line 382 above also does it manually, which duplicates the logic over and over.

File: src/Panel/Panel.php [hunk 27]
```diff
@@ -89,14 +516,80 @@ public static function link(App $kirby): bool
...
+     */
+    public static function partial(App $kirby, string $component, array $data): array
+    {
+        // is it a partial request?
+        $request          = $kirby->request();
+        $include          = $request->header('X-Fiber-Include')   ?? get('_include');
+        $requestComponent = $request->header('X-Fiber-Component') ?? get('_component');
+
+        // split include string into an array of fields
+        $include = Str::split($include);
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: For a better overview and to avoid future regressions:

```suggestion
        $include = Str::split($include, ',');
```

File: src/Panel/Panel.php [hunk 28]
```diff
@@ -89,14 +516,80 @@ public static function link(App $kirby): bool
...
+        if (empty($requestComponent) === false && $requestComponent !== $component) {
+            return $data;
+        }
+
+        // otherwise filter data based on
+        // dot notation, e.g. `$props.tab.columns`
+        $partial = [];
+
+        // check if globals are requested and need to be merged
+        if (Str::contains(implode($include), '$')) {
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: For better performance the original header/request value before splitting should be preserved in a variable. Then we don't need to implode it again here.

File: src/Panel/Panel.php [hunk 29]
```diff
@@ -89,14 +516,80 @@ public static function link(App $kirby): bool
...
+
+        // if a new component is requested, the include
+        // parameter must be ignored and all data returned
+        if (empty($requestComponent) === false && $requestComponent !== $component) {
+            return $data;
+        }
+
+        // otherwise filter data based on
+        // dot notation, e.g. `$props.tab.columns`
+        $partial = [];
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: This variable is overwritten in the `foreach` loop below, but until then it is not used.

Edit: Ah, it's just a typo:

```suggestion
        $partials = [];
```

File: src/Panel/Panel.php [hunk 30]
```diff
@@ -89,14 +516,80 @@ public static function link(App $kirby): bool
...
+    public static function render(App $kirby, string $component, array $data)
     {
+        // get $fiber response array
+        $fiber = static::fiber($kirby, $component, $data);
+
+        // if requested, send $fiber data as JSON
+        if (static::isFiberRequest($kirby->request()) === true) {
+            return Response::json($fiber, null, get('_pretty'), [
+                'Vary'      => 'Accept',
+                'X-Fiber' => 'true'
```
Comment (lukasbestle) [inline src/Panel/Panel.php]:
```suggestion
                'Vary'    => 'Accept',
                'X-Fiber' => 'true'
```

File: src/Panel/Panel.php [hunk 31]
```diff
@@ -109,32 +602,260 @@ public static function render(App $kirby)
...
+     * @return \Kirby\Http\Response|false
+     */
+    public static function router(App $kirby, string $path = null)
+    {
+        if ($kirby->option('panel') === false) {
+            return false;
+        }
+
+        // switch off pagination exceptions
+        Pagination::$validate = false;
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: Why do we need this here? I'm sure there is a reason, a comment that explains it would be great (the current one is stating the obvious).

File: src/Panel/Panel.php [hunk 32]
```diff
@@ -109,32 +602,260 @@ public static function render(App $kirby)
...
+            }
+        }
+
+        // redirect routes
+        $routes[] = [
+            'pattern' => [
+                '/',
+                'installation',
+                'login',
+            ],
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: Is this route acting as a fallback for the defined patterns if the areas that normally define these routes are not active? So basically "if the user is already logged in, but visits `/login`, use this fallback"? That's how I understand it. If that's correct, we should add a comment that explains this behavior so we still know what this code does in the future.

File: src/Panel/Panel.php [hunk 33]
```diff
@@ -109,32 +602,260 @@ public static function render(App $kirby)
...
+        $view['path']       = Str::after($kirby->path(), '/');
+        $view['props']      = $view['props'] ?? [];
+        $view['search']     = $view['search'] ?? $kirby->option('panel.search.type', 'pages');
+
+        // make sure that routes are gone
+        unset($view['routes']);
 
-        return new Response($view->render());
+        // resolve lazy props
+        return $view;
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: Was `A::apply()` used here before? That's what the comment suggests. If so, we can just remove the comment.

File: src/Panel/Page.php (hunk 23 above)
Comment (lukasbestle) [reply src/Panel/Page.php]: Yes, I understand that.

The question is: Do we *have* partial requests that specifically don't need the breadcrumb? I think we should first assume that everything is needed (which allows for the simplest syntax without the closures) and then we should optimize the props that are not always needed.

I disagree with "we should probably use as many closures as possible": Calling all these closures takes time as well, so it also slightly reduces the performance – which is bad if it turns out that a prop is always needed in our frontend implementation.

Don't get me wrong: I'm 100% for optimizing and really like that the closures are lazy. We should just not use them everywhere without considering if they are needed.

Comment (distantnative) [reply src/Panel/Page.php]: We do, e.g. every few seconds for content locking. And we should make partial requests work best also for cases not yet used,  but e.g. used by developers. But agreed "as many closures as possible" is a bad extreme as well 😅 If it would be a straightforward return of a value, a closure is probably worse. But given that for this call we would merge flip and merge a collection and then loop across the values - and that with a page these partial content lock requests are happening every few seconds - I think here it would be worth it to keep it wrapped in a closure.

File: src/Panel/Panel.php (hunk 33 above)
Comment (distantnative) [reply src/Panel/Panel.php]: I believe so, must be a leftover. Let's remove it.

File: src/Panel/Panel.php (hunk 32 above)
Comment (distantnative) [reply src/Panel/Panel.php]: You understand it correctly. Let me add a comment.

File: src/Panel/Model.php (hunk 21 above)
Comment (distantnative) [reply src/Panel/Model.php:208]: It's still here https://github.com/getkirby/kirby/blob/feature/inertia/src/Panel/File.php#L155 - more specific to the `File` object. The previous implementation was a bit redundant.

File: src/Panel/Panel.php (hunk 31 above)
Comment (distantnative) [reply src/Panel/Panel.php]: Tbh, this originated even from the 2020 Inertia trial. I just tried without it and all pagination seems still to work. Let's remove it and if we actually encounter a reason bring it back with good documentation. Or if @bastianallgeier remembers what it was for, please yell :D

**Comment by distantnative** [comment]
@lukasbestle Implemented most of your comments. If @bastianallgeier and you can decide on the exception and the if-statements, we could wrap this up fully.

File: config/areas/settings.php [hunk 34]
```diff
@@ -20,6 +20,7 @@
                                     'text'    => $language->name(),
                                 ];
                             }),
+                            'license' => $kirby->user()->isAdmin() ? $kirby->system()->license() : 'Kirby 3',
```
Comment (distantnative) [inline config/areas/settings.php]: @bastianallgeier Isn't `$kirby->system()->license()` already handling this? Only based on the `access.settings` permission instead of admins. I think we shouldn't duplicate this logic, even worse have two different ones.

File: src/Panel/Page.php (hunk 23 above)
Comment (lukasbestle) [reply src/Panel/Page.php]: I agree! :)

File: config/areas/settings.php (hunk 34 above)
Comment (lukasbestle) [reply config/areas/settings.php]: I think Bastian's implementation is fine. Even a user who has access to the settings view should only be able to see the actual license code if they are admin. But you are right – maybe we should change this in the method itself instead.

In any case the fallback `'Kirby 3'` value should only be printed if a license is active (otherwise non-admins would still see a valid license even though the site is not registered):

```php
$license = $kirby->system()->license();
if ($license === true) {
    $license = 'Kirby 3';
} elseif ($license === false) {
    $license = null;
}
```

This would also make the prop value more consistent so we don't need [this change](https://github.com/getkirby/kirby/pull/3327/commits/f556c65e931291049f0f6a3b6b650f708ae91a2d).

File: src/Panel/Redirect.php (hunk 24 above)
Comment (lukasbestle) [reply src/Panel/Redirect.php:7]: Idea: What if we move the exception to `Kirby\Exception\RedirectException` and also add support for this to our CMS router (like `ErrorPageException`)? Then it's actually generally useful.

Comment (lukasbestle) [reply src/Panel/Redirect.php:7]: The custom exception handling code can actually be useful as we can use it to store the HTTP code of the redirect (301 or 302).

File: src/Cms/Api.php [hunk 35]
```diff
@@ -81,19 +79,7 @@ public function fieldApi($model, string $name, string $path = null)
...
-            return $file;
-        }
-
-        throw new NotFoundException([
-            'key'  => 'file.notFound',
-            'data' => [
-                'filename' => $filename
-            ]
-        ]);
+        return Panel::file($path, $filename);
```
Comment (lukasbestle) [inline src/Cms/Api.php:82]: To be honest I feel like this is a bit of a weird mix. The API suddenly depends on the Panel, even though it has been the other way around before and partly still is. The added methods in the `Panel` class seem generally useful, so maybe they could get a new home in the CMS namespace.

Unrelated, but still kind of related: I feel like the `Panel\Panel` class is a bit chaotic from an architectural standpoint. It only has static methods even though basically all methods rely on the `$kirby` object, some even implicitly (using the global `kirby()` helper). I think a singleton class that gets instantiated with the `$kirby` object would be a lot cleaner and more future-proof.

File: config/areas/settings.php (hunk 34 above)
Comment (distantnative) [reply config/areas/settings.php]: I would solve this within `System::license()` indeed. It's just weird if in that method we look at one permission just to check for another permission when we want to use the method.

Comment (lukasbestle) [reply config/areas/settings.php]: Then let's change `System::license()` to use the admin property instead of the access permission. I still think it should return `true` if the user is not admin. In the area, the code I posted above can then be used to convert that `true` value into a human-readable "Kirby 3" string.

File: panel/src/components/Navigation/Topbar.vue [hunk 36]
```diff
@@ -144,27 +144,18 @@
 </template>
 
 <script>
-import views from "@/config/views.js";
-
 export default {
+  props: {
+    areas: Object,
+    breadcrumb: Array,
+    license: [Boolean, String],
```
Comment (lukasbestle) [inline panel/src/components/Navigation/Topbar.vue]: This should always be `Boolean` because of Bastian's change. We can also simplify the `unregistered()` computed value or remove it and use `!this.license` directly.

File: src/Panel/Panel.php [hunk 37]
```diff
@@ -45,7 +200,290 @@ public static function customCss(App $kirby)
...
+    {
+        if ($js = $kirby->option('panel.js')) {
+            $asset = asset($js);
+
+            if ($asset->exists() === true) {
+                return $asset->url() . '?' . $asset->modified();
+            }
+        }
+
+        return false;
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: While we have the chance to change the return signature, I think we should change this and the `customCss()` method to return `null` in this case. Then we can type-hint the return value as `?string`.

File: src/Panel/Panel.php [hunk 38]
```diff
@@ -45,7 +200,290 @@ public static function customCss(App $kirby)
...
+     *
+     * @param \Kirby\Cms\User|null $user
+     * @param string|null $areaId
+     * @return bool
+     */
+    public static function firewall(?User $user = null, ?string $areaId = null): bool
+    {
+        // a user has to be logged in
+        if ($user === null) {
+            throw new PermissionException(t('error.access.panel'));
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: The translation keys are handled by the exception classes, so this should be:

```suggestion
            throw new PermissionException(['key' => 'access.panel']);
```

The same applies to other uses below.

File: src/Panel/Panel.php [hunk 39]
```diff
@@ -45,7 +200,290 @@ public static function customCss(App $kirby)
...
+
+    /**
+     * Creates global data for the Panel.
+     * This will be injected in the full Panel
+     * view via the script tag.
+     *
+     * @param \Kirby\Cms\App $kirby
+     * @return array
+     */
+    public static function globals(App $kirby): array
```
Comment (lukasbestle) [inline src/Panel/Panel.php:401]: Why do we have both the shared data in the `data()` method and this `globals()` method?

File: src/Panel/Panel.php [hunk 40]
```diff
@@ -89,14 +543,160 @@ public static function link(App $kirby): bool
...
+            'users'   => 'user',
+            'pages'   => 'page',
+            'account' => 'account'
+        ];
+
+        $modelName = $modelTypes[$modelType] ?? null;
+
+        if (Str::endsWith($modelType, '/files') === true) {
+            $modelName = 'file';
+        }
```
Comment (lukasbestle) [inline src/Panel/Panel.php:595]: For easier understanding:

```suggestion
        $modelType = trim(dirname($path), '/');
        if (in_array($path, ['site', 'account']) === true) {
            $modelName = $path;
        } elseif (Str::endsWith($modelType, '/files') === true) {
            $modelName = 'file';
        } else {
            $modelTypes = [
                'users' => 'user',
                'pages' => 'page'
            ];

            $modelName = $modelTypes[$modelType] ?? null;
        }
```

File: src/Panel/Panel.php [hunk 41]
```diff
@@ -89,14 +543,160 @@ public static function link(App $kirby): bool
...
+        switch ($modelName) {
+            case 'site':
+                $model = $kirby->site();
+                break;
+            case 'account':
+                $model = $kirby->user(null, $kirby->option('api.allowImpersonation', false));
+                break;
+            case 'page':
+                $id    = str_replace(['+', ' '], '/', basename($path));
+                $model = $kirby->page($id);
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: This kind of duplicates `Panel::page()`, but with a slightly different behavior (it also converts spaces to slashes for some reason).

File: src/Panel/Panel.php [hunk 42]
```diff
@@ -89,14 +543,160 @@ public static function link(App $kirby): bool
...
+        }
+
+        $kirby = kirby();
+
+        switch ($modelName) {
+            case 'site':
+                $model = $kirby->site();
+                break;
+            case 'account':
+                $model = $kirby->user(null, $kirby->option('api.allowImpersonation', false));
```
Comment (lukasbestle) [inline src/Panel/Panel.php]:
```suggestion
                $model = static::user();
```

File: src/Panel/Panel.php [hunk 43]
```diff
@@ -109,32 +709,289 @@ public static function render(App $kirby)
...
+     */
+    public static function setLanguage(App $kirby): ?string
+    {
+        // language switcher
+        if ($kirby->options('languages')) {
+            $session  = $kirby->session();
+            $language = get('language') ?? $session->get('panel.language', 'en');
+
+            // keep the language for the next visit
+            $session->set('panel.language', $language);
```
Comment (lukasbestle) [inline src/Panel/Panel.php]: For best performance, `$session->set()` should only be called if `$language` is not equals to the value that's already in the session:

```suggestion
            $sessionLanguage = $session->get('panel.language', 'en');
            $language = get('language') ?? $sessionLanguage;

            // keep the language for the next visit
            if ($language !== $sessionLanguage) {
                $session->set('panel.language', $language);
            }
```

File: tests/Cms/Routes/RouterTest.php [hunk 44]
```diff
@@ -294,8 +294,8 @@ public function testDisabledPanel()
             ]
         ]);
 
-        $this->assertNull($app->call('panel'));
-        $this->assertNull($app->call('panel/something'));
+        $this->assertFalse($app->call('panel'));
+        $this->assertFalse($app->call('panel/something'));
```
Comment (lukasbestle) [inline tests/Cms/Routes/RouterTest.php]: This comes from `Panel::router()`, right? Is there anything that speaks against returning `null` in the error case like before?

File: tests/Panel/FileTest.php [hunk 45]
```diff
@@ -21,14 +23,101 @@ public function isLocked(): bool
...
 class FileTest extends TestCase
 {
+    protected $app;
+    protected $fixtures;
+
+    public function setUp(): void
+    {
+        $this->app = new App([
+            'roots' => [
+                'index' => $this->fixtures = __DIR__ . '/fixtures/FileTest',
```
Comment (lukasbestle) [inline tests/Panel/FileTest.php]: Temporary files in test shouldn't be stored in `/fixtures`, but in `/tmp`. This allows us to easily differentiate between files that should be in the repo (= fixtures) and files that shouldn't (= tmp).

Also applies to the other `Panel` test classes.

File: src/Panel/Panel.php (hunk 40 above)
Comment (distantnative) [reply src/Panel/Panel.php:595]: To be honest, I find yours much harder to read than Bastian's 🙈

File: src/Panel/Panel.php (hunk 37 above)
Comment (distantnative) [reply src/Panel/Panel.php]: Sounds good 👍

File: src/Panel/Panel.php (hunk 39 above)
Comment (distantnative) [reply src/Panel/Panel.php:401]: Some shared data should be renewed on navigation, some globale can stay stable for the whole session (only passed on hard reload).

Comment (lukasbestle) [reply src/Panel/Panel.php:401]: Ah, I see. Maybe it's already enough to update the method description for `globals()` to explain this.

File: src/Cms/Api.php (hunk 35 above)
Comment (bastianallgeier) [reply src/Cms/Api.php:82]: Yeah, I was thinking about that as well. Maybe we could introduce a new Kirby\Cms\Finder class with methods like:`Finder::file()`

The architecture of the Panel class really grew a lot. There's definitely room for improvements. The singleton could be a good idea. But I wouldn't solve this in this PR.

File: src/Panel/Panel.php (hunk 39 above)
Comment (bastianallgeier) [reply src/Panel/Panel.php:401]: I extended the method description

File: src/Panel/Panel.php (hunk 40 above)
Comment (bastianallgeier) [reply src/Panel/Panel.php:595]: To be honest, I think both ways are not easy to read. Let's just keep it as it is.

File: src/Panel/Panel.php (hunk 41 above)
Comment (bastianallgeier) [reply src/Panel/Panel.php]: You are totally right. I replaced it with Panel::page. I have no idea why we want to support spaces here but not in Panel::page. This is probably just some weird artefact.

File: tests/Cms/Routes/RouterTest.php (hunk 44 above)
Comment (bastianallgeier) [reply tests/Cms/Routes/RouterTest.php]: ✅

File: tests/Panel/FileTest.php (hunk 45 above)
Comment (bastianallgeier) [reply tests/Panel/FileTest.php]: ✅

File: src/Cms/Api.php (hunk 35 above)
Comment (lukasbestle) [reply src/Cms/Api.php:82]: I've created an issue: https://github.com/getkirby/kirby/issues/3404

**Review by lukasbestle — DISMISSED** [review]

**Comment by lukasbestle** [comment]
Wohoo, I think this PR is finally ready for merging now! 🎉

I have created three issues for the remaining tasks, but they aren't blockers. So unless you see open tasks that need to be tackled before the merge, I think we should go ahead with the merge now to avoid further merge conflicts.

**IMPORTANT:** Please merge with GitHub's "Squash and merge" mode, otherwise we'll have 230 commits on `develop`.

**Review by lukasbestle — APPROVED** [review]
