### PR TITLE
Detect exceeded post_max_size on uploads #1812

### LINKED ISSUE #1812: "No uploaded files" error on uploading specific files
**Describe the bug**
Some files are not able to be uploaded because a "No uploaded files" error is thrown. This must be Windows or PHP 7.x (I think 7.3 or 7.2) specific bug.

**To Reproduce**
1. Create a new default page
2. Try to upload this file (https://send.firefox.com/download/45cc9d7ebef77dce/#VOT4tDtRhx43x3y-U1pkFA, password: kirby)
3. See error

**Expected behavior**
File is uploaded.

**Screenshots**

**Kirby Version**
3.1.4

**Console output**
grafik
grafik
grafik

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 67.0

**Additional context**
We tried to debug this but we found no reason/solution. See this thread: https://forum.getkirby.com/t/what-does-this-error-on-upload-mean-no-uploaded-files/14380

Issue happens with XAMPP and Wampserver.

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR
After all the additional upload checks, the exceeded post_max_size setting is now also caught and followed by a useful error message. 

## Related issues
- Fixes #1812

### CODE REVIEW

File: src/Api/Api.php [hunk 1]
```diff
@@ -690,7 +690,14 @@ public function upload(Closure $callback, $single = false): array
         ];
 
         if (empty($files) === true) {
-            throw new Exception(t('upload.error.noFiles'));
+            $postMaxSize       = 1024 * 1024 * (int)ini_get('post_max_size');
```
Comment (afbora) [inline src/Api/Api.php]: PHP allows shortcuts for byte values, including K (kilo), M (mega) and G (giga).

Do we need to convert this when ini settings `G` or especially `K`?

Comment (bastianallgeier) [reply src/Api/Api.php]: You are completely right! I just created a new `Str::toBytes` method to handle that.

**Review by lukasbestle — APPROVED** [review]
Awesome!
