### PR TITLE
fix: Deselect blocks on focus outside

### LINKED ISSUE #6599: Focus on Blocks is not removed when focus switches to other field
## Description
The focus on a block is not removed, when switching to a different field outside of the blocks/layout-field.

**Expected behavior**  
The focus and highlight on the block should be removed when the focus switches to another field.

**Screenshots**  
Bildschirmfoto 2024-08-04 um 14 16 05

## To reproduce
1. Create a Block in a blocks- or layout-field
2. Click in the Block, so it is focused and highlighted
3. Switch to a different field (e.g. text input or textarea) outside of the blocks- or layout-field
4. The block is still highlighted along with the highlighted field your are focussing

## Your setup
**Kirby Version**  
4.3.0

**Console output**  
There is no console output

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS Sonoma 14.1
 - Browser: Chrome (arm)
 - Version: 126.0.6478.183

### PR DESCRIPTION
**Pull request by bastianallgeier**
### 🐛 Bug fixes

- Deselect blocks when focus moves to an element outside of the blocks field #6599

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Forms/Blocks/Blocks.vue [hunk 1]
```diff
@@ -496,10 +499,7 @@ export default {
 		},
 		onClickGlobal(event) {
 			// ignore focus in dialogs or drawers to keep the current selection
-			if (
-				event.target.closest(".k-dialog") ||
-				event.target.closest(".k-drawer")
-			) {
+			if (focusIsInModal(event.target)) {
```
Comment (distantnative) [inline panel/src/components/Forms/Blocks/Blocks.vue]:
```suggestion
			if (focusIsInModal(event.target) === true) {
```

I am tempted whether we want to drop the `=== true` etc. on the PHP side more and more as typing has grown to be quite strong there and if the methods are typed to return boolean, we could rely on that (as we started using it to avoid ambiguous values leading to weird truths/falsy  results). But I think on the JS side the typing isn't there really, so maybe better to still keep it?

File: panel/src/components/Forms/Blocks/Blocks.vue [hunk 2]
```diff
@@ -544,6 +544,17 @@ export default {
 				this.selected = [block.id];
 			}
 		},
+		onFocusGlobal(event) {
+			// ignore focus in dialogs or drawers to keep the current selection
+			if (focusIsInModal(event.target)) {
```
Comment (distantnative) [inline panel/src/components/Forms/Blocks/Blocks.vue]:
```suggestion
			if (focusIsInModal(event.target) === true) {
```

**Review by distantnative — APPROVED** [review]
