### PR TITLE
Fix password reset dialog dark mode style

### LINKED ISSUE #7003: [v5] Passwort reset dialog has missing dark mode styles
Image

`.k-user-info` class

## Your setup
**Kirby Version**  5.0-beta.3

### PR DESCRIPTION
**Pull request by afbora**
v5-develop test_panel_login

### Fixes
- [v5] Passwort reset dialog has missing dark mode styles #7003

### Breaking changes
None

## Ready?

- [ ] In-code documentation (wherever needed)
- [ ] Unit tests for fixed bug/feature
- [ ] Tests and CI checks all pass

### For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [ ] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Views/Users/UserInfo.vue [hunk 1]
```diff
@@ -31,7 +31,7 @@ export default {
 	height: var(--height-lg);
 	gap: 0.75rem;
 	padding-inline: var(--spacing-2);
-	background: var(--color-white);
+	background: light-dark(var(--color-white), var(--color-gray-850));
```
Comment (distantnative) [inline panel/src/components/Views/Users/UserInfo.vue]:
```suggestion
	background: var(--item-color-back);
```

I think we could reuse this here.

Comment (afbora) [reply panel/src/components/Views/Users/UserInfo.vue]: Ahh I'm was not aware of this var. Nice.

**Review by bastianallgeier — APPROVED** [review]
