### PR TITLE
fix: Add missing array check and fix invalid label value in the entries field

### LINKED ISSUE #7265: [v5] Console error for language translation dialog with entries field
## To reproduce

1. Add two languges,
2. Add translation key with  entries field from primary language,
3. Go to seconary language and edit the that key,
4. See console error: TypeError: Cannot read properties of null (reading 'map')

## Your setup
**Kirby Version**  
5.0.0-rc.3

**Console output**  

> TypeError: Cannot read properties of null (reading 'map')

### PR DESCRIPTION
**Pull request by bastianallgeier**
### Fixes

- Passing `false` as label value to `<k-field>` will no longer throw a console error. We use this in the new `<k-entries-field>` to disable labels for nested fields.  
- The new `<k-entries-field>` checks for a valid array as given value and will no longer throw a console error if `null` is passed. https://github.com/getkirby/kirby/issues/7265

### Breaking changes

None

### For review team

- [ ] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Forms/Field/EntriesField.vue [hunk 1]
```diff
@@ -230,7 +230,7 @@ export default {
 		value: {
 			handler(entries) {
 				// no need to add ids again if the values are the same
-				if (entries === this.values) {
+				if (entries === this.values || Array.isArray(entries) === false) {
```
Comment (distantnative) [inline panel/src/components/Forms/Field/EntriesField.vue]: `Question:` Based on the `value` prop type this should only be an array. So I would think the only other value but an array is undefined/null. Which then we say defaults to an empty array in the prop definition. Which is then why I am wondering if instead of ignoring this new input here, we should rather set `this.entries = []`?

Comment (bastianallgeier) [reply panel/src/components/Forms/Field/EntriesField.vue]: I've changed it.

File: panel/src/components/Forms/Field/EntriesField.vue [hunk 2]
```diff
@@ -229,6 +229,11 @@ export default {
 	watch: {
 		value: {
 			handler(entries) {
+				if (Array.isArray(entries) === false) {
+					this.entries = [];
+					return;
+				}
+
```
Comment (distantnative) [inline panel/src/components/Forms/Field/EntriesField.vue]:
```suggestion
				entries ??= [];

```

`Suggestion:` Shouldn't this be enough? Then we could still benefit from the `entries === this.values` check?

**Review by distantnative — APPROVED** [review]
