### PR TITLE
fix: Refresh file view after replacing file

### LINKED ISSUE #7956: File preview doesn't change/reload after it replaced
## To reproduce

1. Go to any image detail page (file-view)
2. Try to replace the image
3. See the issue that image not changed (still old image visible)

## Your setup
As far as I see this happens after 5.0.0

### PR DESCRIPTION
**Pull request by distantnative**
### 🐛 Bug fixes

- Panel file view: refresh view after replacing the file
#7956

## For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
@afbora Could you please give this a try if it also solves it for you?

File: panel/src/components/Views/ModelView.vue [hunk 1]
```diff
@@ -111,6 +113,11 @@ export default {
 				language: this.$panel.language.code
 			});
 		},
+		onModelUpdate({ path } = {}) {
+			if (path === this.api) {
+				this.$panel.view.refresh();
+			}
+		},
```
Comment (distantnative) [inline panel/src/components/Views/ModelView.vue:120]: `Discuss:` Kinda unsure what name for ``path` would be the correct one here

**Review by afbora — APPROVED** [review]
I've done a lot of testing and it seems to be working perfectly 👍

File: panel/src/components/Views/ModelView.vue (hunk 1 above)
Comment (distantnative) [reply panel/src/components/Views/ModelView.vue:120]: @bastianallgeier Maybe you have an opinion/idea here. The PR in general seems fine with the tests from @afbora.

Comment (bastianallgeier) [reply panel/src/components/Views/ModelView.vue:120]: Ha, good question. I think path is not too bad to be honest. API or ID could be alternatives, but they are all quite confusing, because not really accurate too.

Comment (distantnative) [reply panel/src/components/Views/ModelView.vue:120]: Ok, let's keep `path` then for now. I think the Panel events system would need a clean up/refactoring eventually anyways. Then we can tackle that down the road.
