### PR TITLE
Fix failing first/one/row queries when using fetch closure

### LINKED ISSUE #5615: Database: combination of unsuccessful `first()` and custom fetch Closure throw an exception
## Description

```php
// throws exception
db()->table('users')
  ->where('username', 'doesnt-exist-at-all')
  ->fetch(fn($row) => some_custom_method($row))
  ->first();

// works
db()->table('users')
  ->where('username', 'doesnt-exist-at-all')
  ->fetch(fn($row) => some_custom_method($row))
  ->limit(1)
  ->all();
```

A combination of database `fetch` Closure and unsuccessful `first` query results in error in `src/Database/Database.php:383`.

The difference between the `first()` call and the `->limit(1)->all()` call is that one calls `PDOStatement::fetch` and the other calls `PDOStatement::fetchAll` - and Kirby, expecting empty array in case of query with 0 returned rows, just tries to foreach the results.

I think the fix is to simply add guard against `$results !== false` (or maybe `is_array($results`), but you might also want to force `fetchAll` method if fetch is closure… there are many ways how to go about this.

**Expected behavior**  

I expect both calls to succeed (or return falsy result).

## To reproduce

1. Create a database
2. Do an unsuccessful call
3. Observe error

## Your setup
**Kirby Version**  
3.9.6.1

### PR DESCRIPTION
**Pull request by adamkiss**
### Fixes

- #5615 

This PR replaces #5639 so I can work on it instead Nico. I also added his reformatting from that PR, and added a unit test. 

Note: I had to change function descriptions on first/one/row, because since `->fetch()->first()` now works, it can return absolutely anything (in tests, I use the fetch function to return string)

cc @lukasbestle @distantnative 

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

File: src/Database/Query.php [hunk 1]
```diff
@@ -623,7 +623,7 @@ protected function execute(string|array $sql, array $params = [])
 	/**
 	 * Selects only one row from a table
 	 */
-	public function first(): object|array|false
+	public function first(): mixed
```
Comment (distantnative) [inline src/Database/Query.php:626]: @adamkiss what else do we need to support here? with what use case do the more specific typings fail?

Comment (adamkiss) [reply src/Database/Query.php:626]: @distantnative anything that your `fetch(Closure)` returns. If it returns a string… `first()` returns a string as well. See the added unit test - that's how I actually found out that `->fetch()->first()` will do that.

File: src/Database/Database.php [hunk 2]
```diff
@@ -379,8 +386,14 @@ public function query(string $query, array $bindings = [], array $params = [])
...
-			foreach ($results as $key => $result) {
-				$results[$key] = $options['fetch']($result, $key);
+			if ($options['method'] === 'fetchAll') {
+				// fetching multiple records
+				foreach ($results as $key => $result) {
+					$results[$key] = $options['fetch']($result, $key);
+				}
+			} elseif ($options['method'] === 'fetch' && $results !== false) {
+				// fetching a single record
+				$results = $options['fetch']($results);
```
Comment (lukasbestle) [inline src/Database/Database.php]: I think we need to explicitly pass `null` as the second argument, otherwise we will get "too few arguments" errors when using a closure or callable that expects two arguments.

Comment (distantnative) [inline src/Database/Database.php]: Not sure if I would tie this as closely to the exact methods. How about
`is_iterable($results)` for the first if and just `$results !== false` for the elseif?

**Review by lukasbestle — COMMENTED** [review]
I haven't tested it myself, but the changes look good to me. A small suggestion:

File: src/Database/Database.php (hunk 2 above)
Comment (adamkiss) [reply src/Database/Database.php]: Can't do - the method is the differentiator. the fetch (`->first()` et al) returns:

```
[
	'column1' => 'value',
	'column2' => 'value'
]
```

which passes `is_iterable()` as well, except now we're trying to send 'value' to closure expecting array.

Comment (lukasbestle) [reply src/Database/Database.php]: Ah, right, of course. Each row is an array.

**Review by lukasbestle — APPROVED** [review]
