### PR TITLE
`Dir::index()`: fix `$ignore` parameter

### LINKED ISSUE #5010: `Dir::index` - `ignore` argument doesn't do anything
## Description
One of the parameters of `Dir::index` doesn't do anything other than being pass along to a recursive, call where it doesn't do anything again.

**Expected behavior**  
Makes `Dir::index` ignore file, either by relative name (`file.txt`), or absolute name.

## To reproduce
Just look at the source: https://github.com/getkirby/kirby/blob/066b0506a81fdd331edc54add601d907a61ebbb4/src/Filesystem/Dir.php#L143-L165

`$ignore` is used only once, and that's when the recursion is called.

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- `Dir::index()`: `$ignore` parameter works now 
 #5010

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

File: src/Filesystem/Dir.php [hunk 1]
```diff
@@ -143,14 +143,18 @@ public static function files(
...
-		array|null $ignore = null,
+		array|null $ignore = [],
 		string $path = null
 	): array {
 		$result = [];
 		$dir    = realpath($dir);
 		$items  = static::read($dir);
 
 		foreach ($items as $item) {
+			if (in_array($item, $ignore) === true) {
```
Comment (lukasbestle) [inline src/Filesystem/Dir.php:154]: Needs to check if `$ignore` is an array first (could be `null`).

**Review by lukasbestle — COMMENTED** [review]
I think the ignore implementation should be consistent with the one of the `Dir::copy()` method as both have a recursive mode. `Dir::copy()` uses the full path to compare against the ignore list, not just the path segment.

Also it should support the same `$ignore = false` mode like `Dir::copy()` does (which disables the global ignore list).

**Comment by distantnative** [comment]
@lukasbestle but wouldn't it be then inconsistent to `Dir::read()`? Which I thought is much closer related to the index method.

File: src/Filesystem/Dir.php (hunk 1 above)
Comment (distantnative) [reply src/Filesystem/Dir.php:154]: Probably better not allow passing `null` - or what use case would passing `null` have?

**Comment by lukasbestle** [comment]
`Dir::read()` is non-recursive though. I see what you mean and I feel like there is no right or wrong here.

File: src/Filesystem/Dir.php (hunk 1 above)
Comment (lukasbestle) [reply src/Filesystem/Dir.php:154]: Not adding a breaking change. It could be that some users explicitly copied the default values into their method calls (for whatever reason). This will then break.

I'm in favor of removing the `null` value (or replacing it with `array|bool` like with `Dir::copy()` like I wrote above). But then it should happen in a major release.

**Comment by bastianallgeier** [comment]
I think I would keep null for 3.9.2 and remove it in the next major version.

File: src/Filesystem/Dir.php (hunk 1 above)
Comment (bastianallgeier) [reply src/Filesystem/Dir.php:154]: Let's change the type definition in the next major.

**Review by bastianallgeier — APPROVED** [review]
