### PR TITLE
fix: Tag icon styling

### LINKED ISSUE #7938: Slight visual regression in Structure containing Link field
## Description

For a menu builder as [described in the cookbook](https://getkirby.com/docs/cookbook/navigation/menu-builder), a Structure field contains a Link sub-field. In Kirby 5.3.0 (first image) its preview is slightly broken compared to 5.2.3 (second image):

A Structure field showing the preview of a set of internal pages, looking slightly broken

The same structure field, looking better in the previous Kirby version

<details>
<summary>The structure blueprint, for convenience</summary>

```yaml
mainmenu:
  label: Main Menu
  type: structure
  fields: 
    link:
      label: Link
      type: link
      options:
        - page
        - url
    title:
      label: Title
      type: text
      help: Required for URLs
```
</details>

### PR DESCRIPTION
**Pull request by distantnative**
### 🐛 Bug fixes

- Fixed styling of tags with icons (e.g. link field preview)
#7938

## For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: panel/lab/components/tags/1_tag/index.vue [hunk 1]
```diff
@@ -26,17 +26,17 @@
...
-				:image="{ icon: 'heart' }"
+				:image="{ icon: 'heart', back: 'pattern' }"
 				:removable="true"
 				:theme="theme"
 				text="Foo"
 			/>
 			<k-tag
 				:disabled="true"
-				:image="{ icon: 'heart' }"
+				:image="{ icon: 'heart', back: 'pattern' }"
```
Comment (distantnative) [inline panel/lab/components/tags/1_tag/index.vue:39]: `Comment:` Black background was obscuring the issue. The new styling looks slightly worse with black background, but now does work with all other backgrounds.

File: panel/src/components/Forms/Previews/LinkFieldPreview.vue [hunk 2]
```diff
@@ -1,10 +1,10 @@
...
-		:class="{
-			'k-link-field-preview': true,
-			'k-url-field-preview': isLink,
-			[$attrs.class]: true
-		}"
+		:class="[
+			'k-link-field-preview',
+			{ 'k-url-field-preview': isLink },
+			$attrs.class
+		]"
```
Comment (distantnative) [inline panel/src/components/Forms/Previews/LinkFieldPreview.vue:7]: `Explanation:` `[$attrs.class]: true` did produce an `undefined` class

File: panel/src/components/Navigation/Tag.vue [hunk 3]
```diff
@@ -203,4 +202,7 @@ button.k-tag:not([aria-disabled="true"]) {
 	color: var(--tag-color-disabled-text);
 	cursor: not-allowed;
 }
+.k-tag:where([aria-disabled="true"]) .k-tag-image {
+	opacity: var(--opacity-disabled);
+}
```
Comment (distantnative) [inline panel/src/components/Navigation/Tag.vue:207]: `Comment:` Looked a bit odd that image or icon would be rendered just normal on disabled tags. I think with the opacity it looks better.

**Comment by afbora** [comment]
Aside from @distantnative inline comments, the issue seems to be resolved. LGTM 👍

**Review by lukasbestle — APPROVED** [review]
Merging this into 5.3.1 as it's already making it look a lot less broken. We can still tweak the styling later if necessary.
