### PR TITLE
fix: Use `<div>` for `k-input-element`

### LINKED ISSUE #8018: 'k-textarea-input' div is not allowed inside 'k-input-element' span
Hello kirby team,

I don't know, if You're following the W3 spec, but if so,
please have a look at the rendered textarea field.
The `k-textarea-input` div is a block element inside an inline `span` element, which doesn't pass the validator.
Thank You!

---

kirby version: 5.3.1

### PR DESCRIPTION
**Pull request by distantnative**
### ♻️ Refactored

- Ensure not wrapping `<div>` tags with `<span>` tags in `<k-input>`
#8018

## For review team

- [ ] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Forms/Input.vue [hunk 1]
```diff
@@ -12,7 +12,7 @@
 		>
 			<slot name="before">{{ before }}</slot>
 		</span>
```
Comment (distantnative) [inline panel/src/components/Forms/Input.vue]: `Discuss:` Should we also switch over to `div` tags for `k-input-before` and `k-input-after`?

Comment (bastianallgeier) [reply panel/src/components/Forms/Input.vue]: Yes, I would say so.

**Review by bastianallgeier — APPROVED** [review]
