### PR TITLE
Fix double slashes in asset URLs with base URL `/`

### LINKED ISSUE #4508: Double-slashes when using assets helper
## Description
After running with panel issues as mentioned in issue #4443 we placed `'url' => '/'` in the config.php to get the panel working again. But that somehow breaks the assets helper, it now puts two slashes before the url:

``

With this in the snippet:

`<?= asset('assets/images/logo.png')->url() ?>`

**Expected behavior** 

A correct asset link, in this example:
`"/assets/images/logo.png"`

## To reproduce

1. Place `'url' => '/'` in config.php
1. Place asset on snippet/template using asset helper
2. It is rendered with double slashes and becomes unresolvable

## Your setup
**Kirby Version**  
3.7.1

We updated to the latest version after learning it fixes panel issues regarding https, but this issue remains somehow.

### PR DESCRIPTION
**Pull request by lukasbestle**
### Fixes

- Asset URLs no longer start with two slashes if the site's base URL was configured as `/` #4508

### Breaking changes

None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

File: src/Filesystem/Asset.php [hunk 1]
```diff
@@ -38,7 +38,7 @@ public function __construct(string $path)
 		$this->setProperties([
 			'path' => dirname($path),
 			'root' => $this->kirby()->root('index') . '/' . $path,
-			'url'  => $this->kirby()->url('index') . '/' . $path
+			'url'  => rtrim($this->kirby()->url('index'), '/') . '/' . $path
```
Comment (afbora) [inline src/Filesystem/Asset.php]: This solution seems correct. But I think seems still confusing. `$this->kirby()->url('index')` should returns stable/consist value that with or without slash. So we shouldn't need either the `rtrim` method or the extra slash `/` 🤔

Comment (lukasbestle) [reply src/Filesystem/Asset.php]: `$this->kirby()->url('index')` by default always returns a value without trailing slash, unless it's `/`. This is handled by `Core::urls()` and `Environment::baseUrl()`.

`rtrim()` was the simplest solution I came up with (in the amount of code) and also prevents regressions in case the `index` URL for some reason ever *does* contain a trailing slash.

Open for suggestions though. :)

Comment (afbora) [reply src/Filesystem/Asset.php]: I agree with you and favor the simple solution if a more general but stable solution will cause regressions 👍

Comment (afbora) [reply src/Filesystem/Asset.php]: I'm good overview for this parts. But I just wonder that why didn't we do the same for `index` while the `base` url doesn't end with slash. I guess @bastianallgeier have an idea about that.
https://github.com/getkirby/kirby/blob/cfac315bc685193d0fe1b10fe3bf45a96e48fd15/src/Cms/Core.php#L459-L475

Comment (lukasbestle) [reply src/Filesystem/Asset.php]: Thinking about it, maybe we should convert `/` to an empty string already in `baseUrl`. Then it would be really consistent. But not sure if this would break other parts of the system.

Comment (lukasbestle) [reply src/Filesystem/Asset.php]: Just tested it with an empty `baseUrl`. This breaks immediately because some parts of the core expect the index URL to be non-empty. E.g. `config/routes.php:17` tries to call `Str::after()`, which fails with an empty needle.

So I think for now we need to keep the `baseUrl` as `/` in this special case and handle the trailing slash down the line (like in `Asset` in this case).

Comment (afbora) [reply src/Filesystem/Asset.php]: Then it seems like the safest way to go with your simple solution as this PR, do I understand right? 

But I think we need one more change: 
https://github.com/getkirby/kirby/blob/fix/4508-asset-url-double-slash/src/Panel/Document.php#L279

Comment (lukasbestle) [reply src/Filesystem/Asset.php]: Hm, good point. I'm a bit hesitant to sprinkle the `rtrim()` fix throughout the codebase through. If more parts are affected, this solution feels like a hack.

I moved this issue to 3.7.3. Let's wait for @bastianallgeier's opinion. Hopefully we can find a cleaner solution that fixes the issue in general.

Comment (bastianallgeier) [reply src/Filesystem/Asset.php]: To be honest, the cleanest and technically correct solution would be if all URLs always had a trailing slash. This would be a serious change though that would have serious implications for pretty much any part of the system. I agree that this seems to be the most stable version to keep everything as it is.

Comment (lukasbestle) [reply src/Filesystem/Asset.php]: You are right, a trailing slash really makes the most sense.
Do you think it's just risky in general as the whole system needs to be adapted or would it be a breaking change that users and plugin devs would also need to adapt to?

In any case, the switch to a trailing slash is only something we can do in a major release. If you agree, I can verify all uses of the index URL to make sure that they support the special `/` value. Then we can already fix the bug in 3.7.4.

**Comment by lukasbestle** [comment]
Just found out we already have `$kirby->url('base')` that handles the `rtrim()`.

**Review by distantnative — APPROVED** [review]
