### PR TITLE
fix: Abort previous Panel view requests

### LINKED ISSUE #6536: Slower navigation requests still go through even if already navigated elsewhere
Panel:
1. Click on a slow-loading view (e.g. system)
2. Immediately click on a different view
3. Panel navigates to second view, but as soon as the first slow requests succeeds jumps back there

**Expected behavior:**
First navigation request should be aborted once a new comes in.

### PR DESCRIPTION
**Pull request by distantnative**
## Description

I tried to catch the abort request error right in the view code, but only could manage to silence it in the error handler.

### 🐛 Bug fixes

- Subsequent Panel view request cancel out ongoing (slow) previous view request to ensure navigation always lands at the latest requested view
#6536

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: panel/src/panel/view.js [hunk 1]
```diff
@@ -23,6 +23,21 @@ export default (panel) => {
...
+		 * Load a view from the server and
+		 * cancel any previous request
+		 *
+		 * @param {String|URL} url
+		 * @param {Object|Function} options
+		 * @returns {Object} Returns the current state
+		 */
+		async load(url, options = {}) {
+			// cancel any previous request
+			this.abortController?.abort();
```
Comment (bastianallgeier) [inline panel/src/panel/view.js:36]: `Question:` Can you help me understand why this line is needed when the load method in feature.js already aborts the controller?

Comment (distantnative) [reply panel/src/panel/view.js:36]: But the load method in `feature.js` isn't aborting the controller. It's just replacing it with a new abort controller, but leaving the old untouched. I didn't implement the abort call in `feature.js` as I was wondering if in other features (e.g. dialogs, drawers) it could lead to problems aborting an ongoing request. Whereas with view navigation, I was more confident that aborting the request is the right thing to do.

Comment (bastianallgeier) [reply panel/src/panel/view.js:36]: Oh, I completely missed that. Makes perfect sense now.

**Review by bastianallgeier — APPROVED** [review]
Just double-checked with a super slow loading system view, by injecting a sleep call and it works great.
