### PR TITLE
Continue passing $inline parameter to Markdown component

### LINKED ISSUE #4126: [3.6.2]: kirbytextinline()/kti() incorrectly wraps with <p>/</p> tags
## Description
I believe this is a new regression in 3.6.2:

When using `kirbytextline()`/`kti()` the resulting strings are wrapped in paragraph tags.

**Expected behavior**  
The result should just be the inner contents.

## To reproduce

```php
<?php

echo kirbytextinline('Hello');
// output: <p>Hello</p>
// expected: Hello

// assume field is just Foo
echo $page->field()->kirbytextinline();
// output: <p>Foo</p>
// expected: Foo
```

## Your setup
**Kirby Version**  
`3.6.2`

### PR DESCRIPTION
**Pull request by neildaniels**
## Describe the PR

With Kirby 3.6.2, the $inline parameter for various Markdown methods was deprecated. This parameter was no longer being passed to Markdown component overrides, which is a breaking change. This PR continues to pass that until the parameter can be formally removed.

## Release notes

- Continues passing `$inline` parameter to Markdown component plugins

## Breaking changes

None

## Related issues/ideas

- Fixes #4126 

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

File: src/Cms/App.php [hunk 1]
```diff
@@ -806,7 +806,7 @@ public function kirbytext(string $text = null, array $data = [], bool $inline =
 
         $text = $this->apply('kirbytext:before', compact('text'), 'text');
         $text = $this->kirbytags($text, $options);
-        $text = $this->markdown($text, $options['markdown']);
+        $text = $this->markdown($text, $options['markdown'], $options['markdown']['inline']);
```
Comment (afbora) [inline src/Cms/App.php]: The `markdown()` method has no 3rd parameter and the `inline` parameter is already processed in `$options`.

Comment (neildaniels) [reply src/Cms/App.php]: Thanks for pointing that out. I put my code in the wrong spot.

File: src/Cms/App.php [hunk 2]
```diff
@@ -924,7 +924,8 @@ public function markdown(string $text = null, $inline = null): string
             (array)$options
         );
 
-        return ($this->component('markdown'))($this, $text, $options);
+        $inline = $options['inline'] ?? false;
```
Comment (distantnative) [inline src/Cms/App.php:929]: Could you add an inline `/// TODO:` comment please that we deprecate passing the parameter in 3.7 and remove passing it in 3.8? Thanks.

**Review by bastianallgeier — APPROVED** [review]

**Comment by distantnative** [comment]
Thanks a lot @neildaniels
