### PR TITLE
fix: Wait for upload and refresh the view afterwards

### LINKED ISSUE #7249: [v5] Uploading a file by dragging it over the textarea field doesn't work
## To reproduce

1. Go to panel 
2. Edit any page that have textarea field
3. Drag and drop a file into textarea field from your device to upload
4. See that file drag text will be disappear

## Related issue: 

Fabian's markdown editor has this issue:
https://github.com/fabianmichael/kirby-markdown-field/issues/196

## Your setup
**Kirby Version**  
5.0.0-rc.2

### PR DESCRIPTION
**Pull request by bastianallgeier**
### Enhancements

- New async `TextareaInput.restoreSelection()` method 
- New `panel.upload.announce()` method, which sends the success notification and `model.update` event after uploads have successfully completed. 
- The upload module now sends a `file.upload.error` event for every file that could not be uploaded.
- Various TextareaInput methods have been turned into async methods for more stable async/await control throughout all TextareaInput methods.
  - `insert`
  - `insertFile`
  - `insertUpload`
  - `prepend`
  - `toggle`
  - `wrap`

### Fixes

- `panel.content.save()` now calls `panel.content.cancelSaving()` to make sure that any old scheduled save requests are properly cancelled. This could have lead to potential race conditions before.
- The `FilesField` no longer sends unnecessary `file.upload` and `model.update` emitters after upload. Those lead to duplicate section reload requests so far. After uploads, the `panel.upload.done()` already takes care of reloading the current view and all its sections. 
- The `TextareaInput.insertUpload()` method now uses `await panel.content.update()` to push text value changes directly to the changes API and to reload the view correctly. This fixes https://github.com/getkirby/kirby/issues/7249
- The upload module sends the `file.upload` event directly when a file has been uploaded and passes the file object correctly. Before this change, the file.upload event was only called in the FilesField and FilesSection components when all uploads finished. 
- Both the `upload.done()` and `upload.cancel()` handlers now properly emit the `complete` event if there are any completed uploads. 

### Refactoring

- `TextareaInput.selectionRange` and `TextareaInput.restoreSelection()` are used to replace the old `restoreSelectionCallback` method in dialog events for better async control.
- Removed unnecessary complete handler in `FilesSection`. The upload module already takes care of the notifications and events. 

### Deprecated

- `TextareaInput.restoreSelectionCallback()` Use `TextareaInput.restoreSelection()`.

### Breaking changes

None 

## Sandbox

There's a new "Uploads" tab in the Textarea setup in the sandbox. 

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Tests and CI checks all pass

### For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Comment by afbora** [comment]
@bastianallgeier Still doesn't work :(

**Comment by bastianallgeier** [comment]
That's very weird. Works perfectly for me now. Ok, then I need to double-check again.

**Comment by distantnative** [comment]
It does work for me. @afbora sure there aren't any old files cached, e.g. in `media/panel` if you're running it via `npm run build` not `npm run dev`?

**Comment by afbora** [comment]
@distantnative I'm testing always via `build`. The issue still valid for me. Sometimes works sometime not. With this PR better but it's not completely fixed.

**Comment by distantnative** [comment]
@afbora Very weird. Any insights on the preconditions to have it succeed vs. when it fails?

**Comment by afbora** [comment]
@distantnative I can reproduce it with every request via browser's slow 4G or 3G network throttling feature. 

Not sure but I think this content lost happens when pages/field/files request done after save request.

**Comment by distantnative** [comment]
@afbora You mention "save request" - so it's not just uploading what you are trying to do (as described in the original issue) but some combination with uploading and directly saving (and if you say slow connection, maybe you are trying to super quickly save before the upload request is actually done)?

But then I would think this fix might still be right, but we have in addition still problems with a race condition between `content.save` and `content.publish` (or similar).

**Comment by afbora** [comment]
I mean  `/save` request after uploading done (automaticly and after modal closed) with "save request" not page save request via manual clicking.

**Comment by distantnative** [comment]
Mmm ok. Couldn't reproduce it. Even when throttling speed.

One thought could be if `insertFile` takes longer than the update call. There is a setTimeout involved. So maybe that.

**Comment by afbora** [comment]
@distantnative Here the screencast:

https://github.com/user-attachments/assets/92da57b9-fdaf-41b3-8909-ad5f3736b790

**Comment by bastianallgeier** [comment]
I think our main issue really is the view reloading in the done event of the uploader. I have an idea.

**Comment by bastianallgeier** [comment]
@distantnative @afbora I've refactored the code quite a bit and I hope this PR is not getting too big. 

- We had a couple places in the TextareaInput component that made race conditions possible. I've refactored them with async/await to be more in control of what we actually do
- The upload module had a few weird inconsistencies with event emitting. I've cleaned it up to better see what we are doing at which point
- We only need to emit the `model.update` event once all file uploads are finished. This will trigger all sections to be reloaded. A full `panel.view.reload()` is not necessary here and will always lead to issues with open drawers. 

## Sandbox

I've added a new "Others > Uploads" examples page where we can test textarea, structure, blocks and files fields with uploads and we can also see if a files section updates accordingly.

**Comment by afbora** [comment]
@bastianallgeier I've tested now. There is restore selection issue at first glance. 

Click/select to random place of the paragraph text and try to drag/drop items to selected area. You can repeat this with selecting random places of the text with drag/drop an item. You'll see the issue that dragtexts are inserted always same places instead of selected area.

File: panel/src/components/Forms/Input/TextareaInput.vue [hunk 1]
```diff
@@ -154,51 +156,57 @@ export default {
...
 		focus() {
 			this.$refs.input.focus();
 		},
-		insert(text) {
+		async insert(text) {
 			const input = this.$refs.input;
 			const current = input.value;
 
 			if (typeof text === "function") {
 				text = text(this.$refs.input, this.selection());
```
Comment (distantnative) [inline panel/src/components/Forms/Input/TextareaInput.vue]:
```suggestion
				text = text(input, this.selection());
```

File: panel/src/components/Forms/Input/TextareaInput.vue [hunk 2]
```diff
@@ -291,36 +299,44 @@ export default {
...
+		},
+		selectionRange() {
+			return {
+				start: this.$refs.input.selectionStart,
+				end: this.$refs.input.selectionEnd
+			};
+		},
+		async setSelectionRange({ start, end }) {
+			this.$refs.input.setSelectionRange(start, end);
+			return this.$nextTick();
```
Comment (distantnative) [inline panel/src/components/Forms/Input/TextareaInput.vue]:
```suggestion
			await this.$nextTick();
```

`Suggestion:` I feel we do not actually want to return the promise - this method probably should run as void, shouldn't it? But await the next tick before the method resolves.

File: panel/src/panel/upload.js [hunk 3]
```diff
@@ -74,12 +78,9 @@ export default (panel) => {
 			panel.dialog.close();
 
 			if (this.completed.length > 0) {
+				await this.emit("complete", this.completed);
 				await this.emit("done", this.completed);
-
-				if (panel.drawer.isOpen === false) {
```
Comment (distantnative) [inline panel/src/panel/upload.js:79]: `Test:` Adding this also as a todo for myself to test if it still works properly inside drawers now this guard has been removed.

File: panel/src/components/Forms/Input/TextareaInput.vue [hunk 4]
```diff
@@ -291,36 +299,44 @@ export default {
...
 		},
-		toggle(before, after) {
+		async toggle(before, after) {
 			after = after ?? before;
```
Comment (distantnative) [inline panel/src/components/Forms/Input/TextareaInput.vue]:
```suggestion
			after ??= before;
```

File: panel/src/components/Forms/Input/TextareaInput.vue [hunk 5]
```diff
@@ -337,8 +353,8 @@ export default {
 		upload() {
 			this.$panel.upload.pick(this.uploadOptions);
 		},
-		wrap(before, after) {
-			this.insert(before + this.selection() + (after ?? before));
+		async wrap(before, after) {
+			return this.insert(before + this.selection() + (after ?? before));
```
Comment (distantnative) [inline panel/src/components/Forms/Input/TextareaInput.vue]:
```suggestion
		async wrap(before, after) {
			after ??= before;		
			await this.insert(before + this.selection() + after);
```

File: panel/src/components/Forms/Input/TextareaInput.vue [hunk 6]
```diff
@@ -291,36 +299,44 @@ export default {
...
+			return async (callback) => {
+				await this.setSelectionRange(selectionRange);
 
-					if (callback) {
-						callback();
-					}
-				});
+				if (callback) {
+					callback();
+				}
```
Comment (distantnative) [inline panel/src/components/Forms/Input/TextareaInput.vue:327]: `Question:` Isn't this losing now the implicit next tick that `setTimeout` would add before?

**Review by distantnative — COMMENTED** [review]
I also experienced what @afbora writes. Not always consistently but multiple times the selection would e.g. not be restored when canceling an upload or other dialog.

I think the issue is that the `selectionRange` gets stored inside the computed property. But the computed property actually does not get refreshed each time the selection changes. So it ends up restoring always the first state when the computed property got generated.

File: panel/src/panel/upload.js (hunk 3 above)
Comment (bastianallgeier) [reply panel/src/panel/upload.js:79]: You can use https://sandbox.test/panel/pages/other+uploads?tab=blocks to test this.

File: panel/src/components/Forms/Input/TextareaInput.vue (hunk 6 above)
Comment (bastianallgeier) [reply panel/src/components/Forms/Input/TextareaInput.vue:327]: The nextTick is now handled in restoreSelection

**Comment by bastianallgeier** [comment]
Your tests and comments made me realize that I had a logical issue in the way the selectionRange was stored but not updated when dialogs are opened. This makes no sense and leads to the issues that you describe. Then I realized that we can use the `onselectionchange` event of the input perfectly to always store the latest selection range and restore that one if it exists. This works really well and cleans up the code some more. 

I've tested everything in Firefox, Chrome and Safari and it seems to run smoothly now, but I would want to wait for another round of tests from your side.

**Comment by afbora** [comment]
@bastianallgeier I tried hundreds of times in different ways, but on one of my first attempts, the file disappeared once. Then I couldn't reproduce the problem again. I think it was cache related. So everything seems to be working fine 🎉

**Comment by bastianallgeier** [comment]
@afbora that's great. I think we should wait for another look from @distantnative before we give it a go. I guess it's ok if we put it into rc.4

**Comment by distantnative** [comment]
Haven't had much chance to test it myself, but no further comments on the code and totally fine for me to have it merged if you two tested it successfully 👍
