### PR TITLE
fix: Add native return types to Responder class

### LINKED ISSUE #8006: `Responder::code()` PHPDoc missing `null` return type
## Description

The `code()` getter in `Kirby\Cms\Responder` can return `null` when no status code has been explicitly
   set, but the PHPDoc only declares `@return int|$this`.
                                                                                                        
  ```php                                                                                              
  // Responder.php
  protected int|null $code = null;

  /**
   * @return int|$this  // ← missing null
   */
  public function code(int|null $code = null)
  {
      if ($code === null) {
          return $this->code; // returns null when unset
      }
      // ...
  }
```

This causes PHPStan to flag `??` and null checks as unnecessary when using `kirby()->response()->code()`, even though `null` is a valid return value at runtime.

**Suggested Fix** Change return type annotation to null|int|$this or use php native return type

```php 
public function code(int|null $code = null): null|int|static
```

### PR DESCRIPTION
**Pull request by afbora**
## Description

Adds native PHP return type hints to the Responder class methods and removes redundant @return tags from the DocBlocks.

### ✨ Enhancements

- Responder::code() PHPDoc missing null return type #8006

## For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: src/Cms/Responder.php [hunk 1]
```diff
@@ -98,8 +96,6 @@ public function body(string|null $body = null): static|string|null
 	 * whether the current response can be cached
 	 * by Kirby's cache
 	 * @since 3.5.5
-	 *
-	 * @return bool|$this
```
Comment (distantnative) [inline src/Cms/Responder.php:102]: We actually do need this as the native PHP types cannot differentiate between `static` and `$this` - but for the docs it's important to know that it doesn't return a new object but the same object.

Comment (afbora) [reply src/Cms/Responder.php:102]: I got this. I wasn't aware of it.

**Review by distantnative — APPROVED** [review]
