### PR TITLE
Fix page tree parents request

### LINKED ISSUE #6683: File link dialog: throw an error when `content.uuid` disable
## Description

> Cannot read properties of undefined (reading 'hasChildren')

Getting above error in dialog when `content.uuid` disabled while linking to file.

## To reproduce

1. Go to panel
2. Edit any page that have writer field
3. Try to link to file

## Your setup
**Kirby Version**  
4.4.0

### LINKED ISSUE #6684: In Panel: Request page error 500
## Description
In Panel, when moving any page, the destination dialog box displays the following error message:
"The request to https://example.ddev.site/panel/site/tree/parents?page=site%3A%2F%2F failed" 
There is also a long delay before all pages are displayed (about hundred pages).
However, the page move is executed.

**Expected behavior**  
Obviously, open the move page dialog without the error. 

**Screenshots**  
SCR-20240918-rfis

## To reproduce
1. Go to the Panel
2. Click on the pop-up menu (3 dots) of the page to be moved and select 'Move page'
3. Wait for all pages to be displayed

Note: With a fresh starterkit install, I cannot reproduce the issue.

## Your setup
**Kirby Version**  
4.4.0

**Console output**  
[browser-console-errors.md](https://github.com/user-attachments/files/17048306/browser-console-errors.md)

**Your system (please complete the following information)**
 - Device: Appe Mac M1
 - OS: macOS 13.6.3 (Ventura)
 - Browser: Brave
 - Version: Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build)

**Additional context**

### PR DESCRIPTION
**Pull request by bastianallgeier**
### Fixes

- https://github.com/getkirby/kirby/issues/6684
- https://github.com/getkirby/kirby/issues/6683

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: config/areas/site/requests.php [hunk 1]
```diff
@@ -70,12 +72,23 @@
 		'action'  => function () {
 			$kirby   = App::instance();
 			$request = $kirby->request();
+			$root    = $request->get('root');
 			$page    = $kirby->page($request->get('page'));
+			$parents = $page?->parents()?->flip()?->values(
```
Comment (distantnative) [inline config/areas/site/requests.php]:
```suggestion
			$parents = $page?->parents()->flip()->values(
```

File: config/areas/site/requests.php [hunk 2]
```diff
@@ -70,12 +72,23 @@
...
+				fn ($parent) => $parent->uuid()?->toString() ?? $parent->id()
+			) ?? [];
+
+			// if root is included, add the site as top-level parent
+			if ($root === 'true') {
+				if (Uuids::enabled()) {
+					$parents = A::prepend($parents, ['site://']);
+				} else {
+					$parents = A::prepend($parents, ['/']);
+				}
```
Comment (distantnative) [inline config/areas/site/requests.php]:
```suggestion
				array_unshift($parents, $kirby->site()->uuid()?->toString() ?? '/');
```
