### PR TITLE
Fixes more possible deprecated warnings when `null` passing for PHP 8.1

### LINKED ISSUE #4047: Calling `url()` helper throws deprecation warning with PHP 8.1
## Description
Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /kirby/config/components.php on line 378

## Your setup
**Kirby Version**  
3.6.1.1

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Fixed more possible deprecated warnings when `null` passing for PHP 8.1.

### Fixes

- Fixed calling `url()` helper throws deprecation warning with PHP 8.1 #4047 

## Breaking changes

None

## Related issues/ideas

- Fixes #4047 

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

File: src/Http/Url.php [hunk 1]
```diff
@@ -77,11 +77,15 @@ public static function currentDir(): string
...
-     * @param string $url
+     * @param string|null $url
      * @return string
      */
     public static function fix(string $url = null): string
     {
+        if (empty($url) === true) {
+            return '';
+        }
+
```
Comment (afbora) [inline src/Http/Url.php]: Possible breaking change?

Comment (bastianallgeier) [reply src/Http/Url.php]: Why do you think so?

Comment (afbora) [reply src/Http/Url.php]: Current

    Url::fix(); // Returns: http://

Now

    Url::fix(); // Returns: ''
    
If the variable is empty, there is nothing to fix.

Comment (bastianallgeier) [reply src/Http/Url.php]: Oh, I see. I think the old version is completely buggy though. Do we see this as a breaking change or as a fix?

Comment (afbora) [reply src/Http/Url.php]: Since this usage does not make sense, we can call it a bug-fix.

Comment (distantnative) [reply src/Http/Url.php]: I wouldn't check for empty, but rather pass `$url ?? ''` to `preg_match`

**Review by bastianallgeier — APPROVED** [review]
