### PR TITLE
Revamped video URL parsing for PHP and JS #2955

### LINKED ISSUE #2955: Video Block Error
If you paste this type of youtube url in the video block it will result in an error.

example url: https://www.youtube.com/watch?list=PL7CcGwsqRpSM3w9BT_21tUU8JN2SnyckR&v=21HuwjmuS7A&index=1

Exception
Invalid YouTube source

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

The parser for video URLs now uses the URI class in PHP and the URL parser in JS. They are actually pretty close, which is very cool. The code is almost identical that way and we can simply adapt it on both ends if needed. Tests have also been ported to JS to test the same URL patterns on both sides. 

## Related issues

- Fixes #2955

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [ ] Added in-code documentation (if needed)

### CODE REVIEW

File: panel/src/helpers/embed.js [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+    const host = "https://" + uri.host + "/embed";
+
+    const isYoutubeId = (id) => {
+      return id.match(/^[a-zA-Z0-9_-]+$/) !== null;
+    };
+
+    let query = uri.searchParams;
+    let src = null;
+
+    switch (path.join("/")) {
```
Comment (lukasbestle) [inline panel/src/helpers/embed.js]: When reading the code, I was confused what happens with the query params in the resulting URL, because I didn't yet know they were appended at the end.

Suggestion: A quick comment above this that explains what happens:

```suggestion

    // build the correct base URL for the embed,
    // the query params are appended below
    let src = null;
    switch (path.join("/")) {
```

File: panel/src/helpers/embed.js [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+    }
+
+    if (!src) {
+      return false;
+    }
+
+    const queryString = query.toString();
+
+    if (queryString.length) {
+      src += "?" + queryString.replace("&", "&amp;");
```
Comment (lukasbestle) [inline panel/src/helpers/embed.js]: For cleanliness I think this helper shouldn't escape the string as the returned URL is not a valid URL anymore. Does anything speak against escaping when the URL is used in the component?

File: src/Toolkit/Html.php [hunk 3]
```diff
@@ -446,128 +447,110 @@ public static function video(string $url, array $options = [], array $attr = [])
...
      * Embeds a YouTube video by URL in an `<iframe>`
      *
      * @param string $url YouTube video URL
      * @param array $options Query params for the embed URL
-     * @param array $attr Additional attributes for the `<iframe>` tag
+     * @param array $attrs Additional attributes for the `<iframe>` tag
      * @return string The generated HTML
      */
-    public static function youtube(string $url, array $options = [], array $attr = []): string
+    public static function youtube(string $url, array $options = [], array $attrs = []): string
```
Comment (lukasbestle) [inline src/Toolkit/Html.php]: Renaming the param would be a breaking-change because of PHP 8's named arguments. Also it's only there for the YouTube method, not for Vimeo. Is the change really necessary?

File: src/Toolkit/Html.php [hunk 4]
```diff
@@ -446,128 +447,110 @@ public static function video(string $url, array $options = [], array $attr = [])
...
+            case 'vimeo.com':
+            case 'www.vimeo.com':
+                $id = $path->first();
+                break;
+            case 'player.vimeo.com':
+                $id = $path->nth(1);
+                break;
+        }
+
+        if (!preg_match('!^[0-9]*$!', $id)) {
```
Comment (lukasbestle) [inline src/Toolkit/Html.php]:
```suggestion
        if (preg_match('!^[0-9]*$!', $id) !== 1) {
```

File: src/Toolkit/Html.php [hunk 5]
```diff
@@ -446,128 +447,110 @@ public static function video(string $url, array $options = [], array $attr = [])
...
+        $uri    = new Uri($url);
+        $path   = $uri->path();
+        $query  = $uri->query();
+        $first  = $path->first();
+        $second = $path->nth(1);
+        $host   = 'https://' . $uri->host() . '/embed';
+        $src    = null;
+
+        $isYoutubeId = function (string $id): bool {
+            return preg_match('!^[a-zA-Z0-9_-]+$!', $id);
```
Comment (lukasbestle) [inline src/Toolkit/Html.php:540]: `preg_match()` does not return a bool, but `1|0|false`. So Psalm will complain about this on higher levels. Fix:

```suggestion
            return preg_match('!^[a-zA-Z0-9_-]+$!', $id) === 1;
```

File: src/Toolkit/Html.php [hunk 6]
```diff
@@ -446,128 +447,110 @@ public static function video(string $url, array $options = [], array $attr = [])
...
+                break;
+
+            // regular video URLs
+            case 'watch':
+                if ($isYoutubeId($query->v) === true) {
+                    $src = $host . '/' . $query->v;
+
+                    $query->start = $query->t;
+
+                    unset($query->v, $query->t);
```
Comment (lukasbestle) [inline src/Toolkit/Html.php]:
```suggestion
                    unset($query->v, $query->t);
```

File: src/Toolkit/Html.php [hunk 7]
```diff
@@ -446,128 +447,110 @@ public static function video(string $url, array $options = [], array $attr = [])
...
-        } else {
-            $query = '';
+        // append all query parameters
+        foreach ($options as $key => $value) {
+            $query->$key = $value;
         }
 
-        $url = 'https://' . $domain . '/' . $uri . $id . $query;
+        // allow fullscreen mode by default
+        $attrs = array_merge(['allowfullscreen' => true], $attrs);
```
Comment (lukasbestle) [inline src/Toolkit/Html.php]: This change (extracting the `array_merge()` into its own line) is not mirrored in the `vimeo()` method. In contrast, the `vimeo()` method already appends the query string. I think the implementation should be mostly consistent for better readability.

**Review by lukasbestle — COMMENTED** [review]
It would be great to also support other video platforms/embed types in the future, see https://kirby.nolt.io/170. I'm torn if we should use this opportunity to already offer this feature. But in the end we can still support it later, there's nothing that really stops us from fixing it first and then improving it again later.

My comments on the YouTube JS method also apply to the Vimeo one that uses identical code.

File: panel/src/helpers/embed.js (hunk 2 above)
Comment (bastianallgeier) [reply panel/src/helpers/embed.js]: The only reason for escaping it here is to keep the results identical with the ones in PHP.

File: src/Toolkit/Html.php (hunk 3 above)
Comment (bastianallgeier) [reply src/Toolkit/Html.php]: Ah, I still have to get used to the PHP 8 stuff. No, it's not necessary. I will revert it.

File: panel/src/helpers/embed.js (hunk 2 above)
Comment (bastianallgeier) [reply panel/src/helpers/embed.js]: I just fixed it. I think we should also stop encoding ampersands in PHP. I'm not sure why we are doing it anyway. But this should be done in a different PR. I don't know how deep that problem will go.

**Comment by bastianallgeier** [comment]
> It would be great to also support other video platforms/embed types in the future, see https://kirby.nolt.io/170. I'm torn if we should use this opportunity to already offer this feature. But in the end we can still support it later, there's nothing that really stops us from fixing it first and then improving it again later.
> 
> My comments on the YouTube JS method also apply to the Vimeo one that uses identical code.

Yes, it would definitely be cool to support other platforms. But that should happen in a different PR and version.

**Comment by afbora** [comment]
> Cannot read property 'match' of null

Related line for youtube:
https://github.com/getkirby/kirby/blob/fix/2955-video-block-error/panel/src/helpers/embed.js#L22

Steps for youtube:
1. Go to panel
2. Enter invalid video url that `https://www.youtube.com/watch?list=zv=21HuwjmuS7A&index=1`
3. See error

Steps for vimeo:
1. Go to panel
2. Enter invalid video url that `https://vimeo.com./115805751`
3. See error

**Comment by afbora** [comment]
Doesn't work for all vimeo links: `groups`, `channels`, `album`

- https://vimeo.com/channels/covid19stories/495450370
- https://vimeo.com/groups/animation/videos/499212458
- https://vimeo.com/album/2222222/video/11111111 (I couldn't find a working video but it is said that there are albums)

**Comment by bastianallgeier** [comment]
@afbora I just fixed the invalid ID check. 

The other Vimeo URLs need to be supported in a different PR.

**Comment by afbora** [comment]
> I just fixed the invalid ID check.

Error still continue.

> The other Vimeo URLs need to be supported in a different PR.

OK 👍

**Comment by bastianallgeier** [comment]
@afbora I forgot the same check for Vimeo. Should be fixed now.

**Comment by afbora** [comment]
> Block error: "Kirby\Toolkit\Html::Kirby\Toolkit\{closure}(): Argument #1 ($id) must be of type string, null given, called in \htdocs\test\kirby\2955\kirby\src\Toolkit\Html.php on line 525" in block type: "video"

When the video link is invalid, the panel works correctly now 👍 but a similar error continues on the frontend.

**Comment by distantnative** [comment]
Since this seems to include breaking changes, I think we should push it to 3.6

**Comment by bastianallgeier** [comment]
@distantnative yep, I'm not getting it ready today anyway. I'm constantly falling through the test coverage checks.

**Comment by afbora** [comment]
I have added the required test for Coverage. If there's nothing missing, I think it's ready 🚀

**Comment by fabianmichael** [comment]
Sorry, I’m pretty late to the party … now that this has basically been resolved for now. I wrote down some thoughts in Nolt about using oEmbed for handling this in the future – could make our lives easier, because we could possibly avoid to write additional code for every new provider. See: https://kirby.nolt.io/170

**Comment by afbora** [comment]
@fabianmichael I think new providers definitely need to be supported.. But at first the issue was related to parsing the video url, then we realized that PHP and JS were not working with the same validation. This PR was to solve these two issues radically. I'm sure the new video providers will be the next step. See @lukasbestle [comment](https://github.com/getkirby/kirby/pull/3074#pullrequestreview-564811527) and after @bastianallgeier [comment](https://github.com/getkirby/kirby/pull/3074#issuecomment-757889675).

**Comment by fabianmichael** [comment]
@afbora it’s not something, that I would personally require at the moment. Just wanted to give a hint to the oEmbed solution, which might be a way of making this easier in the future.

**Comment by afbora** [comment]
@fabianmichael I understood properly now. Yes you right, it will definitely provide much convenience for the future 👍

**Comment by bastianallgeier** [comment]
I've rebased and adjusted it again, after the last updates on the video tag.

**Comment by afbora** [comment]
Will there be any improvements to the `oEmbed` mentioned by Fabian or should we test the PR as it is?

**Comment by bastianallgeier** [comment]
@afbora no, I don't want to add oEmbed to it in this PR. It's a completely different story with two calls for each URL. It's a fantastic solution, but I think we should still move forward with this and add that later.

**Review by distantnative — APPROVED** [review]
LGTM
