### PR TITLE
Fixes border-radius and box-shadow on image in lists

### LINKED ISSUE #3733: [3.6.0-beta.2] Preview images/icons get wrong `border-radius` in lists
**Describe the bug**  
Preview images/icons get wrong `border-radius` in lists.
```css
.k-list-item .k-item-figure {
  border-top-right-radius: var(--rounded-sm);
  border-top-left-radius: var(--rounded-sm);
}
```
Screenshot-30-09-2021_14-19-43@2x

**Expected behavior (I think)**  
```css
.k-list-item .k-item-figure {
  border-bottom-left-radius: var(--rounded-sm);
  border-top-left-radius: var(--rounded-sm);
}
```
Screenshot-30-09-2021_14-19-17@2x

**Kirby Version**  
3.6.0 beta 2

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Fixed border-radius and box-shadow on image in lists

### Fixes regressions from 3.6.0-beta.2
- Fixed border-radius and box-shadow on image in lists `#3733`

## Breaking changes

None

## Related issues/ideas

- Fixes #3733 

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] ~In-code documentation (wherever needed)~
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Layout/Item.vue [hunk 1]
```diff
@@ -221,7 +221,8 @@ export default {
 .k-list-item .k-item-figure {
   width: 38px;
   border-start-start-radius: var(--rounded-sm);
-  border-start-end-radius: var(--rounded-sm);
+  border-end-start-radius: var(--rounded-sm);
+  box-shadow: var(--shadow);
```
Comment (distantnative) [inline panel/src/components/Layout/Item.vue]: The added box shadow makes it look like the image sits above the rest of the list row. I am not sure if I like it or not, but it's a bit of a change.

Comment (afbora) [reply panel/src/components/Layout/Item.vue]: 👍 Then let's continue as before without shadow.

**Review by distantnative — APPROVED** [review]
