### PR TITLE
Switch from `class_uses()` to duck test for `File::setModel()` 

### LINKED ISSUE #4748: `File::setModel()`: Switch from `class_uses()` to duck test
The following lines cause a regression when a model class is extended in a plugin (because `class_uses()` does not check parents):

https://github.com/getkirby/kirby/blob/cfdba1b81fc68d5bdf6561fc47858f6c966100d3/src/Filesystem/File.php#L447-L449

Instead we want to check for the existence of the `root()` and `url()` methods.

See https://github.com/mullema/k3-image-clip/issues/25 for the original discussion.

### PR DESCRIPTION
**Pull request by afbora**
### Fixes
- File class extending works as before #4748

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by afbora** [comment]
@lukasbestle Another potential issue came up where we were checking for `root` and `url`. If a model has `url` and `root` method (like `Page` class), it is accepted. You can check out `Kirby\Filesystem\FileTest::testInvalidModel` unit test. Do you have an idea?

File: src/Filesystem/File.php [hunk 1]
```diff
@@ -441,11 +442,17 @@ public function root(): string|null
...
 	 */
 	protected function setModel(object|null $model = null): static
 	{
-		if ($model !== null && in_array(IsFile::class, class_uses($model)) !== true) {
-			throw new InvalidArgumentException('The model object must use the "Kirby\Filesystem\IsFile" trait');
+		// TODO: create an interface instead of checking methods
+		if (
+			$model !== null &&
+			method_exists($model, 'root') !== true &&
+			method_exists($model, 'url') !== true
```
Comment (lukasbestle) [inline src/Filesystem/File.php]: This should be an or check because both methods must exist:

```suggestion
			(
				method_exists($model, 'root') !== true ||
				method_exists($model, 'url') !== true
			)
```

For cleaner code, we could move the `null` case to the top:

```php
if ($model === null) {
	$this->model = null;
	return $this;
}

if (
	method_exists($model, 'root') !== true ||
	method_exists($model, 'url') !== true
) {
	throw new InvalidArgumentException('The model object must use the "Kirby\Filesystem\IsFile" trait or have "root" and "url" methods');
}

$this->model = $model;
return $this;
```

**Review by lukasbestle — COMMENTED** [review]
It's not ideal, but I feel like it's fine that other models are also accepted. We only need the model object for the root and URL and once those are there, everything will work as expected. It is unlikely that someone will pass a page as the model.

File: src/Filesystem/File.php (hunk 1 above)
Comment (afbora) [reply src/Filesystem/File.php]: Thanks for suggestion 👍

**Review by lukasbestle — DISMISSED** [review]

**Comment by lukasbestle** [comment]
@distantnative Could you take a look at this as well? The solution is not 100% optimal, maybe you have a better idea. Otherwise I think we can still merge it because it fixes the regression.

**Comment by distantnative** [comment]
I think this would be fine.
But had another idea, just want to share: what if the `IsFile` trait would add a class constant that our method would check for? This one would be inherited (whereas the has trait check doesn't work for parents).

**Comment by lukasbestle** [comment]
OMG, that's an awesome hack! It's a hack, but I think it will work really well.

**Comment by distantnative** [comment]
Except that I just read constants in traits are only a PHP 8.2 thing 😆
But I think a method `protected ::hasIsFileTrait(): bool` or so could just serve the same functionality

**Comment by afbora** [comment]
Thank you @distantnative for great idea! I've implemented it. Ready to review 🚀

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Nice one!
