### PR TITLE
Fix `->toUrl()` method for invalid uuids 

### LINKED ISSUE #5367: [v4] `toUrl()` on Link field with Page that got deleted throws error
## Description
Kirby's Url component will throw an error when trying to create the Url for a page that doesn't exist anymore.

**Expected behavior**  
`null` return, no error; similar to when the field would be empty (it's shown empty in the panel as well).

## To reproduce
1. Create a Link Field
2. Set a page in such Link Field
3. Access the URL via `$field->toUrl()`
4. Delete the Page
5. Kirby will throw an error

## Your setup
**Kirby Version**  4.0.0.alpha-4

### PR DESCRIPTION
**Pull request by afbora**
### Fixes
- Fix `->toUrl()` method for invalid uuids #5367

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

File: tests/Cms/Fields/FieldMethodsTest.php [hunk 1]
```diff
@@ -446,6 +446,53 @@ public function testToUrlEmpty()
...
+		$file = $app->file('file://my-file-uuid');
+		$field = $this->field('file://my-file-uuid');
+		$this->assertSame('/media/pages/test/' . $file->mediaHash() . '/test.jpg', $field->toUrl());
+		$this->assertSame($file->url(), $field->toUrl());
+	}
+
+	public function testToInvalidUuidUrl()
+	{
+		$field = $this->field('page://invalid');
+		$this->assertSame('/', $field->toUrl());
```
Comment (lukasbestle) [inline tests/Cms/Fields/FieldMethodsTest.php]: TBH I feel like this is unexpected. I'd expect `null` here.

Comment (afbora) [reply tests/Cms/Fields/FieldMethodsTest.php]: Hmm, the `url` component always returns a string and it is revealed in this component whether the `uuid` is valid or invalid:
https://github.com/getkirby/kirby/blob/v4/fix/5367-toUrl-invalid-uuid/config/components.php#L400-L408

Comment (afbora) [reply tests/Cms/Fields/FieldMethodsTest.php]: Alternative solutions:

1. The easiest way is to return `null` for `url` component. This seems to be a big breaking change.
2. We need to send the path to the `Url::to()` method after checking `uuid`. But this time `Url::to()` will no longer have `uuid` support.

Comment (lukasbestle) [reply tests/Cms/Fields/FieldMethodsTest.php]: You are right, this is a limitation of `Url::to()` and the `url` component.

Thinking about different options, I feel like there is no ideal solution that is both clean and avoids breaking changes.

Returning `null` seems useful, however there would indeed be quite a breaking change in such a central code location.

A few more options I thought about for the "UUID was passed but invalid" case:

3. Throw a `NotFoundException` (more or less backwards-compatible as there was also a PHP error in this case until now)
4. Return the passed UUID string unchanged (keeps the "always a string" return value, but the UUID may not be a useful value in real use)
5. Return `null` from the `url` component but convert that to one of options 1, 3 or 4 in `Url::to()`. Then `Url::to()` could get a new param to control the behavior. But probably needlessly complex.

So far I favor option 3 TBH. It's the least amount of breaking change, but we could still catch the exception in the `toUrl()` field method and return `null` from there if it gets thrown.

What do you think?

Comment (afbora) [reply tests/Cms/Fields/FieldMethodsTest.php]: Option 3 seems ideal. Already throwing an uncontrolled exception. But I have one more idea.

 The `url` component always returns `string`, right?. Except for one case: invalid uuid. If it returns `null` only in the invalid uuid case, we can say that there is almost no breaking change 😇. Anyway, the case that throws an exception now returns `null`. I think it looks like a good bug-fix from the outside 🙂

Comment (lukasbestle) [reply tests/Cms/Fields/FieldMethodsTest.php]: The difference between `NotFoundException` and returning `null` is that the exception is clearly visible and the `null` value can be missed. So I feel like `NotFoundException` would be safer as it's easier to adapt other parts of the code (both by us and by site and plugin devs).

Comment (afbora) [reply tests/Cms/Fields/FieldMethodsTest.php]: Here the changes https://github.com/getkirby/kirby/pull/5368/commits/abc8965a7e6cccb54c862ee60f6d8128fbbee8dc

Comment (afbora) [reply tests/Cms/Fields/FieldMethodsTest.php]: Should we declare breaking change?

Comment (bastianallgeier) [reply tests/Cms/Fields/FieldMethodsTest.php]: @afbora I don't think we need to declare it a breaking change. UUID support didn't exist in 3.9.x yet.

File: config/methods.php [hunk 2]
```diff
@@ -270,7 +270,11 @@
 		 * Turns the field value into an absolute Url
 		 */
 		'toUrl' => function (Field $field): string|null {
-			return $field->isNotEmpty() ? Url::to($field->value) : null;
+			try {
+				return $field->isNotEmpty() ? Url::to($field->value) : null;
+			} catch (Throwable) {
```
Comment (lukasbestle) [inline config/methods.php]: To avoid swallowing other kinds of errors:

```suggestion
			} catch (NotFoundException) {
```

Might need `use` at the top of the file.

File: config/components.php [hunk 3]
```diff
@@ -349,6 +350,7 @@
 	 *
 	 * @param string|null $path URL path
 	 * @param array|string|null $options Array of options for the Uri class
+	 * @throws \Kirby\Exception\NotFoundException
```
Comment (lukasbestle) [inline config/components.php]:
```suggestion
	 * @throws \Kirby\Exception\NotFoundException If an invalid UUID was passed
```

**Review by lukasbestle — APPROVED** [review]
