### PR TITLE
Fix textarea caption using inline markdown

### LINKED ISSUE #4435: [3.7.0] Textarea - Image with caption throws deprecation notice
## Description

Might be associated with #4366 and #4375
When using the image-tag with a caption, i.e. (image: myimage.jpg caption: My awesome caption) the deprecation notice for $inline parameter is triggered.

**Expected behavior**  

Image with caption should appear.

**Screenshots**  

Bildschirmfoto 2022-06-27 um 13 57 34

## To reproduce

1. insert image-tag with caption in textarea field

## Your setup
**Kirby Version**  

3.7.0

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Image KirbyTag with caption doesn't trigger deprecation warning anymore
#4435

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

**Review by afbora — DISMISSED** [review]

File: config/tags.php [hunk 1]
```diff
@@ -144,7 +144,9 @@
 
             // render KirbyText in caption
             if ($tag->caption) {
-                $tag->caption = [$tag->kirby()->kirbytext($tag->caption, [], true)];
+                $options = ['markdown'=> ['inline' => true]];
```
Comment (lukasbestle) [inline config/tags.php]:
```suggestion
                $options = ['markdown' => ['inline' => true]];
```

**Review by lukasbestle — APPROVED** [review]
