### PR TITLE
 Deactivate the replace action if files cannot be replaced #3031

### LINKED ISSUE #3031: Cannot Upload or Replace .json File in Panel ("Invalid file type: code")
**Describe the bug**  
In Kirby 3.5.0, I cannot replace existing .json files in the Panel. I get the following 400 response:
```
{
    "status": "error",
    "message": "Invalid file type: code"
}
```

**To Reproduce**  
1. Have a `files` section
```yaml
        sections:
          files:
            type: files
```
2. Try to upload any `.json` file

**Screenshots**  
Screen Shot 2020-12-23 at 2 08 45 PM

**Kirby Version**  
`3.5.0`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari Version 14.0.2 (16610.3.7.1.9)

**Additional context**  
Works fine in `3.4.5`

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

The accept option in the file blueprint is now checked for the file option menu and the replace button is disabled if a file cannot be re-uploaded/replaced

## Related issues

- Fixes #3031

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

File: src/Cms/File.php [hunk 1]
```diff
@@ -504,6 +505,37 @@ protected function panelImageSource(string $query = null)
...
 
+    /**
+     * Returns an array of all actions
+     * that can be performed in the Panel
+     *
+     * This also checks for the lock status
+     * @since 3.3.0
+     *
+     * and matching accept settings
+     * @since 3.5.1
```
Comment (lukasbestle) [inline src/Cms/File.php]:
```suggestion
     * @since 3.3.0 This also checks for the lock status
     * @since 3.5.1 This also checks for matching accept settings
```

File: src/Cms/File.php [hunk 2]
```diff
@@ -504,6 +505,37 @@ protected function panelImageSource(string $query = null)
...
+    public function panelOptions(array $unlock = []): array
+    {
+        $options = parent::panelOptions($unlock);
+
+        try {
+            /**
+             * check if the file type is allowed
+             * at all. Otherwise it cannot be
+             * replaced.
+             */
```
Comment (lukasbestle) [inline src/Cms/File.php]:
```suggestion
            // check if the file type is allowed at all,
            // otherwise it cannot be replaced
```

**Review by lukasbestle — APPROVED** [review]
@afbora Awesome! 👍

**Review by afbora — APPROVED** [review]

**Comment by bastianallgeier** [comment]
@afbora the unit tests are great! Thank you for the help
