### PR TITLE
Fix disabled cache on empty auth header

### LINKED ISSUE #4634: Pages cache not working (neither stored not used) when checking for logged in user
## Description
Having read @lukasbestle's explanation in #4423, I figured the following would work. [This thread](https://forum.getkirby.com/t/pages-with-protected-content-cannot-be-cached/26387/2) in the forum suggests this should work too so I'm mentioning this as an issue. Starting with a fresh starterkit, I activate the cache in `config.php`:

```php
'cache' => [
    'pages' => [
        'active' => true
    ]
]
```

Pages are stored. Let's say I want to add the ability for my logged in users to have an edit button available on any front-end page which redirects to this very same page in the panel. I clear the cache and I add in my `header.php`:

```php
<?php if(kirby()->user()): ?>
    <a class="edit" href="<?php echo $page->panel()->url() ?>">Edit content</a>
<?php endif; ?>
```

As soon as I do, the cache stops storing pages, the `Cache-Control: no-store, private` header is always set despite me not being logged in. Here's a video of this:

https://user-images.githubusercontent.com/14079751/189099427-fdbd6cd6-ac20-4d42-b355-d5e5d695af95.mp4

## Your setup
Kirby 3.7.5

### PR DESCRIPTION
**Pull request by lukasbestle**
### Fixes

- Caching is no longer disabled when the request passes an empty `Authorization` header. #4634
- Calling `$app->user()` no longer sets the response flag for "uses auth header" unless the `api.basicAuth` option is enabled.

### Breaking changes

None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

File: src/Cms/Auth.php [hunk 1]
```diff
@@ -712,9 +712,13 @@ public function track(string|null $email, bool $triggerHook = true): bool
...
 	{
 		$basicAuth = $this->kirby->option('api.basicAuth', false);
-		$auth      = $this->kirby->request()->auth();
+		$request   = $this->kirby->request();
 
-		if ($basicAuth === true && $auth && $auth->type() === 'basic') {
+		if (
+			$basicAuth === true &&
+			$request->auth() &&
+			$request->auth()->type() === 'basic'
```
Comment (distantnative) [inline src/Cms/Auth.php:724]: Could be shortened to `$request->auth()?->type() === 'basic'`

Comment (lukasbestle) [reply src/Cms/Auth.php:724]: No, because `$request->auth()` can return `false`, which would lead to "call to type() on bool".

Comment (distantnative) [reply src/Cms/Auth.php:724]: 👍

Comment (distantnative) [reply src/Cms/Auth.php:724]: But can I ask what this change is for? It seems to have the same functionality as before, just now spelling out `$request->auth()` twice instead keeping it in a variable

Comment (lukasbestle) [reply src/Cms/Auth.php:724]: See the unit tests. If we call `auth()` beforehand, it will always trigger `$app->response()->usesAuth()`, even if the auth is never actually used.

Comment (distantnative) [reply src/Cms/Auth.php:724]: Maybe we can add a comment for us others to later still understand that basically `$basicAuth === true` is the condition that really needs to be true before we even call `->auth()`. I'm afraid we'll read it in the future and this won\t be so clear to us anymore.

**Review by distantnative — APPROVED** [review]
