### PR TITLE
fix: Disable dialog save shortcut when loading

### LINKED ISSUE #7258: Saving the page causing loop requests while uploading in progress
## To reproduce

1. Go to panel
2. Edit any page
3. Try to upload big file (or use browser throttling)
4. Use CTRL + S to save the page while file uploading still in progress
5. See console that multiple upload request created as pending and all is stucked (never completed for me)

## Your setup
**Kirby Version**  
4.8.0 & 5.0.0-rc2

### PR DESCRIPTION
**Pull request by distantnative**
## Description

Blocks the `panel.dialog.submit()` method when dialog is currently loading (already being submitted).

In the related issue, this prevents the upload dialog to be submitted multiple times by spamming `Cmd+S` (when the user thinks this would save the form content). 

### Fixes
- Dialogs: `Cmd+S` doesn't re-submit the dialog when its already submitting
#7258

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Dialogs/Elements/Buttons.vue [hunk 1]
```diff
@@ -77,7 +73,7 @@ export default {
 			return this.button(this.submitButton, {
 				class: "k-dialog-button-submit",
 				disabled: this.disabled || this.$panel.dialog.isLoading,
-				icon: this.icon,
+				icon: this.$panel.dialog.isLoading ? "loader" : this.icon,
```
Comment (distantnative) [inline panel/src/components/Dialogs/Elements/Buttons.vue:76]: `Explanation:` This changed chunk only moves the logic from the template code into the `submit()` method (where also the other logic is already located).

**Review by bastianallgeier — APPROVED** [review]
