### PR TITLE
fix: respect case preferences when grouping by callable

### LINKED ISSUE #7562: Case preferences are ignored when grouping collections by callable
## Description
I was trying to group my page collection by a custom callable:

```php
$kirby->collection('artists')->group(function (ArtistPage $artist) {
  return match ($artist->category()->value()) {
    'musician' => $artist->instrument()->value(),
    default => $artist->category()->value(),
  };
}, caseInsensitive: false);
```
Unfortunatly the value of the caseInsensitive argument is ignore whenever a callable is provided. As a consequence the name of the categories/instruments are lower case.

**Expected behavior**  
Keep the original case of the key used for each group intact, if `caseInsensitive` is set to `false`.

## To reproduce
1. Create a collection
2. Group the collection by a callable and set `caseInsensitive` to `false`

## Your setup
**Kirby Version**  
5.0.3

### PR DESCRIPTION
**Pull request by dweidner**
### 🐛 Bug fixes
Keep original case intact when grouping a collection by callable. See issue #7562.

### CODE REVIEW

File: src/Toolkit/Collection.php [hunk 1]
```diff
@@ -553,7 +553,7 @@ public function group(
 				}
 			}
 
-			return new self($groups);
+			return new self($groups, !$caseInsensitive);
```
Comment (afbora) [inline src/Toolkit/Collection.php:556]:
```suggestion
			return new self($groups, $caseInsensitive);
```

Comment (afbora) [reply src/Toolkit/Collection.php:556]: It should be without `!` to respect parent `$caseInsensitive`.

Comment (distantnative) [reply src/Toolkit/Collection.php:556]: @afbora no it's correct, the method and class use opposites: caseSensitive vs caseInsensitive

Comment (afbora) [reply src/Toolkit/Collection.php:556]: Oh sorry, I thought both are same variable names 😅

**Comment by afbora** [comment]
@dweidner Can you add a unit test for this improvement, please? I can take care if you're not available.

**Comment by dweidner** [comment]
Sorry, it took me a while to find the time. I will add some tests today. Thank you for considering my pull request.

**Comment by dweidner** [comment]
Sorry for the noise. Was struggeling with the prettier configuration in VSCode. Should be ready now.

**Review by afbora — DISMISSED** [review]
Great 👍 

_Optional note: IMHO It's not a big deal, but in unit tests, counting the results of `->group()` to check how many results the grouping explicitly returns increases the accuracy of the unit test._

**Comment by dweidner** [comment]
> _Optional note: IMHO It's not a big deal, but in unit tests, counting the results of `->group()` to check how many results the grouping explicitly returns increases the accuracy of the unit test._

Was considering this as well, but was not sure whether this should be part of this particular unit test.

**Comment by afbora** [comment]
What I mean is that the group size changes with sensitive and insensitive grouping. You do this with the key control. We can also make the unit test more meaningful by checking the group size. Something like that:

````php
public function testGroupByCallableCaseSensitive(): void
{
	$collection = new Collection();

	$collection->taylor = [
		'name' => 'Taylor',
		'genre' => 'Pop',
	];

	$collection->justin = [
		'name' => 'Justin',
		'genre' => 'Pop',
	];

	$collection->aubrey = [
		'name' => 'Aubrey',
		'genre' => 'Hip-Hop',
	];

	$collection->kayne = [
		'name' => 'kayne',
		'genre' => 'hip-hop',
	];

	$groupsCaseInsensitive = $collection->group(fn (array $item) => $item['genre'], true);

	$this->assertCount(2, $groupsCaseInsensitive);
	$this->assertTrue($groupsCaseInsensitive->has('pop'));
	$this->assertTrue($groupsCaseInsensitive->has('hip-hop'));


	$groupsCaseSensitive = $collection->group(fn (array $item) => $item['genre'], false);

	$this->assertCount(3, $groupsCaseSensitive);
	$this->assertTrue($groupsCaseSensitive->has('Pop'));
	$this->assertTrue($groupsCaseSensitive->has('Hip-Hop'));
}
````

**Comment by dweidner** [comment]
That makes perfect sense. Thank you for clarifying.

**Review by afbora — APPROVED** [review]
