### PR TITLE
Fix multiselect issues

### LINKED ISSUE #2302: [Panel] [Reference] "Multiselect: fix focus on close" commit issue
**Describe the bug**  

https://github.com/getkirby/kirby/commit/0f4f79240b4edaac69379720fe52161d8ba7fec1 This commit that "**Multiselect: fix focus on close**" causing following issues/bugs:

1. #2295
2. #2290
3. #2287
4. #2281 (partially)

Wherever you click, the `close` event is triggered and the multiselect field focuses itself always. 
I tried to solve it, but I didn't succeed.  When we solve this issue, these 4 issues will be solved.

**Kirby Version**  
3.3.0

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

I have corrected all issues in multiselect field 🎉 
I corrected the main issue of self-focusing by doing dropdown `is open` control. 
It works but I opened it as a draft because I'm not sure technically. 
Waiting for your reviews.

## Related issues

- Fixes #2302

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Fixed code style issues with CS fixer and `composer fix`
- [ ] Added in-code documentation (if neeed)

### CODE REVIEW

File: panel/src/components/Forms/Input/MultiselectInput.vue [hunk 1]
```diff
@@ -222,8 +223,13 @@ export default {
       }
     },
     onClose() {
-      this.q = null;
-      this.$parent.$el.focus();
+      if (this.$refs.dropdown.isOpen === false) {
```
Comment (afbora) [inline panel/src/components/Forms/Input/MultiselectInput.vue:226]: To prevent on each close event

File: panel/src/components/Forms/Input/MultiselectInput.vue [hunk 2]
```diff
@@ -222,8 +223,13 @@ export default {
...
+        if (document.activeElement === this.$parent.$el) {
```
Comment (afbora) [inline panel/src/components/Forms/Input/MultiselectInput.vue:227]: To ensure closed element is current element

File: panel/src/components/Forms/Input/MultiselectInput.vue [hunk 3]
```diff
@@ -177,8 +177,9 @@ export default {
       this.close();
     },
     close() {
-      this.$refs.dropdown.close();
-      this.onClose();
+      if (this.$refs.dropdown.isOpen === true) {
+        this.$refs.dropdown.close();
+      }
```
Comment (afbora) [inline panel/src/components/Forms/Input/MultiselectInput.vue:182]: Close the dropdown only dropdown is open

**Review by bastianallgeier — APPROVED** [review]
The changes look really useful to me!
