### PR TITLE
Fix loading template controllers on representations

### LINKED ISSUE #2471: Controller not passing data to content representation if php template is not present
**Describe the bug**  
I use Kirby as a headless CMS and am not interested in using the normal templates, only their content representation version, e.g. json. But the controller doesnt pass data to the content representation version of a template if its normal template is not present as well.

**To Reproduce**  
1. Go to `site/templates` and remove all templates, leave only `site/templates/default.php`
2. Add a json content representation template for some page that exists and uses this template, e.g. `site/templates/album.json.php` (in starterkit)
3. Add a controller for this representation, i.e. `site/controllers/album.json.php` and try to pass some variable to the json template.
4. Doesnt work. But if you create a file for the normal template, i.e. `site/templates/album.php`and even leave it empty, suddenly the variable from the controller gets passed to the json template.

**Expected behavior**  
The controller for the json template passes data to the json template even without having to have a normal (non-json) template present.

**Kirby Version**  
3.3.4

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

The issue had two sources:

1. Since the `representation()` method doesn't update the `template` variable of class, if there is no template file, it always returns the default template.
2. Since the controller call process is related to the template, the order of setting the template and then calling the controller has been adjusted.

Maybe a better development can be done or you may want to refactor. So I open it as a draft.

## Related issues

- Fixes #2471 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

File: src/Cms/Page.php [hunk 1]
```diff
@@ -1172,7 +1172,7 @@ public function representation($type)
         $representation = $kirby->template($template->name(), $type);
 
         if ($representation->exists() === true) {
-            return $representation;
+            return $this->template = $representation;
```
Comment (afbora) [inline src/Cms/Page.php]: @lukasbestle I am not sure if there is a need to undo this change?

**Comment by afbora** [comment]
@lukasbestle Can you make the last touch please? 😇

**Review by lukasbestle — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]
