### PR TITLE
fix: Unclosed nested snippets

### LINKED ISSUE #7567: Layout snippets do not work from within other layout snippets
## Description

When I use a [layout snippet](https://getkirby.com/docs/guide/templates/snippets#passing-slots-to-snippets__layout-snippets) within another layout snipped, the content is discarded without any error reported.

**Expected behavior**  

I would expect to see the content of the included snippet.

**Note**

Since I found a workaround, the issue is not really important to me. However, I was a bit lost initially when I got an empty page without any error. I thought I should let you know anyway.

## To reproduce

1. Create a snippet
2. Create another snippet which uses the previous snipped as a layout snippet
3. Create a template which uses the snipped from step 2 as a layout snippet
4. **Content of the snipped from step 1 is missing**

**Example**

In the following example, I get a HTTP 200 response, but the page is completely empty.

https://github.com/JojOatXGME/plainkit/commit/5798fca5aa919f5160ed57964a22069f852542d0

<details>
<summary>Alternative: patch on top of plainkit (based on commit 3d651f772485fa7ec836238bde103d4368e9fdcb)</summary>

```diff
$ git diff --staged
diff --git a/site/snippets/base.php b/site/snippets/base.php
new file mode 100644
index 0000000..74e38ae
--- /dev/null
+++ b/site/snippets/base.php
@@ -0,0 +1 @@
+<h1><?= $page->title() ?></h1>
diff --git a/site/snippets/subsnippet.php b/site/snippets/subsnippet.php
new file mode 100644
index 0000000..b95c82b
--- /dev/null
+++ b/site/snippets/subsnippet.php
@@ -0,0 +1 @@
+<?php snippet('base', slots: true);
diff --git a/site/templates/default.php b/site/templates/default.php
index 74e38ae..9ca23b8 100644
--- a/site/templates/default.php
+++ b/site/templates/default.php
@@ -1 +1 @@
-<h1><?= $page->title() ?></h1>
+<?php snippet('subsnippet', slots: true);
```

</details>

## Your setup
**Kirby Version**  
4.8.0

**Console output**  

```
> Composer\Config::disableProcessTimeout
> @php -S localhost:8000 kirby/router.php
[Mon Aug 25 01:15:56 2025] PHP 8.4.11 Development Server (http://localhost:8000) started
[Mon Aug 25 01:16:02 2025] [::1]:54971 Accepted
[Mon Aug 25 01:16:02 2025] [::1]:54971 Closing
```

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 142.0

**Workaround**  

Call `endsnippet()` at the end of either the snippet of step 2, or the template of step 3.

### PR DESCRIPTION
**Pull request by distantnative**
## Description

Original PR: https://github.com/getkirby/kirby/pull/7571

- [x] Unit tests

### 🐛 Bug fixes

- Fixed auto-closing open snippets at the end of a nested snippet (thx to @JojOatXGME)
https://github.com/getkirby/kirby/issues/7567

### Breaking changes
- Template data must not include variables named `$slot` or `$slots`

### For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
  - [x] https://github.com/getkirby/sandbox/pull/21
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: tests/Template/TemplateTest.php [hunk 1]
```diff
@@ -102,8 +102,8 @@ public function testRender(): void
 			]
 		]);
 
-		$template = new Template('simple');
-		$this->assertSame('Test', $template->render(['slot' => 'Test']));
+		$template = new Template('template');
+		$this->assertSame('Test', $template->render(['foo' => 'Test']));
```
Comment (distantnative) [inline tests/Template/TemplateTest.php:106]: `Discuss:` As we reuse `Snippet::load()` for `Template::render()`, templates now would also not allow to include `$slot` and `$slots` in the data array passed to the template. This is a breaking change, but maybe more consistent?

File: src/Template/Snippet.php [hunk 2]
```diff
@@ -128,6 +128,57 @@ public static function end(): void
...
+			// no slots have been defined, but the snippet code
+			// should be used as default slot
+			return Snippet::$current->render($data, [
+				'default' => $snippet
+			]);
+		}
+
+		// swallow any "unslotted" content
+		// between start and end
+		return Snippet::$current->render($data);
```
Comment (distantnative) [inline src/Template/Snippet.php:179]: `Help:` I cannot find a unit test to cover this line. I am wondering if there is a logical mistake and this line is never reachable.

Comment (bastianallgeier) [reply src/Template/Snippet.php:179]: I'm not 100% sure, but I think this was about the following case: 

The layout snippet has a head and default slot: 

```php
<head>
<?= $slots->head() ?>
</head>

<body>
<?= $slot ?>
</body>
```

And the snippet is used like this: 

```php
<?php snippet('layout', slots: true) ?>

<?php slot('head') ?>
This goes into the head
<?php endslot() ?>

This content is swallowed. As soon as a named slot is used, the default slot also has to be added explicitely.

<?php endsnippet() ?>
```

File: tests/Template/TemplateTest.php (hunk 1 above)
Comment (bastianallgeier) [reply tests/Template/TemplateTest.php:106]: I'm in general fine with this breaking change. Moving it to v6 does not sound like a bad idea to me anyway. It's quite a bit of a change in the template engine.

File: src/Template/Snippet.php (hunk 2 above)
Comment (bastianallgeier) [reply src/Template/Snippet.php:179]: I added unit tests for it and they run through, but the line is still not marked as covered. If I remove the line from the class, my two new tests fail though. I'm pretty sure this is a Codecov issue.

Comment (distantnative) [reply src/Template/Snippet.php:179]: OK thanks, then let's ignore it. But move this to v6 as discussed in the other comment.

**Review by bastianallgeier — APPROVED** [review]
