### PR TITLE
sortBy in sections: Support sorting constants

### LINKED ISSUE #1913: Special Characters Sorting Issue on Sections
I'm using Turkish language and there are some special characters in our language (Ç,Ğ,İ,Ö,Ş,Ü).
If title or sorting field have these characters, sorting not working properly.

**Blueprint**
```
customSection:
    type: pages
    headline: Custom Section
    sortBy: title asc
```

**Screenshots**
FireShot Capture 704 - PixelShop - http___pixelshop com_panel_site

**Expected sort**

1. Katalog
2. Kategoriler
3. Özellikler
4. Üretici Firmalar
5. Yorumlar

Tried following setting locales but I didn't get the result I expected:

```
return [
    ...
    'locale' => [
        'tr_TR'
    ]
    ...
];

return [
    ...
    'locale' => [
        LC_ALL  => 'tr_TR.utf-8',
    ],
    ...
];
```

**Kirby Version**
3.2.2

**Desktop:**
 - Windows 10
 - Chrome 75.0.3770.100 (64 bit)

### PR DESCRIPTION
**Pull request by lukasbestle**
Makes it possible to use custom sorting flags in the `sortBy` attribute of the pages and files sections:

```yaml
customSection:
    type: pages
    headline: Custom Section
    sortBy: title asc SORT_LOCALE_STRING
```

## Related issues

Fixes #1913.

## Todos

- [x] Add unit tests for fixed bug/feature
- [x] Pass all unit tests
- [x] Fix code style issues with CS fixer and `composer fix`
- [x] If needeed, in-code documentation (DocBlocks etc.)

### CODE REVIEW

File: config/sections/files.php [hunk 1]
```diff
@@ -82,7 +82,16 @@
             $files = $this->parent->files()->template($this->template);
 
             if ($this->sortBy) {
-                $files = $files->sortBy(...Str::split($this->sortBy, ' '));
+                $sortArgs = Str::split($this->sortBy, ' ');
```
Comment (bastianallgeier) [inline config/sections/files.php]: I think it would be great if we could unify this for all sections that use sorting. I'm just not sure yet where. Maybe in a new mixin.

**Review by bastianallgeier — APPROVED** [review]
