### PR TITLE
Fix tabbed link styling

### LINKED ISSUE #3576: [3.6.0] Topbar breadcrumb: no tabbed styling

### PR DESCRIPTION
**Pull request by distantnative**
## Describe the PR

We made a small mistake when moving from SCSS to CSS. See https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/panel/src/main.scss#L168-L174

### Fixed regressions from alpha.2
- Styling for tabbed link highlighting works again

## Related issues/ideas

- Fixes #3576

### CODE REVIEW

File: panel/src/components/Navigation/Link.vue [hunk 1]
```diff
@@ -117,7 +117,7 @@ export default {
 .k-link {
   outline: none;
 }
-.k-link [data-tabbed] {
+.k-link[data-tabbed] {
   outline: none;
```
Comment (lukasbestle) [inline panel/src/components/Navigation/Link.vue]: This line can also be removed as it's duplicated from above:

```suggestion
```

**Review by lukasbestle — APPROVED** [review]
