### PR TITLE
fix: Allow selecting any file blueprint if none is specified

### LINKED ISSUE #6761: File changeTemplate rules: Bug when no template defined
https://forum.getkirby.com/t/files-section-change-template-cant-be-enabled/32701/2?u=distantnative

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Changelog 

🐛 Bug fixes

- Fixed "Change Template" options for files: All available file templates are shown when sections don't define available templates #6761.

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: src/Cms/Blueprint.php [hunk 1]
```diff
@@ -125,7 +125,12 @@ public function acceptedFileTemplates(string|null $inSection = null): array
 			}
 
 			$templates = match ($section->type()) {
-				'files'  => [...$templates, $section->template() ?? 'default'],
+				'files'  => [
+					...$templates,
+					...($section->template()
+						? [$section->template()]
+						: App::instance()->blueprints('files'))
```
Comment (distantnative) [inline src/Cms/Blueprint.php:133]: `Suggestion:` I guess `$section->template()` isn't a very expensive call. But might still make sense to define it above `$templates = ` once and then just do `$template ? [$template ] : ...`

File: src/Cms/File.php [hunk 2]
```diff
@@ -192,7 +192,7 @@ public function blueprints(string|null $inSection = null): array
 			if ($template === 'default') {
 				$blueprints[$template] = [
 					'name'  => 'default',
-					'title' => '– (default)',
+					'title' => 'Default – (default)',
```
Comment (distantnative) [inline src/Cms/File.php]: `Question:` This one I don't quite understand. If you want to add `Default` also as text not just value, wouldn't it be `Default (default)` rather? But do you think that improves it really to repeat it twice?

File: tests/Cms/FilesSectionTemplateChangeTest.php [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+
+	public function testFileCanChangeTemplateWithMultipleBlueprintsAvailable(): void
+	{
+		$this->app->impersonate('admin');
+
+		$page = new Page(['slug' => 'test', 'template' => 'default']);
+		$file = new File(['filename' => 'test.jpg', 'parent' => $page]);
+
+		// Before the fix: this would return false because only 'default' template was available
+		// After the fix: this should return true because multiple templates are available
```
Comment (distantnative) [inline tests/Cms/FilesSectionTemplateChangeTest.php]: This was great for reading the tests during review, but I wouldn't keep it in the code as I think down the road we would have no clue anymore what "fix" this is talking about.

File: src/Cms/File.php (hunk 2 above)
Comment (bastianallgeier) [reply src/Cms/File.php]: You are right. I've reverted it.

**Review by distantnative — APPROVED** [review]
