### PR TITLE
Fixes autofocus fields in structure fields #3083

### LINKED ISSUE #3083: [Panel] Blueprint autofocus property not working as expected
The video shows a structure field containing a date field as first child. When clicking on an existing entry, the date field pops up and can only be closed by confirming the date. Clicking elsewhere on the structure does nothing and clicking outside of the structure closes the parent as well.

Setting `autofocus: false` on either date field or its parent structure field does not seem to have any effect. Autofocus also occurs when using the arrow buttons to navigate between structure entries. 

https://user-images.githubusercontent.com/12812201/104510440-7e535c80-55eb-11eb-8c08-f5e303a570ae.mov

**Simplified Blueprint**  

```
label: Events
type: structure
autofocus: false
fields:
  date:
    extends: fields/date
    required: true
    autofocus: false
```

**Expected behavior**  

I'd expect `autofocus: false` to prevent focus when:
1. Opening a structure field
2. Navigating between structure field entries

Additionally I'd expect the date field to close when clicking anywhere but the date field (just like a HTML select box), but this should probably be a separate issue report...

**Workarounds**  

The only workaround I found was to add a honeypot `line` field to intercept the focus (a `hidden` field doesn't work, unfortunately).

**Kirby Version** 

3.5

**Desktop** 

Mac OS 10.14.6, Firefox 84.0.2

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

We have already solved the autofocus issue, but there was also a issue with the pagination part. This issue was also resolved by improving the codes. The autofocus field was cached while loading the fields.

## Related issues

- Fixes #3083 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

### CODE REVIEW

File: panel/src/components/Forms/Field/StructureField.vue [hunk 1]
```diff
@@ -233,6 +234,10 @@ export default {
           model: this.endpoints.model
         };
 
+        if (this.autofocus === null && field.autofocus === true) {
+          this.autofocus = name;
+        }
```
Comment (afbora) [inline panel/src/components/Forms/Field/StructureField.vue:239]: If there is more than one autofocus fields, should the first or last one be applied?

Comment (bastianallgeier) [reply panel/src/components/Forms/Field/StructureField.vue:239]: It should normally be the first autofocus field.

Comment (afbora) [reply panel/src/components/Forms/Field/StructureField.vue:239]: Okay, this code is already working on getting the first autofocus 👍

**Review by bastianallgeier — APPROVED** [review]
