### PR TITLE
Fix blocks and layout field default values

### LINKED ISSUE #5111: Using default values in a block that's in a structure bugs the block system
## Description
If you add default values to a blocks field that it is in a structure then the blocks start showing some weird behaviour. (until full page refresh)
If you don't add the default values it works as expected.

**Expected behavior**  

Blocks to behave like they always do 😊

**Screenrecording**  

https://x.gnx.li/Hxz46NyQ

## To reproduce
1. Create a structure field
2. Create a block field in the structure
3. Give the block field default values
4. Use it and see it fail 😅

```yaml
title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          test:
            type: structure
            fields:
              text:
                type: blocks
                default:
                  - type: heading
                    content:
                      level: h2
                      text: This is a test
                  - type: text
                    content:
                      text: This is a test
```

## Your setup
**Kirby Version**  
Latest plainkit install (3.9.2)

**Your system (please complete the following information)**
 - Device: Mac Studio
 - OS: Ventura 13.2.1
 - Browser: Chrome
 - Version: Latest (111.0.55, arm64)

### PR DESCRIPTION
**Pull request by afbora**
## This PR …
The source of the issue was that there was a conflict in the block and layout field default value because did not have a unique ID. I solved the issue by assigning new ID while setting the default value.

### Fixes
- Fix blocks and layout field ids for default values #5111

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

File: src/Form/Field/LayoutField.php [hunk 1]
```diff
@@ -115,6 +115,33 @@ public function routes(): array
...
+						$block['id'] ??= Str::uuid();
+						return $block;
+					}, $column['blocks'] ?? []);
+
+					return $column;
+				}, $layout['columns'] ?? []);
+
+				return $layout;
+			}, $default);
+		}
```
Comment (afbora) [inline src/Form/Field/LayoutField.php]: If anyone knows a shorter way, please tell me 😅

File: src/Form/Field/BlocksField.php [hunk 2]
```diff
@@ -202,6 +202,19 @@ public function store($value)
...
 	}
 
+	protected function setDefault($default = null)
+	{
+		// set id for blocks if not exists
+		if (is_array($default) === true) {
+			$default = array_map(function ($block) {
+				$block['id'] ??= Str::uuid();
+				return $block;
+			}, $default);
```
Comment (lukasbestle) [inline src/Form/Field/BlocksField.php]:
```suggestion
			array_walk($default, function (&$block) {
				$block['id'] ??= Str::uuid();
			});
```

File: src/Form/Field/LayoutField.php [hunk 3]
```diff
@@ -115,6 +115,33 @@ public function routes(): array
...
+					$column['blocks'] = array_map(function ($block) {
+						$block['id'] ??= Str::uuid();
+						return $block;
+					}, $column['blocks'] ?? []);
+
+					return $column;
+				}, $layout['columns'] ?? []);
+
+				return $layout;
+			}, $default);
```
Comment (lukasbestle) [inline src/Form/Field/LayoutField.php]: At least barely shorter: 😅

```suggestion
			array_walk($default, function (&$layout) {
				$layout['id'] ??= Str::uuid();

				// set columns id within layout
				if (isset($layout['columns']) === true) {
					array_walk($layout['columns'], function (&$column) {
						$column['id'] ??= Str::uuid();

						// set blocks id within column
						if (isset($layout['blocks']) === true) {
							array_walk($column['blocks'], function (&$block) {
								$block['id'] ??= Str::uuid();
							});
						}
					});
				}
			});
```

Comment (afbora) [reply src/Form/Field/LayoutField.php]: Thanks! There was a small variable typo in the last if condition. I pushed it manually 👍

**Review by lukasbestle — COMMENTED** [review]
The code looks good to me. But I don't know the inner workings of the fields enough to review the change overall.

**Review by bastianallgeier — APPROVED** [review]
LGTM!
