### PR TITLE
Fix `File::previewUrl` on custom `file::url` component 

### LINKED ISSUE #4143: file::url component doesn't work as expected in 3.6.x on File Panel Pages
## Description

The [file::url component](https://getkirby.com/docs/reference/plugins/components/file-urls) doesn't return the correct url to the panel in 3.6.x, downgrading to 3.5.x solves the issue. 

**Expected behavior**  
The open button and image preview links on the panel should use the returned url set on the plugin / component and not the default. See the URLS below on the screenshots bottom left.

**Kirby 3.6.2 Screenshot** 

**Kirby 3.5.8 Screenshot**

## To reproduce

1. Create a custom file::url component plugin
2. Navigate to a file page on the panel
3. Click the open or image preview.
4. See URL returns as default rather than a modified one via the component

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

WIP and POC of @distantnative comment: https://github.com/getkirby/kirby/issues/4143#issuecomment-1075001280 @lukasbestle not agreed about solution but I just created the PR to force fixing the issue soon. Feel free to close any time.

### Fixes
 - `file::url` component doesn't work as expected in 3.6.x on File Panel Pages #4143

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

**Comment by distantnative** [comment]
@lukasbestle I understand that this would not be a 100% solution for custom file url components with CDNs - as then the Panel preview URLs aren't the original ones but the CDN ones again. But maybe still a better fix than status quo?

**Comment by lukasbestle** [comment]
@distantnative Probably, yes. To be honest I find it hard to consider all use cases. May well be that we would have another regression, but maybe we wouldn't. We can certainly try it and 3.7.0 will be the best release to do that.

File: src/Cms/AppPlugins.php [hunk 1]
```diff
@@ -790,6 +790,17 @@ protected function extensionsFromSystem()
         $this->extendTemplates($this->core->templates());
     }
 
+    /**
+     * Checks native component extended
+     *
```
Comment (distantnative) [inline src/Cms/AppPlugins.php:796]: Should add `@since` tag.

Comment (lukasbestle) [reply src/Cms/AppPlugins.php:796]: Text suggestion for the docblock:

```txt
Checks if a core component is the unchanged native component
```

**Comment by bastianallgeier** [comment]
I really like this fix because it is so simple. I would go for it.

**Review by bastianallgeier — APPROVED** [review]
