### PR TITLE
fix: Normalize field names in field classes

### LINKED ISSUE #7236: [v5] Struture Field Blueprint Preview is empty without defining columns
## Description
after updating 5.0.0-beta.5 => 5.0.0-rc.1 all structure fields in the panel are only displayed with a number and an empty column:

`  footerOpeningTimes:
    type: structure
    label: Opening Times
    width: 1/2
    fields:
      otDay:
        label: Tag(e)
        type: text
      otTimes:
        label: Zeiten
        type: text`

Image

after adding the columns manually, they are displayed how i defined them:

`  footerOpeningTimes:
    type: structure
    label: Opening Times
    width: 1/2
    columns:
      otDay: true
      otTimes: true
    fields:
      otDay:
        label: Tag(e)
        type: text
      otTimes:
        label: Zeiten
        type: text`

Image

**Expected behavior**  
strucure fields should show all columns if nothing is specified

## Your setup
 5.0.0-rc.1

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Sandbox 

There's a new test setup for this in the sandbox. Pull the latest changes, switch to the lab environment and go to: https://sandbox.test/panel/pages/fields+structure You will find a new "Field name cases" example at the bottom. 

### Fixes

- `Kirby\Form\Field` and `Kirby\Form\FieldClass` normalize type and name attributes and set the name to lowercase. We did that previously in the Form class and it slipped through with the refactoring. Without turning all names into lowercase, fields might not be matched properly and this is also causing an issue with columns in structure fields. https://github.com/getkirby/kirby/issues/7236

### Breaking changes

None

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add lab example
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: src/Form/Field.php [hunk 1]
```diff
@@ -57,22 +57,25 @@ public function __construct(
...
+		// set the name to lowercase
+		$attrs['name'] = strtolower($attrs['name']);
+
 		if (isset(static::$types[$type]) === false) {
 			throw new InvalidArgumentException(
 				key: 'field.type.missing',
 				data: [
-					'name' => $attrs['name'] ?? '-',
-					'type' => $type
+					'name' => $attrs['name'],
```
Comment (distantnative) [inline src/Form/Field.php]: `Nitpick:` This will produce a (maybe) misleading error message when the name here might already be filled in with the type, but the error message presents it as its actual name.

Comment (bastianallgeier) [reply src/Form/Field.php]: I've reverted it

**Review by distantnative — APPROVED** [review]
