### PR TITLE
More efficient lock check

### LINKED ISSUE #4740: Query in tag field polled every 10s while page is open in panel
## Description
Tag fields (potentially other field types as well; untested) with queries execute that query every 10 seconds while the page in question is open in the panel. With slightly more complex queries (e.g. when using `->index()`) this can lead to a measurable increase in server load.

**Expected behavior**  
The query should not be executed repeatedly.

## To reproduce
1. Install a fresh Starterkit (3.7 is fine, as this is not a new issue)
2. Add this little plugin

```php
// site/plugins/my-plugin/index.php
<?php
Kirby::plugin('my/plugin', [
  'pageMethods' => [
    'alltags' => function () {
      F::write(kirby()->root('logs')  . '/alltags.log', date('H:i:s'). "\r\n", true);
      return ['tag1', 'tag2', 'tag3'];
    }
  ]
]);
```

3. Change the `tag` field in the `note` blueprint as follows:

```yaml
# site/blueprints/pages/note.yml
tags:
  options: query
  query: page.alltags

```

4. Open an existing note page in the panel
5. Wait a minute and open file `site/logs/alltags.log`
6. See how the field query got executed every 10 seconds:
```
07:54:08
07:54:18
07:54:28
07:54:38
07:54:48
07:54:58
```

## Your setup
Fresh Starterkit 3.7.5 (also present after updating to 3.8.0-rc.1)
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 104.0.2

### PR DESCRIPTION
**Pull request by bastianallgeier**
## This PR …

When we switched to Fiber, we removed the GET route for locks and instead reloaded the view every 10 seconds and passed an only rule, to only return `$view.props.lock`. The only problem: To build the `$view` array, the backend would process a lot more than necessary. Even with the only rule, tabs, content, permissions and more would be reevaluated on every call every 10 seconds. This is not noticable if the view is fast, but when there are complex queries involved it can get really messy and the UUIDs don't make this problem better. 

That's why I brought back the GET request for the lock status and instead of using the Fiber call, the checks are now done through the API again. I've unified the code, which is used in the Fiber view and in the lock check. They now return identical objects or false if locking is disabled. This means that we can still get the first state from Fiber and every next update is done through the API. Ideally, we would have additional Fiber routes that could do the same thing without relying on the API at some point. But this seems like a rather simple fix for a pretty big issue. 

@distantnative I think you really should have a look at this. You are most familiar with locking. I hope I didn't miss anything.

### Fixes

- #4740

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

File: src/Panel/Model.php [hunk 1]
```diff
@@ -235,18 +235,7 @@ public function isDisabledDropdownOption(string $action, array $options, array $
...
-					'state' => 'lock',
-					'data'  => $lock->get()
-				];
-			}
-
-			return ['state' => null];
+			return $lock->toArray();
 		}
 
 		return false;
```
Comment (distantnative) [inline src/Panel/Model.php:241]: We could simplify this then even further

```php
return $this->model->lock()?->toArray() ?? false;
```

**Comment by distantnative** [comment]
This would be a way and looks fine so far (would like to do some actual testing still though).
But I wonder whether the same thing (Fiber not respecting the `only`-nature of a reload request) would bite us in other parts too and we should rather fix that? 

To my understanding we would need to wrap a lot more into Closures in `Panel\Model::props()` etc.

**Comment by bastianallgeier** [comment]
The general problem is indeed that we are not clean enough with the way we send data to the views. Other "only" requests would indeed have the same problem. But when I looked at it, it seems like the far more risky fix so shortly before the release.

**Comment by distantnative** [comment]
Keep seeing the Fiber requests still
Screenshot 2022-10-03 at 12 56 55

**Comment by bastianallgeier** [comment]
Did you run npm run dev to test? Haven't updated the dist files.

**Comment by distantnative** [comment]
Yes, always just running on `npm run dev`. But trying to narrow it down, this seems weird.

**Comment by distantnative** [comment]
Ok somehow vite didn't pick up the changes in dev mode. Now working.

**Comment by bastianallgeier** [comment]
Now Codecov discovered that there are lock routes for the first time and we have to write tests for them 🙈

**Comment by distantnative** [comment]
Codecov knew already about them, but our setup is that we are not allowed to leave any touched line uncovered even if it was not covered before. Very strict @lukasbestle

**Comment by lukasbestle** [comment]
Codecov is only complaining about the single line in the new `GET` route. The others were already uncovered, but because they were not changed, there is no additional risk from this PR. As we discussed before, we can replace the tests in such cases with manual tests and extra carefulness if automated tests are difficult or not viable with the current code base.

**Comment by bastianallgeier** [comment]
I've created a simple integration test for the get route.

**Review by distantnative — APPROVED** [review]
