### PR TITLE
fix: Prevent duplicate draft when changing status in `page.create:after` hook

### LINKED ISSUE #7957: Duplicate draft created when using page.create:after hook (Kirby 5.3.x)
I am using the following hook in my `config.php` to automatically set newly created pages (for specific templates) to `listed`:

```PHP
use Kirby\Cms\Page;

return [
  'hooks' => [
    'page.create:after' => function (Page $page) {

      $allowed = [
        'news-item',
        'stats-item',
        'shop-item',
      ];

      $template = $page->intendedTemplate()->name();

      if (in_array($template, $allowed, true) === false) {
        return;
      }

      if ($page->isDraft() === false) {
        return;
      }

      $page->changeStatus('listed');
    }
  ]
];
```

The issue also occurs with this simplified version:

```PHP
'hooks' => [
    'page.create:after' => function ($page) {
        $page->changeStatus('listed');
    }
]
```

Since updating to **Kirby 5.3.0** (also reproducible in **5.3.1**), the following issue occurs:
1. When creating a new page in the Panel, the page is correctly set to listed.
2. At the same time, **an additional draft with the same slug is created**.
3. This extra draft contains only a `.txt` file with a `uuid` field — no other content.
4. The draft and the listed page have **different UUIDs**.

If I attempt to delete the draft in the Panel:
- The listed (original) page gets deleted instead.
- The draft remains.
- The remaining draft cannot be deleted anymore.

This behavior did not occur before version 5.3.0.

It appears that changing the status inside the `page.create:after` hook may interfere with draft handling or UUID generation in Kirby 5.3.x.

https://github.com/user-attachments/assets/90d07fd9-ebd3-444d-810a-6dc75491eb98

### PR DESCRIPTION
**Pull request by afbora**
## Description

When `changeStatus()` is called inside a `page.create:after` hook, the draft directory gets moved to the published location. However, the `$page` object returned from `commit('create')` still points to the old draft path. The subsequent `$page->uuid()->populate()` call then fails to read the content (file no longer exists), generates a new UUID, and writes it to disk — recreating the draft directory with only a UUID field.

This adds an `$page->exists()` check before calling `populate()` to skip UUID cache population when the page no longer exists at its expected location.

### 🐛 Bug fixes

- Duplicate draft created when using page.create:after hook (Kirby 5.3.x) #7957

## For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [ ] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: src/Cms/PageActions.php [hunk 1]
```diff
@@ -491,7 +491,12 @@ function ($page) use ($storage) {
 			$page = $page->changeStatus('listed', $props['num']);
 		}
 
-		$page->uuid()?->populate();
+		// only populate UUID cache if the page still exists at its
+		// expected location; a hook may have changed the status and
+		// moved the draft directory, making the page object stale
+		if ($page->exists() === true) {
+			$page->uuid()?->populate();
+		}
```
Comment (distantnative) [inline src/Cms/PageActions.php]: Honestly, I don't think at the moment that this is quite right. Cause the page UUID should be populated to the UUID cache anyways. The problem here is rather that `$page` doesn't seem to reference the actual page object anymore but an outdated version. We should look into whether we can retrieve it from the hook, even if none got returned actively, but I also think we might have to require returning the page object when it gets modified inside the hook.

Comment (afbora) [reply src/Cms/PageActions.php]: You're right. So not ideal but the easiest another way then is to get the current object from the parent model before populating it. Getting it from a hook might require significant refactoring.

A forced return change within a hook will create a breaking change. This seems like the most logical solution.

```php
$page = $page->parentModel()->findPageOrDraft($page->id()) ?? $page;
$page->uuid()?->populate();
````

Comment (bastianallgeier) [reply src/Cms/PageActions.php]: @afbora your suggestion seems good. I'm always a bit worried with the state of our cached collections, but as long as our code that updates collections after hooks works as expected, it should be the most solid solution. Let's give it a try and see what our unit tests have to say.

Comment (afbora) [reply src/Cms/PageActions.php]: @bastianallgeier I've applied the changes with tests via https://github.com/getkirby/kirby/pull/7958/changes/5f83a31457868ab67aee3a1756b36c9912cb5264

Comment (bastianallgeier) [reply src/Cms/PageActions.php]: That's great. Thanks. @distantnative do you want to take a last look at it?

Comment (distantnative) [reply src/Cms/PageActions.php]: I am quite torn, it seems to work but also seems to be a bit of a hot patch considering that the lines above do continue to use the actual object returned from the hook. So IMO it would be better to really solve this with the hooks or use the same new behavior for all actions following after a hook - and not just in this action method. But this might be hard, so maybe the current commit is ok, just feels not very clean (but also don't want to get this stuck).

Comment (afbora) [reply src/Cms/PageActions.php]: @distantnative is right about this. We can implement this as a temporary solution for now, deprecating it in v6 and completely removing it in v7, making it mandatory to return it (self `$page` object) within the hook.

Comment (distantnative) [reply src/Cms/PageActions.php]: But this temporary solution, would we not need to use it also for the other lines above in `Page:.create()` and for other page/file/user action methods?

Comment (distantnative) [reply src/Cms/PageActions.php]: Could we not in the Events logic check after the last hook if the model passed got changed (and now should have the immutable storage, no?), without any new object returned from the hook, and if so throw an error?

Comment (afbora) [reply src/Cms/PageActions.php]: > But this temporary solution, would we not need to use it also for the other lines above in Page:.create() and for other page/file/user action methods?

@distantnative The fix should move before the `->changeStatus()` call that call also runs on the stale `$page`. 

Other action methods don't need it because they just return `$this->commit(...)` and stop, so there's nothing running on a stale object after the commit.

Comment (afbora) [reply src/Cms/PageActions.php]: @distantnative @bastianallgeier I've found great solution (I guess :))

What do you think about moving `->populate()` call into `->commit()` like in `File::create()`. Seems like working but not sure since not tested well. Now we not need to another check like `->findPageOrDraft()`

````diff
$page = $page->commit(
	'create',
	[
		'page'  => $page,
		'input' => $props
	],
	function ($page) use ($storage) {
		// move to final storage
-		return $page->changeStorage($storage);
+		$page->changeStorage($storage);
+		$page->uuid()?->populate();
+		return $page;
	}
);
````

Comment (bastianallgeier) [reply src/Cms/PageActions.php]: This makes a lot of sense. I wonder why we put it in two different places in the first place. Could you give it a try and see if our tests still all pass?

Comment (afbora) [reply src/Cms/PageActions.php]: Maybe @distantnative @lukasbestle have an idea about that.
Yes, all `/Cms/Page` namespace tests passed with suggested changes.

Comment (distantnative) [reply src/Cms/PageActions.php]: @bastianallgeier doesn't it then happen before the after hook? I think most of those clean up measures in all our model actions happen outside the commit closure cause they should only be applied after the after hook.

Comment (lukasbestle) [reply src/Cms/PageActions.php]: We already have `Event::updateArgument()` that handles hook closures that modify a model but don't return it. So far we only use it for `Events::apply()`, but is there a reason why we can't also use it for `Events::trigger()`? If I understand it correctly, this should solve this and other related issues. Because I agree with Nico that it would be cleaner to have a general solution.

Comment (bastianallgeier) [reply src/Cms/PageActions.php]: @distantnative I'm also really not happy with any of this. To move it into the commit logic just makes sure that it happened with the correct object first. If you then mess with that and you don't return it in the after hook, we at least don't make any assumptions that we are still dealing with the correct object afterwards. But it's not 100% clean either. 

@lukasbestle I just checked again and we already use ::apply instead of ::trigger in our ModelCommit class to run hooks. Changing the trigger method could still make sense, but it should not fix the problem here as far as I can see.

Comment (lukasbestle) [reply src/Cms/PageActions.php]: Hm, interesting. But then I don’t understand why returning the new object from the hook manually fixes the issue. Shouldn’t our `updateArgument` logic replace exactly that if the return value is omitted?

Comment (bastianallgeier) [reply src/Cms/PageActions.php]: It's just a guess. We only have access to the object that we put into the hook as argument. But when the hook itself calls a method that will then call more hooks, the reference to that object will probably get lost in the nested call and we can't properly run our checks and updateArgument logic anymore.

**Review by bastianallgeier — APPROVED** [review]
