### PR TITLE
fix: Keep default values in disabled structure fields

### LINKED ISSUE #7233: [v5] Saving in the panel removes entries from structure field if field has disabled: true
## To reproduce
Install a fresh plainkit and change site.yml blueprint to

```
title: Site

sections:
  notes:
    type: fields
    fields:
      note:
        type: structure
        label: Notizen
        prepend: true
        batch: true
        empty: Noch keine Notizen angelegt.
        fields:
          user:
            type: users
            default: true
            disabled: true
          created:
            type: date
            default: now
            time: true
            disabled: true
          note:
            type: text
            label: Notiz
```

1. Go to panel
2. Click on + icon to add an entry
3. See user and date/time is set and the field is not editable
4. Write a note and press enter.
5. You see all the content in the table
6. Save the site
7. See how user, date/time disappears in all columns, data is gone from content file!

**Expected behavior**  
Should just save the values for the fields, not erase them.

**What I think**
When I comment this property: #disabled: true – it does save and not delete the fields content. Why?

## Your setup
**Kirby Version**  
5.0.0-rc.1

**Console output**  
no output / no errors

### PR DESCRIPTION
**Pull request by bastianallgeier**
### Fixes

- When a structure field has disabled fields with a default value, the default value is now properly submitted and saved again. https://github.com/getkirby/kirby/issues/7233

### Breaking changes

None

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add lab and/or sandbox examples (wherever helpful)
- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: config/fields/structure.php [hunk 1]
```diff
@@ -181,11 +181,22 @@
...
+		foreach ($value as $index => $row) {
+			$row = $form
+				->reset()
+				->fill(
+					input: $defaults,
+					passthrough: true
+				)
+				->submit(
+					input: $row,
+					passthrough: true
```
Comment (lukasbestle) [inline config/fields/structure.php:197]: Question somewhat unrelated to this PR: Why do we use `passthrough` for the `submit()` call here? Doesn't it allow to pass unfiltered and unsanitized data for extra fields from the frontend?

**Review by lukasbestle — APPROVED** [review]
As I'm not yet fully comfortable working with the new form classes, I think an additional review by @distantnative would be good.

The code and especially the test looks correct to me though.

**Review by distantnative — APPROVED** [review]
