### PR TITLE
PageCreateDialog: use field defaults

### LINKED ISSUE #6119: Publishing a page using `create.status` option doesn't work if page has required fields & defaults for them
## Description
I have a page with fields a & b. In the blueprint, I define

```yaml
create:
  status: listed
```

to publish the page directly after creating it.
Field a is a required field and therefore creation of the page fails, because it's not filled.

I want to mitigate this issue by adding a default for field a.
Because Kirby (afaik) handles default data from blueprints in the panel as well, it won't be respected by Page::create() and it still doesn't work. There is no issue when setting the status from the panel, as Kirby saves the default data from the blueprint correctly.

## Your setup
**Kirby Version**  4.0.2

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Page create dialog: custom fields in dialogs are prefilled with default values
- Page create dialog: no error is thrown when directly publishing page with required fields that have a default value 
#6119

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

File: src/Panel/PageCreateDialog.php [hunk 1]
```diff
@@ -301,13 +305,20 @@ public function validate(array $input, string $status = 'draft'): bool
...
 			'section'  => $this->sectionId,
 			'slug'     => $this->slug ?? '',
 			'template' => $this->template,
 			'title'    => $this->title ?? '',
 			'view'     => $this->viewId,
 		];
+
+		// add default values for custom fields
+		foreach ($this->customFields() as $name => $field) {
+			$value[$name] = $field['default'] ?? null;
```
Comment (bastianallgeier) [inline src/Panel/PageCreateDialog.php]: I think this is risky because some fields don't really like null as value. I would probably create an if clause and only add it to the array if it exists. 

```suggestion
if (isset($field['default']) === true) {
  $value[$name] = $field['default'];
}
```

Comment (distantnative) [reply src/Panel/PageCreateDialog.php]: Good idea

Comment (distantnative) [reply src/Panel/PageCreateDialog.php]: Added the change

**Review by bastianallgeier — APPROVED** [review]
Works great! I've added examples for all page creation options to the sandbox, so we can better test them in the future.
