### PR TITLE
Page create dialog: fix custom fields

### LINKED ISSUE #5231: [v4] Tags field with query error in page create dialogue
## Description
Adding a tags field in the new page create dialogue throws an error `this.options.filter is not a function` when I start typing a tag. This seems to happen when the tags field on the page uses dynamic options with query of tags from sibling pages. If I remove the query options it works fine.

**Screenshots**  

## To reproduce

1. Get the [starterkit](https://github.com/getkirby/starterkit/releases/tag/3.9.4)
2. In `album.yml` add a page create option with a `tags` field
3. In `album.yml` add query options to the `tags` field with `page.siblings.pluck("tags", ",", true)` 
4. In the panel go to the photography page and click + to add a new subpage
5. Start writing a tag in the page create dialogue, see error

## Your setup
**Kirby Version**  
4.0.0-alpha.2 

**Console output**  
```
TypeError: this.options.filter is not a function
    search http://localhost/starterkit/media/panel/9a459044c0e9d589a8dfb36aa8947cc2/js/index.js:1
    onType http://localhost/starterkit/media/panel/9a459044c0e9d589a8dfb36aa8947cc2/js/index.js:1
    input http://localhost/starterkit/media/panel/9a459044c0e9d589a8dfb36aa8947cc2/js/index.js:1
    VueJS 3
```

**Your system (please complete the following information)**
 - PC with XAMPP local development 
 - OS: Windows 10
 - Browser: Firefox
 - Version: 113.0.2

### LINKED ISSUE #5235: [v4] Unit tests for `PageCreateDialog`

### PR DESCRIPTION
**Pull request by distantnative**
## This PR …

Page create dialog needs to resolve custom fields via `Form` class to get all props, options etc. properly resolved.

### Fixes
- #5231
- https://github.com/getkirby/kirby/issues/5235

### Enhancements
- Page create dialog throws proper exceptions if a field type is not supported
- Add custom field types to the list of allowed fields for the page create dialog via `\Kirby\Panel\PageCreateDialog::$fieldTypes[] = 'yourFieldType'`

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier 

```
Kirby\Cms\Page::setParent(): Argument #1 ($parent) must be of type ?Kirby\Cms\Page, Kirby\Cms\Site given, called in /kirby/sandbox/kirby/src/Toolkit/Properties.php on line 137
```

How do we set the Site as a page parent?

File: src/Panel/PageCreateDialog.php [hunk 1]
```diff
@@ -194,6 +190,21 @@ public function load(): array
...
+	 * be created, used to properly render
+	 * the blueprint for fields
+	 */
+	public function model(): Page
+	{
+		return $this->model ??= Page::factory([
+			'slug'     => 'new',
+			'template' => $this->template,
+			'model'    => $this->template,
+			'parent'   => $this->parent
```
Comment (distantnative) [inline src/Panel/PageCreateDialog.php]: @bastianallgeier I guess this needs to be

```suggestion
			'parent'   => $this->parent instanceof Page ? $this->parent : null
```

Since `Page::parentModel()` will automatically fall back to Site if no parent is set.

**Comment by afbora** [comment]
Dialogs in `textarea` and `writer` field doesn't work for this PR.

**Review by bastianallgeier — APPROVED** [review]
This is great!
