### PR TITLE
Fix structure field actions 

### LINKED ISSUE #4393: [3.7.0-rc.1] structure field with max value looks off
## description
dont know if you’re aware of this already. but since updating to `3.7.0-rc.1`, my structure fields look kinda strange. the last column either needs more space or the "remove" text needs to be removed (lol). this only happens when having a `max` value set.

**Screenshots**  
structure

## to reproduce
```yml
structure:
    label: Structure
    type: structure
    max: 3
    fields:
        title:
            label: Title
            type: text
        images:
            label: Carousel Images
            type: files
            query: page.images
```

then add 3 entries to the structure field.

---

hope it helps!
🙏🏻 ✨

### PR DESCRIPTION
**Pull request by afbora**
### Fixes

- #4393

### CODE REVIEW

File: panel/src/components/Navigation/OptionsDropdown.vue [hunk 1]
```diff
@@ -2,7 +2,6 @@
   <!-- Single option = button -->
   <k-button
     v-if="hasSingleOption"
-    v-bind="options[0]"
```
Comment (afbora) [inline panel/src/components/Navigation/OptionsDropdown.vue:5]: I'm not sure what for? This line causing the `e.apply is not a function` error.

Comment (bastianallgeier) [reply panel/src/components/Navigation/OptionsDropdown.vue:5]: The idea is that the first item in the options dropdown will be used to define the toggle button if there's just one option in the dropdown. I think we could make it more stable by adding a v-if to the toggle button to check if there are any options at all.

Comment (afbora) [reply panel/src/components/Navigation/OptionsDropdown.vue:5]: We're talking about `v-bind`, right? Right now my PR seems to be working great. 

I couldn't foresee where it would error/malfunction. Because we already have `v-if` condition for single and multiple options. Frankly, I have no idea about the solution 🤷‍♂️

**Review by bastianallgeier — APPROVED** [review]
I think it's fine like this
