### PR TITLE
Passing empty string for `is_file()` when param `null` 

### LINKED ISSUE #4032: PHP 8.1: "is_file(): Passing null to parameter #1 ($filename) of type string is deprecated"
## Description

CleanShot 2021-12-10 at 09 46 33@2x

I have 3 snippet calls for prepending or appending code as needed. **None of these snippets exist** until I need them. Until now this method has worked well. When upgrading to PHP 8.1 I get the following error:

CleanShot 2021-12-10 at 10 10 17@2x

With PHP 8.1 the [deprecation](https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation) shown in the screenshot above is not handled by Kirby as of version 3.6.1.1.

**Expected behavior**  
I expect Kirby to ignore snippets that don't exist, without producing an error.

## To reproduce

1. Be sure to have PHP 8.1 installed
2. In PHP call a snippet that doesn't exist.
3. You should see the Error

## Your setup
**Kirby Version**  
Kirby 3.6.1.1

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

All `is_file()` functions checked. There was only one that accept `null` parameter and it fixed.

### Fixes

- Fixed passing `null` to parameter to `is_file()` function in `Tpl::load()` method on PHP 8.1 #4032

## Breaking changes

None

## Related issues/ideas

- Fixes #4032

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Review by distantnative — DISMISSED** [review]

File: src/Toolkit/Tpl.php [hunk 1]
```diff
@@ -19,13 +19,14 @@ class Tpl
...
+     * @param string|null $file
      * @param array $data
      * @return string
+     * @throws Throwable
      */
-    public static function load(string $file = null, array $data = []): string
+    public static function load(?string $file = null, array $data = []): string
     {
-        if (is_file($file) === false) {
+        if (is_file($file ?? '') === false) {
```
Comment (lukasbestle) [inline src/Toolkit/Tpl.php]:
```suggestion
        if ($file === null || is_file($file) === false) {
```

**Review by lukasbestle — DISMISSED** [review]

**Review by lukasbestle — APPROVED** [review]
