### PR TITLE
Set default locale for intl extension from config

### LINKED ISSUE #4304: 'intl' date handler outputs random translation on multilanguage site
## Description
Using the new `intl` date handler on a multilanguage site, the date output language is picked randomly from the available languages.

**Expected behavior**  
Date output language correponds to the current selected language.

**Video of the behavior**  
[See video](https://cln.sh/BO5pbm)

## To reproduce
On a fresh install of Kirby 3.6.6

1. Configure the site to have languages available and `intl` as the date handler:
```php
// config.php
return [
  'languages' => true,
  'date.handler'  => 'intl',
]
```
2. Add two languages:
```php
// languages/lt.php
return [
    'code' => 'lt',
    'default' => true,
    'direction' => 'ltr',
    'locale' => [
        'LC_ALL' => 'lt_LT'
    ],
    'name' => 'Lietuvių',
]
```

```php
// languages/en.php
return [
    'code' => 'en',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        'LC_ALL' => 'en_US'
    ],
    'name' => 'English',
]
```

3. Ouput the date with month as a word:

```php
// somewhere in the template
<span><?= $page->date()->toDate('Y, LLLL') ?></span>
```
4. Reload browser multiple times. (Sometimes it stays in one language for 10 reloads, sometimes it changes every second reload).

### PR DESCRIPTION
**Pull request by lukasbestle**
### Fixes

- The `intl` date handler now consistently uses the configured default locale #4304

### Breaking changes

None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

File: src/Toolkit/Locale.php [hunk 1]
```diff
@@ -135,9 +135,19 @@ public static function set($locale): void
...
+		// locale for core string functions
 		foreach ($locale as $key => $value) {
 			setlocale($key, $value);
 		}
+
+		// locale for the intl extension
+		$timeLocale = $locale[LC_TIME] ?? $locale[LC_ALL] ?? null;
+		if (
+			$timeLocale !== null &&
+			function_exists('locale_set_default') === true
```
Comment (distantnative) [inline src/Toolkit/Locale.php]:
```suggestion
		if (
			function_exists('locale_set_default') === true &&
			$timeLocale = $locale[LC_TIME] ?? $locale[LC_ALL] ?? null
```

**Review by distantnative — APPROVED** [review]
