### PR TITLE
Fix table layout heading alignment

### LINKED ISSUE #4630: table layout: alignment does not affect column heading
When aligning right in the pagetable extension, the column heading also aligns right, but in the new table layout the column heading is unaffected.

I feel this is the wrong behavior.

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

Fixes table layout heading alignment and some RTL issues.

### Fixes
- table layout heading alignment working properly #4630 

### Breaking changes
None

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

File: panel/src/components/Layout/Table.vue [hunk 1]
```diff
@@ -418,6 +399,15 @@ export default {
 	height: var(--table-row-height);
 }
 
+/* Text aligment */
+.k-table-column[data-align] {
+	text-align: var(--align) !important;
```
Comment (distantnative) [inline panel/src/components/Layout/Table.vue:404]: Would be great if we can avoid this `!important`. Is it needed if we would remove the `text-align: start;` from above?

Comment (afbora) [reply panel/src/components/Layout/Table.vue:404]: I already tried but unfortunately when remove the `text-align: start;`, table header centered (seems default behaviour, not via custom css)

Comment (afbora) [reply panel/src/components/Layout/Table.vue:404]: Like that when your suggestion applied

captures_chrome-capture-2022-8-6 (1)

**Review by distantnative — APPROVED** [review]
