### PR TITLE
Fix broken image: false and image: icon options

### LINKED ISSUE #3633: [3.6.0-alpha.4]  - Image: false on page sections no longer works
**Describe the bug**  
No longer possible to hide the image on list view of page sections

**To Reproduce**  

```
menu:
      headline: ' '
      type: pages
      status: all
      image: false

```
**Expected behavior**  
No black squares on the page items

**Screenshots**  
Screenshot 2021-08-12 at 10 37 32

**Kirby Version**  
3.6.0-alpha.4

**Desktop:**  
 - OS: OSX
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by bastianallgeier**

### CODE REVIEW

**Review by afbora — APPROVED** [review]

File: panel/src/helpers/color.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default function (string) {
 
   if (
     string.match(
-      /^(black|white|light|gray|red|orange|yellow|green|aqua|blue|purple})/i
+      /^(black|white|light|gray|red|orange|yellow|green|aqua|blue|purple)/i
```
Comment (bastianallgeier) [inline panel/src/helpers/color.js:12]: good catch!
