### PR TITLE
Fix nullable search query

### LINKED ISSUE #5428: Search component broken when query is `null`
## Description

> Kirby\Cms\Core::{closure}(): Argument #3 ($query) must be of type string, null given, called in /kirby/src/Cms/Search.php on line 40

Regression PR: [Clean up search component](https://github.com/getkirby/kirby/pull/5297)

## To reproduce
````php
$results = $site->search(get('not-exists-param'), 'title|text');
````

## Your setup
Kirby 3.9.6

### PR DESCRIPTION
**Pull request by afbora**
### Fixes
- Fix nullable search query #5428

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

File: config/components.php [hunk 1]
```diff
@@ -140,9 +140,16 @@
...
 		Collection $collection,
-		string $query = '',
-		$params = []
+		string $query = null,
+		array|string $params = []
 	): Collection|bool {
+		$query = trim($query ?? '');
+
+		// empty search query
+		if (empty($query) === true) {
```
Comment (lukasbestle) [inline config/components.php]: Could we also cover the "shorter than minlength" check from line 168 here? Or rather delete this additional check and move the `clone $collection` in line 164 after the check in line 168? This avoids duplicate code.

File: config/components.php [hunk 2]
```diff
@@ -140,9 +140,16 @@
 	'search' => function (
 		App $kirby,
 		Collection $collection,
-		string $query = '',
-		$params = []
+		string $query = null,
```
Comment (lukasbestle) [inline config/components.php]: This should still primarily be a string IMO, but a nullable one:

```suggestion
		string|null $query = '',
```

File: config/components.php [hunk 3]
```diff
@@ -154,9 +154,9 @@
 			'words'     => false,
 		];
 
-		$collection  = clone $collection;
-		$options     = array_merge($defaults, $params);
-		$query       = trim($query);
+		$collection = clone $collection;
```
Comment (lukasbestle) [inline config/components.php]: I think this clone operation can be removed completely as both `$collection->limit()` (via `$collection->slice()`) and `$collection->filter()` also clone the collection before any operation. Removing this line would increase performance for large collections.

```suggestion
```

**Review by bastianallgeier — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]
