### PR TITLE
fix focus handling of block option buttons

### LINKED ISSUE #3941: Copy blocks with Writer preview not possible in Chrome
In Chrome you can't copy blocks that have a Writer preview and they are the last element you click on. See the small video for demonstration. In Safari it works. But unfortunately not in Chrome on the Mac

Kapture 2021-11-17 at 13 36 38

### LINKED ISSUE #4129: [Panel] Cannot copy multiple blocks
## Description
The button to copy multiple blocks does not work when an input element is focused. 

**Expected behavior**  
The focused input should "blur" before the copy operation is tried or the copy operation should work "anyway" when started from the button click.

## To reproduce
1. In a blocks field, create at least 1 text block
2. Select the block via Ctrl/Cmd + Click
3. Notice that the writer instance in the text block did not loose focus
4. Click on the copy button

Nothing is copied.

## Your setup
**Kirby Version** : 3.6.2, but also previous versions. 

**Console output**  
No console output

**Your system (please complete the following information)**
 - Device: PC
 - OS: Win 10
 - Browser: Chrome
 - Version: 97

**Additional context**  
The execution of the copy function in "Blocks.vue" is halted here:
```js
// don't copy if an input is focused
if (this.isInputEvent(e) === true) {
  return false;
}
```

## Quick fix
In **BlockOptions.vue**, the click on the copy (and also delete) button is handled by a `mousedown` event. This event fires before the browser has a chance to change focus from Input element to Button. As I understand it, the `mousedown` event was chosen, instead of a normal `click` event, because there is also a global "onOutsideFocus" that fires when a button is clicked that "deselects the blocks", and therefore the copy event has to fire before this "focus" event. 
The quickest fix would be to manually `blur()` the `activeElement` when the copy button receives "mouseDown".

### LINKED ISSUE #4131: [Panel] Cannot remove multiple blocks
## Description
Trying to remove multiple blocks does not work. I click on "Delete" in the confirmation dialog, but nothing happens. 

**Expected behavior**  
The previously selected blocks should be deleted. 

**Screenshots**  

https://user-images.githubusercontent.com/6684137/152362459-6e085178-8747-44b1-b446-86c7a3a28a7f.mov

## To reproduce

1. Select multiple blocks
2. Try to delete them via the  batched selection flow. 

## Your setup
**Kirby Version**: 3.6.2

**Console output**  
No console output

**Your system (please complete the following information)**
 - Device: Desktop PC
 - OS: Win 10
 - Browser: Chrome
 - Version: 97

**Additional context**  
In the moment I click on the 🗑 button, the `onOutsideFocus` method in Blocks.vue fires and removes the blocks from the selection. Once I get to click on the confirmation "Delete" button, the blocks are no longer selected and are therefore not deleted.

### PR DESCRIPTION
**Pull request by rasteiner**
## Describe the PR
BlockOptions now use a Click handler, but don't send a focus event to Blocks.vue.  This allows them to be clicked without losing the blocks selection.
Focus events in dialogs also no longer cause the selection to be lost.

## Release notes
 - Fixes delete and copy blocks buttons not working as expected in Chrome

## Breaking changes
None

## Related issues/ideas
- Fixes https://github.com/getkirby/kirby/issues/4129
- Fixes https://github.com/getkirby/kirby/issues/4131
- Fixes https://github.com/getkirby/kirby/issues/3941

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by rasteiner** [comment]
I see the failed coding style check, but I don't understand the error message :/

--- 
edit: ok, next time I'll run "prettier" before submitting

File: panel/src/components/Forms/Blocks/Block.vue [hunk 1]
```diff
@@ -202,6 +202,14 @@ export default {
         }
       }
     },
+    onFocusIn(event) {
+      // skip focus if the event is coming from the options buttons
```
Comment (distantnative) [inline panel/src/components/Forms/Blocks/Block.vue:206]:
```suggestion
      // skip focus if the event is coming from the options buttons
      // to preserve the current focus (since options buttons directly
      // trigger events and don't need any focus themselves)
```

File: panel/src/components/Forms/Blocks/Blocks.vue [hunk 2]
```diff
@@ -472,6 +472,11 @@ export default {
       this.isMultiSelectKey = event.metaKey || event.ctrlKey || event.altKey;
     },
     onOutsideFocus(event) {
+      //ignore focus in dialogs
```
Comment (distantnative) [inline panel/src/components/Forms/Blocks/Blocks.vue]:
```suggestion
      // ignore focus in dialogs to not alter current selection
```

**Review by distantnative — COMMENTED** [review]
Looks good to me. Only added some suggestions to make the comments more detailed.

@bastianallgeier should have a final look at this as he wrote the initial implementation and might better know if we are missing any other consideration.

**Comment by afbora** [comment]
Looks fixed all issues, works great for me 🎉 @rasteiner Great job for triple fixes 👏

**Comment by rasteiner** [comment]
> @rasteiner Great job for triple fixes 👏

well, to be fair it's only a "double fix" and a duplicate xD

**Review by bastianallgeier — APPROVED** [review]
LGTM
