### PR TITLE
fix: treat post_max_size=0 as unlimited

### LINKED ISSUE #8022: Disabiling PHP's post_max_size causes uploads to fail.
## Description
As per [PHP's documentation](https://www.php.net/manual/en/ini.core.php#ini.post-max-size) `post_max_size=0` can be used to disable the maximum size of post data. Kirby however uses the value as a literal, meaning a value of 0 will cause uploads to fail.

**Expected behavior**  
Uploads should still work with the maximum limit set by `upload_max_filesize`.

## To reproduce
1. Set `post_max_size=0` in the PHP INI.
2. Try to upload a file through Kirby and see that it fails.
3. Comment out [this line](https://github.com/getkirby/kirby/blob/bbb64db1516140fe43f54667af10a011a67cb3b5/src/Api/Upload.php#L66) in Kirby's source.
4. Try to upload a file again and see that the upload works, up to the maximum set by `upload_max_filesize`.

## Your setup
**Kirby Version**  
5.3.2

**Your system (please complete the following information)**
 - Device: PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 148.0.2

**Additional context**  
I didn't create a pull request because I wasn't sure how you want to handle a disabled maximum limit. Setting a limit of 0 was probably an error on my part to begin with but I still think this is a valid bug as it contradicts PHP's documentation.

### PR DESCRIPTION
**Pull request by afbora**
## Description

In PHP, `post_max_size=0` means that the POST size limit is disabled.

Kirby currently interprets this value as a literal `0`, which causes uploads to fail because the calculated chunk size becomes `0` and the upload validation may throw the wrong error.

This PR treats `post_max_size=0` as unlimited and ignores it when determining the effective upload size.

### 🐛 Bug fixes

- Disabiling PHP's post_max_size causes uploads to fail. #8022

## For review team

- [ ] Add lab and/or sandbox examples (wherever helpful)
- [ ] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Waiting for @lukasbestle second look for potential security problems though.

File: src/Api/Upload.php [hunk 1]
```diff
@@ -62,10 +62,16 @@ public static function chunkId(string $id): string
 	public static function chunkSize(): int
 	{
 		$max = [
-			Str::toBytes(ini_get('upload_max_filesize')),
-			Str::toBytes(ini_get('post_max_size'))
+			Str::toBytes(ini_get('upload_max_filesize'))
```
Comment (lukasbestle) [inline src/Api/Upload.php:65]: `Thought`: I checked the default for `post_max_size` at Uberspace, which I trust to use sane defaults. They set both `post_max_size` and `upload_max_filesize` to 2048M, which seems quite generous. Actually I think that this large of a chunk size is almost unwieldy.

But this is of course entirely independent from this fix. If someone configured `post_max_size=0`, this didn't work at all before and now it does. `upload_max_filesize` on the other hand does not seem to support an unlimited value, at least such a value isn't documented. This should mean that the chunk size is always limited to something, which is the most important part.

In a future step, we might want to consider a hard cap for the chunk size e.g. of 1 GB by adding that as another (hard-coded) value to `$max`. I don't really see how larger chunks could have any real-world benefits.

But this PR itself looks good to me and I don't see any risk to existing sites. Sites with explicit `post_max_size=0` will behave as expected, so there is no security risk there either.

**Review by lukasbestle — APPROVED** [review]
