### PR TITLE
Avoid invalid content types for missing representations

### LINKED ISSUE #2924: Using .php in URLs can lead to unwanted content representations
**Describe the bug**  
When you add .php to the path of a page and the slug is the same as the template (i.e. /blog.php and the template is blog.php) Kirby will load the HTML code of the blog.php template and send a content type that will force the browser to show the result. 

We should disable content representations for .php entirely.

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

When a content representation cannot be found, the App::resolve method still set the wrong content type according to the given extension. Of course this can lead to unwanted side-effects. (see issue) 

## Related issues

- Fixes #2924

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`

### CODE REVIEW

**Review by distantnative — DISMISSED** [review]
LGTM

File: tests/Cms/Pages/PageTemplateTest.php [hunk 1]
```diff
@@ -106,4 +106,27 @@ public function testRepresentationError()
...
+                        'template' => 'blog'
+                    ]
+                ]
+            ]
+        ]);
+
+        $this->app->resolve('blog.php');
+
+        // there must be no forced php response type if the
+        // represenation cannot be found
```
Comment (lukasbestle) [inline tests/Cms/Pages/PageTemplateTest.php]:
```suggestion
        // representation cannot be found
```

**Review by lukasbestle — COMMENTED** [review]
The fix is great and simple!

IMO the test should be in the `AppResolveTest` class to keep it with the other tests for the tested method. It would be good to also check the return value of `$app->resolve()`, which should be `null`.

**Comment by bastianallgeier** [comment]
@lukasbestle You are right! I just moved the test, added the assertion and fixed the typo

**Review by lukasbestle — APPROVED** [review]

**Review by afbora — APPROVED** [review]
I really like the new `php` presentation with this fix 🎉
