### PR TITLE
Fix/progress bar styling

### LINKED ISSUE #2784: Progress bar styling inconsistent
**Describe the bug**  
The progress bar component is not styled in firefox. In Chrome and Safari I noticed that if the width of the progress indicator is less then it's height the border radius gets smaller and it overflows the bar.

**Screenshots**

Firefox:
Bildschirmfoto 2020-08-18 um 23 15 54

Chrome:
Bildschirmfoto 2020-08-18 um 23 15 59

**Kirby Version**  
3.4.2

### PR DESCRIPTION
**Pull request by qwerdee**
## Describe the PR

This PR fixes styling Issues of the progress bar component. Styles for firefox are added and overflowing the bar is now prevented.

## Related issues

- Fixes #2784 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Fixed code style issues with CS fixer and `composer fix`
- [ ] Added in-code documentation (if needed)

### CODE REVIEW

File: panel/src/components/Misc/Progress.vue [hunk 1]
```diff
@@ -41,7 +44,13 @@ export default {
 }
 
 .k-progress::-webkit-progress-value {
-  border-radius: 20px;
+  border-radius: inherit;
+  background: $color-focus;
+  transition: width 0.3s;
+}
+
```
Comment (distantnative) [inline panel/src/components/Misc/Progress.vue:51]: Let’s keep it DRY and combine both rule sets

Comment (qwerdee) [reply panel/src/components/Misc/Progress.vue:51]: That doesn't work in this case since these are vendor specific selectors. In all cases one of them is not recognized, so the whole block is ignored

Comment (qwerdee) [reply panel/src/components/Misc/Progress.vue:51]: https://stackoverflow.com/questions/50580986/why-cant-i-combine-pseudo-element-selectors/50581522#50581522

Comment (distantnative) [reply panel/src/components/Misc/Progress.vue:51]: I see. Good to know!

**Review by bastianallgeier — APPROVED** [review]
