### PR TITLE
Move changes dropdown to the backend to fix broken links and other is…

### LINKED ISSUE #3854: [3.6.0-rc.2] Files name and link broken in unsaved changes
**Describe the bug**  

**To Reproduce**  
1. Go to panel (demokit)
2. Go to file detail (`/pages/portfolio+projects+sky/files/tent-in-the-woods.jpg`)
3. You'll see unsaved changes
4. See file name missing
5. Nevertheless click it, you'll see broken link that missing `files` segment (`/panel/pages/portfolio+projects+sky+tent-in-the-woods.jpg`)

**Kirby Version**  
3.6.0-rc.2

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

The changes dropdown was always a bit hacky. We had to send a single request for every model in the changes store and then build the options in JS. After the move to Fiber the links and labels were broken. I decided to not fix it in JS, but move to a Fiber dropdown instead. This works better than expected but also requires a couple changes throughout multiple classes. It's all tested and should not be a big deal, but it would be good if @distantnative and @afbora could have a closer look. 

## Related issues/ideas

- Fixes #3854

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

File: panel/src/components/Forms/FormIndicator.vue [hunk 1]
```diff
@@ -40,10 +40,10 @@ export default {
     ids() {
       return Object
         .entries(this.store)
-        .filter(([id, model]) => {
+        .filter(([, model]) => {
           return Object.keys(model.changes).length > 0;
         })
-        .map(([id, model]) => {
+        .map(([id]) => {
```
Comment (distantnative) [inline panel/src/components/Forms/FormIndicator.vue]: Looking at this... wouldn't it make more sense to go with `Object.keys` in line 42 then?

Comment (bastianallgeier) [reply panel/src/components/Forms/FormIndicator.vue]: I thought it's quite nice to get access to the model and the id like this because the model is needed in 44

Comment (distantnative) [reply panel/src/components/Forms/FormIndicator.vue]: I mean, it's no dealbreaker, but I jus thought that this is shorter and still not so bad on line 44?

```js
return Object
  .keys(this.store)
  .filter((id) => {
    return Object.keys(this.store[id].changes).length > 0;
  })
  ```

**Comment by distantnative** [comment]
I like this a lot - and seems to work fine for me so far.
It's a good step - also for when we will eventually move unsaved changes to the server (and thus the backend anyways).

File: panel/src/components/Forms/FormIndicator.vue (hunk 1 above)
Comment (bastianallgeier) [reply panel/src/components/Forms/FormIndicator.vue]: You are right. I updated it.

**Comment by bastianallgeier** [comment]
@distantnative I agree. It helps quite a lot to think about a backend implementation already.

**Review by distantnative — APPROVED** [review]
We should add a note to the final release notes that all unsaved changes should be cleared before upgrading to a new major version.
