### PR TITLE
Fix blocks stuck as selected in blocks within layout field 

### LINKED ISSUE #3856: [3.6.0-rc.2] Blocks stuck as selected in blocks in layout field
**Describe the bug**  

When clicking (normal click, not multiselect) on blocks in different layouts in the layout field within the block field , it stays selected.

````yaml
# sample blueprint
fields:   
  blocks:
    type: blocks
    fieldsets:
      test:
        fields:
          layout:
            type: layout
````

### Steps

1. Add a block
2. Add multiple layouts in drawer
3. Add blocks (for ex line block to see clear) for each layout
4. Now try to click/select blocks
5. See issue

**Screenshots**  

screen-capture-1228-Test - Mægazine-localhost

**Kirby Version**  

3.6.0-rc.2

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Since we are still working in the same block when overlay is open, we cannot detect the transition between the layout columns. This PR codes detect if the target is in the same column. 

I'm not sure as it looks a bit hacky 🤷‍♂️ 

### Fixes
- Fix blocks stuck as selected in blocks within layout field #3856

## Breaking changes

None

## Related issues/ideas

- Fixes #3856

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

**Comment by distantnative** [comment]
Are you still working on this @afbora or should we switch it to ready for review (not draft)?

**Comment by afbora** [comment]
@distantnative Ready to review. I created as draft because I'm not sure as it looks a bit hacky.

File: panel/src/components/Forms/Blocks/Blocks.vue [hunk 1]
```diff
@@ -467,6 +467,16 @@ export default {
       if (this.$el.contains(event.target) === false && (!overlay || overlay.contains(event.target) === false)) {
         this.select(null);
```
Comment (distantnative) [inline panel/src/components/Forms/Blocks/Blocks.vue]: We should probably return here, right? Or should we continue with the new code even if this `this.select(null)` happened here on line 468?

**Comment by distantnative** [comment]
I am not really sure if I get when the bug is happening. Could you help me and describe it in steps maybe? e.g. 1. open block, 2. click on x 3. click on y....? That would be great

**Comment by afbora** [comment]
You can test the blueprint that I've posted in issue description?

````yaml
# sample blueprint
fields:   
  blocks:
    type: blocks
    fieldsets:
      test:
        fields:
          layout:
            type: layout
````

### Steps

1. Add a block
2. Add multiple layouts in drawer
3. Add blocks (for ex line block to see clear) for each layout
4. Now try to click/select blocks
5. See issue

File: panel/src/components/Forms/Blocks/Blocks.vue (hunk 1 above)
Comment (afbora) [reply panel/src/components/Forms/Blocks/Blocks.vue]: You're probably right, our goal is to empty the selection anyway.

**Review by bastianallgeier — APPROVED** [review]
Works like a charm
