### PR TITLE
`Version::create()`: don't always create latest

### LINKED ISSUE #7184: [v5] creating file content translation throws exception
For non-default languages

### LINKED ISSUE #7185: [v5]`latest` content file for translations created too early
Gets already created for unsaved changes instead of only when publishing

### PR DESCRIPTION
**Pull request by distantnative**
### Summary of changes
- `Version::create()` does not automatically create a latest version a language anymore when creating a changes version for the language. This allows for the following scenario
  - Page has a latest version of the default language, not translated in any secondary language
  - Start drafting the version for. a secondary language (as changes version)
  - Only have a latest version once the changes version for the secondary language is published

### Reasoning
We do not want to create latest/published versions for a secondary language immediately when a Panel user starts editing/creating it.

### Fixes from earlier pre-releases
- https://github.com/getkirby/kirby/issues/7184
- https://github.com/getkirby/kirby/issues/7185

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: src/Content/Version.php [hunk 1]
```diff
@@ -502,8 +488,8 @@ public function publish(Language|string $language = 'default'): void
 		// check if publishing is allowed
 		VersionRules::publish($this, $language);
 
-		$latest  = $this->sibling('latest')->read($language);
-		$changes = $this->read($language);
+		$latest  = $this->sibling('latest')->read($language) ?? [];
+		$changes = $this->read($language) ?? [];
```
Comment (distantnative) [inline src/Content/Version.php:492]: @bastianallgeier this change is necessary as we get otherwise an `foreach argument is null` error. But it makes me wonder whether it is the best decision that `::read()` returns `null`.

Comment (bastianallgeier) [reply src/Content/Version.php:492]: I wonder about that as well. We still have the ::exists method in addition if you really need to find out if content exists or not.

Comment (bastianallgeier) [reply src/Content/Version.php:492]: I looked at it again and I think it adds some value and clarity to return null here when the version does not exist, even if it is a bit more effort to write the fallbacks. I would leave it as it is.

**Review by bastianallgeier — APPROVED** [review]
