### PR TITLE
Table layout: fix `mobile` columns

### LINKED ISSUE #6106: Pages section with table layout doesn’t hide columns on mobile
I use the following structure for a section to display entries:

```
sections:
  entries:
    type: pages
    query: page.entries
    layout: table
    columns:
      tags:
        type: tags
        width: 1/2
      date:
        width: 1/6
        align: right
        value: "{{ page.date.toDate('M d, Y') }}"
```

What I expect from the [documentation about the table layout](https://getkirby.com/docs/reference/panel/sections/pages#layout__table-layout) is that all columns other than the title are hidden on mobile, and they can be enabled with `mobile: true`.  Since Kirby 4, all columns remain and mostly cover the title, so I cannot even get to the child page (see screenshot 2).

I pointed this out [in the forum](https://forum.getkirby.com/t/mobile-option-on-table-layout-doesn-t-seem-to-apply/30008) already but it seems like it hasn’t been addressed yet.

Screenshot 2023-12-31 at 1 43 04 PM
Screenshot 2023-12-31 at 1 43 16 PM

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- Table layout: columns marked as `mobile: true` are shown again in narrow viewports 
#6106

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add example to sandbox

### CODE REVIEW

File: panel/src/components/Layout/Table.vue [hunk 1]
```diff
@@ -108,7 +116,12 @@
 						/>
 
 						<!-- Options -->
-						<td v-if="hasOptions" data-mobile class="k-table-options-column">
+						<td
+							v-if="hasOptions"
+							data-mobile="true"
+							true
```
Comment (afbora) [inline panel/src/components/Layout/Table.vue]: What for it? 🙂

Comment (distantnative) [reply panel/src/components/Layout/Table.vue]: That's not supposed to be there :D

**Review by afbora — DISMISSED** [review]

**Review by afbora — APPROVED** [review]
