### PR TITLE
Fix overwritable site title #3901

### LINKED ISSUE #3901: [3.6.0-rc.3] Title in site blueprint cannot be changed
**Describe the bug**  
Changing the `title` in the site blueprint does no longer work.

**To Reproduce**  
1. Download plainkit
2. Update to kirby 3.6.0 rc.3
3. Open `site.yml`, change `title:`

**Expected behavior**  
In Kirby 3.5, changing the title is possible: https://getkirby.com/docs/reference/panel/blueprints/site#title

**Kirby Version**
3.6.0-rc.3

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Now the menu name can be changed again with the custom site title from the site blueprint.

### Fixed regressions from 3.6.0-rc.3

- Fixed overwritable custom site title #3901

## Breaking changes

None

## Related issues/ideas

- Fixes #3901 

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [x] Add changes to release notes draft in Notion

### CODE REVIEW

File: config/areas/site.php [hunk 1]
```diff
@@ -7,7 +7,7 @@
             return $kirby->site()->title()->or(t('view.site'))->toString();
```
Comment (afbora) [inline config/areas/site.php:7]: @bastianallgeier Do we need to update `breadcrumbLabel` too?

Comment (bastianallgeier) [reply config/areas/site.php:7]: No, as far as I know we only changed the menu label, which makes sense. The site title should still be visible in the breadcrumb in my opinion.

**Review by bastianallgeier — APPROVED** [review]
