### PR TITLE
Fix options in video helpers #2118

### LINKED ISSUE #2118: No options when using youtube()
**Describe the bug**
I don't get the parameters in the youtube url (iframe) when setting the $options in the youtube() function.

https://getkirby.com/docs/reference/templates/helpers/youtube

**To Reproduce**
In my Template i use the youtube() function with the $options to hide the controlls:

`
youtube($myVideoUrl, array("controlls" => 0))
`

**Expected behavior**
I want to get an iframe with the parameter _controlls_, like: 

<iframe allowfullscreen src="https://www.youtube.com/embed/123456789?controlls=0"></iframe> 

But the _?controlls=0_ is missing.

**Kirby Version**
3.2.4

**Console output**
No Output

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 69

**Additional context**
https://github.com/getkirby/kirby/blob/3.2.4/src/Toolkit/Html.php#L439
Is _$options['youtube']_ right? With _$options_ it works.

html::youtube() works perfectly.

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Describe the PR

The vimeo and youtube helpers did not pass the options argument correctly to the HTML::video method. 

## Related issues

- Fixes #2118

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`

### CODE REVIEW

File: src/Toolkit/Html.php [hunk 1]
```diff
@@ -465,7 +465,7 @@ public static function vimeo(string $url, ?array $options = [], array $attr = []
         }
 
         // build the options query
-        if (!empty($options)) {
+        if (empty($options) === false) {
```
Comment (lukasbestle) [inline src/Toolkit/Html.php:468]: Same change for the `youtube()` method?

Comment (bastianallgeier) [reply src/Toolkit/Html.php:468]: Yep, good idea!

**Review by lukasbestle — APPROVED** [review]
