### PR TITLE
Add ErrorPageException, fix pagination overflow

### LINKED ISSUE #1887: Pagination doesn't redirect to error page, shows last page instead.
**Describe the bug**
The current pagination, instead of returning an error page when trying to visit a page number that doesn't exist (for example visiting `page:50` in a collection that has only 10 pages) it's returning the last page of the pagination.

**To Reproduce**
1. In the starterkit homepage template, add a `paginate()` in the foreach loop. For example `foreach (page('photography')->children()->listed()->paginate(2)`
2. Try open a page with a stupidly high page number

**Expected behavior**
You should be redirected to the error page.

**Screenshots**
screenshot_2019-06-28_at_12 27 45

**Kirby Version**
This is happening in the current 3.2.0 but @texnixe has tested this and told me it goes back to 3.1.0

### PR DESCRIPTION
**Pull request by lukasbestle**
## Describe the PR

- Add new `ErrorPageException` that can be thrown while a page is rendered (e.g. from the template or controller) to trigger the error page
- Replace the single setters in the `Pagination` class with a new `setProperties()` method that validates the properties when setting
- Trigger the error page if the pagination page is out of bounds

## Related issues

- Fixes #1887

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if neeed)

### CODE REVIEW

**Comment by afbora** [comment]
FireShot Capture 772 - Kirby CMS Debugger - http___localhost_test_kirby_2147_page;2

Didn't work for me when i try to access second page `/page;2`. Am I wrong?

I checked the `$params['page']` variable, it has value `2` as `string` not `int`.

I think you may have passed the test because you tested directly with an integer value in the unit test.

**Comment by lukasbestle** [comment]
You are right, the validation was too strict. I have fixed it now.

**Comment by afbora** [comment]
Works great now! 👍 

Btw do we need to check the float numbers? 
I think it will always work because we cast to int, but I wanted to mention it anyway. 
For ex: `/page;3.14`

**Comment by lukasbestle** [comment]
There is unfortunately no native PHP function to check for strings that may only contain ints. Options are:

```php
(string)(int)$value === (string)$value
ctype_digit((string)$value) === true
```

Both are very clumsy and long, therefore I figured that the check for `is_numeric()` should be enough here. As you wrote, the value is casted to int anyway, so it doesn't really matter.

File: config/sections/mixins/pagination.php [hunk 1]
```diff
@@ -14,7 +14,7 @@
          * Sets the default page for the pagination. This will overwrite default pagination.
          */
         'page' => function (int $page = null) {
-            return get('page', $page ?? 1);
+            return get('page', $page);
```
Comment (bastianallgeier) [inline config/sections/mixins/pagination.php:17]: Is there a special reason not to fall back to 1 as the default page?

**Review by bastianallgeier — COMMENTED** [review]
Couldn't we still keep the single setters by using the setProperties method there as well?

Otherwise we should think about refactoring it completely in the same style we handle immutable objects in other places and provide a clone method instead of setProperties.

File: config/sections/mixins/pagination.php (hunk 1 above)
Comment (lukasbestle) [reply config/sections/mixins/pagination.php:17]: The automatic fallback now happens directly in the `setProperties()` method. The reason we need to do it there is that it would otherwise throw an Exception if the default page of 1 is passed for a collection with 0 items (= 0 pages).

**Comment by lukasbestle** [comment]
@bastianallgeier The question is why we had the setters in the first place. I think an immutable object with a clone function would indeed be the cleanest way.

In any case we need to remove the individual setters, otherwise the validation won‘t kick in.

**Comment by bastianallgeier** [comment]
@lukasbestle let's use this chance to move to our normal pattern with private setters that get called  once in the constructor and a clone method.

**Comment by lukasbestle** [comment]
Alright, will do that soon.

File: src/Toolkit/Pagination.php [hunk 2]
```diff
@@ -397,6 +381,86 @@ public function rangeEnd(int $range = 5): int
...
+        // generate "default page" based on other params
+        if ($this->page === null) {
+            $this->page = $this->firstPage();
+        }
+
+        // validate page based on all params
+        $min = $this->firstPage();
+        $max = $this->pages();
+        if ($this->page < $min || $this->page > $max) {
+            throw new ErrorPageException('Pagination page ' . $this->page . ' is out of bounds, expected ' . $min . '-' . $max);
```
Comment (bastianallgeier) [inline src/Toolkit/Pagination.php:405]: I think we need to make this translatable and also make it less technical. This will be passed to the error page as $errorMessage variable and can be used to display a custom error message there. So I think it should be a `human` as possible.

Comment (bastianallgeier) [reply src/Toolkit/Pagination.php:405]: I take my comment back. I think it's fine. We can't translate it in the toolkit class anyway.

**Review by bastianallgeier — DISMISSED** [review]
