### PR TITLE
Fix broken params in URLs

### LINKED ISSUE #4367: [3.7.0-rc.1] Panel ignores port configured in config
## Description
When using a non standard port in the `url` option inside `config.php`  the panel does not load.

The console logs:
```
Failed to execute 'pushState' on 'History': A history state object with URL 'http://localhost/panel/installation' cannot be created in a document with origin 'http://localhost:8090'
```

The detection in the new Environment class seems to work since `$kirby->environment()->url()` returns the right path.

### LINKED ISSUE #4394: [3.7.0-rc.1] URL with params redirect to error page
A URL like this: `website.test/view:list` worked as expected in `3.6.6` and directed to the homepage, making the `view` param accessible.

In `3.7.0-rc.1.` the same URL redirects to the error page.

### PR DESCRIPTION
**Pull request by bastianallgeier**
## Fixes

- Params in URLs were ignored after the refactoring with the environment class. They are now properly detected again. https://github.com/getkirby/kirby/issues/4394
- Could be fixing https://github.com/getkirby/kirby/issues/4367 as well, but needs to be tested.

## Breaking changes

`Server::requestUri` now returns an instance of `Kirby\Http\Uri` instead of an array with path and query.

## Ready?

- [x] ~Unit tests for fixed bug/feature~
- [x] ~In-code documentation (wherever needed)~
- [x] Tests and checks all pass

### For review team

- [ ] Add changes to release notes draft in Notion
- [x] ~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~

### CODE REVIEW

File: src/Http/Environment.php [hunk 1]
```diff
@@ -1008,12 +995,22 @@ public function toArray(): array
...
             'url'           => $this->url
         ];
     }
 
+    /**
+     * Returns the full base URL object
+     *
+     * @return \Kirby\Http\Uri
+     */
+    public function uri()
```
Comment (lukasbestle) [inline src/Http/Environment.php]: I think the name `uri()` is very easy to confuse. It could both be the the base URI or the full request URI. What about `baseUri()`?

Also: For consistency, the `requestUri()` could return a `Http\Uri` object as well. I know that this out of scope of this PR, but we can never make such consistency fixes again after 3.7 without breaking changes.

Comment (bastianallgeier) [reply src/Http/Environment.php]: I already refactored the requestUri method to return an URI object as well. 

We now have: 

```php
$environment->url()
$environment->uri()

$environment->requestUrl()
$environment->requestUri()
```

I like the idea to rename uri and url to base uri and base url. Will take care of it.

File: src/Http/Environment.php [hunk 2]
```diff
@@ -180,7 +213,7 @@ public function detect(array $options = null, array $info = null): array
         // @codeCoverageIgnoreStart
         if (is_int($options['allowed']) === true) {
             Helpers::deprecated('
-                Using `Server::` constants for the `url` option has been deprecated and support will be removed in 3.8.0. Use one of the following instead: a single fixed URL, an array of allowed URLs to match dynamically, `*` wildcard to match dynamically even from insecure headers, or `true` to match automtically from safe server variables.
+                Using `Server::` constants for the `baseUrl` option has been deprecated and support will be removed in 3.8.0. Use one of the following instead: a single fixed URL, an array of allowed URLs to match dynamically, `*` wildcard to match dynamically even from insecure headers, or `true` to match automtically from safe server variables.
```
Comment (lukasbestle) [inline src/Http/Environment.php]:
```suggestion
                Using `Server::` constants for the `allowed` option has been deprecated and support will be removed in 3.8.0. Use one of the following instead: a single fixed URL, an array of allowed URLs to match dynamically, `*` wildcard to match dynamically even from insecure headers, or `true` to match automtically from safe server variables.
```

File: src/Cms/App.php [hunk 3]
```diff
@@ -1219,7 +1222,11 @@ public function path(): string
             return $this->path;
         }
 
-        return $this->path ??= $this->environment()->requestPath();
+        $current = $this->request()->path()->toString();
+        $index   = $this->environment()->baseUri()->path()->toString();
+        $path    = Str::afterStart($current, $index);
```
Comment (lukasbestle) [inline src/Cms/App.php:1227]: This could fail if for some reason `$current` does not start with `$index`. In theory this should never happen, but if it does, this method will return a full URI including scheme and host. Maybe something like this:

```suggestion

        // catch edge cases that shouldn't occur
        // @codeCoverageIgnoreStart
        if (Str::startsWith($current, $index) !== true) {
            throw new LogicException('Could not determine request path');
        }
        // @codeCoverageIgnoreEnd
        
        $path = Str::afterStart($current, $index);
```

**Review by lukasbestle — COMMENTED** [review]
I've now read through the full code. It's really awesome how everything fits together now and how clean it is. 👍:tada:

Two minor things I noticed, apart from that it's ready to merge IMO.

File: src/Http/Environment.php [hunk 4]
```diff
@@ -317,6 +353,26 @@ protected function detectAuto(bool $insecure = false): void
...
+    protected function detectBaseUri()
+    {
+        $this->baseUri = new Uri([
+            'host'   => $this->host,
+            'path'   => $this->path,
+            'port'   => $this->port,
+            'scheme' => $this->https ? 'https' : 'http',
+        ]);
+
+        $this->baseUrl = $this->baseUri->toString();
```
Comment (lukasbestle) [inline src/Http/Environment.php:371]: Maybe we could make the `baseUrl` and `requestUrl` props lazy so that they are only initialized when needed.

Comment (bastianallgeier) [reply src/Http/Environment.php:371]: I thought about that as well, but we actually need them immediately in the App class, so it doesn't really make sense.

File: src/Cms/App.php (hunk 3 above)
Comment (bastianallgeier) [reply src/Cms/App.php:1227]: I wouldn't do that to be honest. This is only about the path. Let's say for some weird reason the base URL has a different path than the request URL, then the request path would still be returned entirely, which sounds right to me.

Comment (lukasbestle) [reply src/Cms/App.php:1227]: Right!

File: src/Http/Environment.php (hunk 4 above)
Comment (lukasbestle) [reply src/Http/Environment.php:371]: Currently on the go, so can't check. But I thought the App class only uses the Uri objects? If it really uses both strings then I agree with you.

**Review by lukasbestle — APPROVED** [review]

File: src/Http/Environment.php (hunk 4 above)
Comment (bastianallgeier) [reply src/Http/Environment.php:371]: Just double-checked. BaseUrl is used in the Core.php pretty much immediately. I think it doesn't make sense to convert one into a lazy method and keep the other unlazy, so I would keep it as it is.
