### PR TITLE
Fix `api.methodOverride` option

### LINKED ISSUE #6984: Reconsider `api.methodOverwrite` option
See https://github.com/getkirby/kirby/pull/6650#issuecomment-2634970023:

- [x] Remove automated check as it doesn't work with the default of `true`
- [x] Rename option to `api.methodOverride` (overwrite was a typo when we originally introduced it in the Panel code)

### PR DESCRIPTION
**Pull request by distantnative**
### Summary of changes
- Corrected option name
- Removed JS automatic system check
- Fixed console error when local (no `urls`)

### Breaking changes
- `api.methodOverwrite` option has been renamed to `api.methodOverride`

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]

File: src/Panel/View.php [hunk 1]
```diff
@@ -262,7 +262,7 @@ public static function globals(): array
 		return [
 			'$config' => fn () => [
 				'api'         => [
-					'methodOverwrite' => $kirby->option('api.methodOverwrite', true)
+					'methodOverride' => $kirby->option('api.methodOverride', true)
```
Comment (lukasbestle) [inline src/Panel/View.php:265]: `Suggestion` to keep backwards-compatibility:

```suggestion
					// TODO: Remove fallback to `api.methodOverwrite` in v6
					'methodOverride' => $kirby->option('api.methodOverride', $kirby->option('api.methodOverwrite', true))
```

We could add "Deprecated: Option `api.methodOverwrite`: Use `api.methodOverride` instead" into the release notes. I'd also be fine with the breaking change though as it's unlikely many users would be affected.

**Review by lukasbestle — COMMENTED** [review]
Thanks for taking care of it. I have removed the leftover translation that is no longer used and have one minor suggestion:

File: src/Panel/View.php (hunk 1 above)
Comment (distantnative) [reply src/Panel/View.php:265]: I'll let Basti decide on it. Totally valid suggestion. My take here was that it's gonna affect so few to none that we might just get it over right with v5.

Comment (bastianallgeier) [reply src/Panel/View.php:265]: I would agree with @distantnative here. It seems like one of the really minor breaking changes to me for v5 and in return we get a cleaner setup.
