### PR TITLE
Duplicating page: replace UUIDs with new ones

### LINKED ISSUE #4844: Duplicating pages without files does not remove files in panel
(I've already written a bit about this in a different bug #4831, posting here for visibility)
## Description
While duplicating a page, setting 'copy files?' to false used to generate a new page with only text content and no images. Now, it still copies the file-UUIDs from the original content file, and keeps the connection to the images from the original page.
This can be confusing for the user, because it is not obvious where those images are coming from.
I think that's bad UX: 
Some clients might keep using these images, then at some point delete the original page and will be suprised that all the images are gone.

**Expected behavior**  
Duplicating a page without files should remove links to file UUIDs not belonging to the new page.

I realise this is more complicated now with UUIDs.
With Kirby <= 3.7, the content.txt was simply copied, and no images, pointing to an image that didn't exist anymore in that folder:
```
Cover: - monster-trees-in-the-fog.jpg
```
The panel handled that invalid link nicely by just not showing any image.
Now with UUIDs, the panel still can find that image from the original page and displays it.

Just an idea: Since the file links have a very distinctive pattern, wouldn't it be possible to use regex
(maybe `file:\/\/[\w]{16}`) to invalidate file links during duplication?

```
Cover: - file://soTV5M2PG5DJfuHw
```
becomes
```
Cover: - file://
```

Or is that replacement operation too risky? 

I would just be nice to be able to use file UUIDs while still having the old, more natural duplication behaviour:
When duplication without images -> no images on new, duplicated page.

## To reproduce
- Create a page with images
- Duplicate that page, "copy files?" -> no
- The panel still shows linked images

## Your setup
**Kirby Version**  
3.8.1.1

### LINKED ISSUE #4867: Duplicating pages does regenerate file UUIDs, but does not update content file with new UUIDs
## Description
Related to #4831. 
Duplicating pages with files now regenerates file UUIDs, but the files linked in the content.txt still point towards the original page (the duplication source).

**Expected behavior**  
Duplicated files should be linked correctly in the content.txt.

## To reproduce
1. Create a page with images, with UUIDs active
2. Duplicate that page, with files
3. File UUIDs get regenerated, but linked are still the parent files, not the newly generated ones.

## Your setup
**Kirby Version**  
3.8.2

**Additional context**  
See also dicussion here #4844

### PR DESCRIPTION
**Pull request by distantnative**
### Summary of changes
- New `PageCopy` class to handle all adaptations for a copied page, its files and children
- Tracking a map of all `oldUUID => newUUID` relations when replacing a UUID on newly generated models
- Replacing all UUID mappings in all new content files
- Removing file UUIDs (replacing with empty string) if files aren't copied
- Removing children UUIDs (replacing with empty string) if children aren't copied
- New `ContenStorageHandler::replaceStrings()`

### Reasoning
- Removing UUIDs for files/children when not copying files/children: Users obligation to fix empty.invalid KirbyTags or other afterwards when not copying files. But in the end it did feel better in the UX to handle it this way, even though I initially thought differently.

### Additional context
- We will have to refactor the content storage changes directly for v5. But I think this way is the right way to implement it for v4.

### Enhancements
- Duplicating pages: All UUIDs within the copied page, its files and children that point to an object that got copied as well will be replaced with the UUID of the copied version. If no copying files, any UUID pointing to a file within the copied page gets removed.

## Docs

- See where to mention this behavior.

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: src/Cms/PageCopy.php [hunk 1]
```diff
@@ -0,0 +1,229 @@
...
+
+	/**
+	 * Returns the pages collection for children to adapt
+	 */
+	public function children(): Pages
+	{
+		return match ($this->children) {
+			true  => $this->copy->index(drafts: true),
+			false => new Pages()
+		};
```
Comment (bastianallgeier) [inline src/Cms/PageCopy.php]:
```suggestion
		if ($this->children === true) {
			return $this->copy->index(drafts: true);
		}

		return new Pages();
```

I can't help but feel uneasy with using match everywhere to be honest. It's one of those decisions that we would need to move along a lot more in so many other parts to turn it into a consistent coding style and I'm really not sure if it is helping. I don't want to block PRs because of this. I really just think that we should decide at which point it makes sense to use match and when there are just two cases like here, I would vote against it.

File: src/Cms/PageCopy.php [hunk 2]
```diff
@@ -0,0 +1,229 @@
...
+			// children because we already operate on the index
+			$child = new PageCopy($child, files: true, uuids: $this->uuids);
+			$child->convertUuids($language);
+			$this->uuids = [...$this->uuids, ...$child->uuids];
+		}
+
+		// if children have not been copied over,
+		// track all children UUIDs from original page to
+		// remove/replace with empty string
+		if ($this->children === false) {
```
Comment (bastianallgeier) [inline src/Cms/PageCopy.php]: I stumbled across the property name here while reading, because I thought it was somehow related to the children method. This is of course only happening because we use the children property in the Page method as a cache for the children method. But maybe it would help to rename the children and file properties to something like includeChildren and includeFiles or copyChildren and copyFiles. It's just a thought though after stumbling across it. It's not super important.

File: src/Cms/PageCopy.php [hunk 3]
```diff
@@ -0,0 +1,229 @@
...
+
+	/**
+	 * Returns the files collection for files to adapt
+	 */
+	public function files(): Files
+	{
+		return match ($this->files) {
+			true  => $this->copy->files(),
+			false => new Files()
+		};
```
Comment (bastianallgeier) [inline src/Cms/PageCopy.php]: See match comment above.

File: src/Cms/PageCopy.php [hunk 4]
```diff
@@ -0,0 +1,229 @@
...
+	 *
+	 * @todo Refactor once singe-lang mode also works with a language object
+	 */
+	public function languages(): Languages|iterable
+	{
+		$kirby = App::instance();
+
+		return match ($kirby->multilang()) {
+			true  => $kirby->languages(),
+			false => [null]
```
Comment (bastianallgeier) [inline src/Cms/PageCopy.php]: Same here (match)

File: src/Cms/PageCopy.php [hunk 5]
```diff
@@ -0,0 +1,229 @@
...
+		}
+
+		// apply all tracked UUID changes at once
+		$converter->replaceUuids();
+
+		return $converter->copy;
+	}
+
+	/**
+	 * Removes translated slug for copied page
```
Comment (bastianallgeier) [inline src/Cms/PageCopy.php]: I forgot again why we need this and had to look through the code first to understand it again. I think it would be helpful to add something like …
```suggestion
	 * Removes translated slug for copied page. This is needed to avoid translated slug collisions with the original page.
```

File: src/Content/ContentStorage.php [hunk 6]
```diff
@@ -217,6 +217,18 @@ public function read(
...
+	 *
+	 * @param array $map search-replace mapping where all keys are replaced by their values
+	 */
+	public function replace(array $map): void
+	{
+		foreach ($this->all() as $version => $lang) {
+			$this->handler->replace($version, $lang, $map);
+		}
+	}
+
```
Comment (bastianallgeier) [inline src/Content/ContentStorage.php]: The ContentStorage class no longer exists in the alpha. Is there any chance that we can implement this without relying on the wrapper class? I guess we will otherwise create some nasty merge conflicts later.

File: src/Content/ContentStorageHandler.php [hunk 7]
```diff
@@ -75,6 +75,20 @@ public function move(
...
 
+	/**
+	 * Searches and replaces one or multiple strings in all versions
+	 *
+	 * @param string $lang Code `'default'` in a single-lang installation
+	 * @param array $map search-replace mapping where all keys are replaced by their values
+	 *
+	 * @throws \Kirby\Exception\NotFoundException If the version does not exist
+	 */
+	public function replace(
```
Comment (bastianallgeier) [inline src/Content/ContentStorageHandler.php]: In the context of the content storage handler classes, I would think that "replace" means that the content is replaced/overwritten. We use Version::replace like that. Maybe we could use something like replaceStrings?

File: src/Content/PlainTextContentStorageHandler.php [hunk 8]
```diff
@@ -128,6 +128,24 @@ public function read(string $version, string $lang): array
...
 
+	/**
+	 * Searches and replaces one or multiple strings in all versions
+	 *
+	 * @param string $lang Code `'default'` in a single-lang installation
+	 * @param array $map search-replace mapping where all keys are replaced by their values
+	 *
+	 * @throws \Kirby\Exception\NotFoundException If the version does not exist
+	 */
+	public function replace(
```
Comment (bastianallgeier) [inline src/Content/PlainTextContentStorageHandler.php]: See comment above

File: src/Filesystem/F.php [hunk 9]
```diff
@@ -727,6 +727,25 @@ public static function remove(string $file): bool
 		return static::unlink($file);
 	}
 
+	/**
+	 * Searches and replaces one or multiple strings in a file
+	 */
+	public static function replace(
```
Comment (bastianallgeier) [inline src/Filesystem/F.php]: I would probably also vote for replaceStrings here.

File: src/Content/ContentStorage.php (hunk 6 above)
Comment (distantnative) [reply src/Content/ContentStorage.php]: Maybe just adding a comment? Cause I am not sure if trying to work around it wouldn't make quite the mess for 4.5 – or we directly target v5 with this from the start?

Comment (bastianallgeier) [reply src/Content/ContentStorage.php]: Seeing all the work ahead of us for the changes, I would probably prefer to put it in v5 and not cause additional conflicts with it tbh.

File: src/Cms/PageCopy.php (hunk 2 above)
Comment (distantnative) [reply src/Cms/PageCopy.php]: I went with `withChildren` and `withFiles`.

File: src/Content/MemoryContentStorageHandler.php [hunk 10]
```diff
@@ -79,6 +80,28 @@ public function read(VersionId $versionId, Language $language): array
...
+		$fields = $this->read($versionId, $language);
+		$fields = A::map(
+			$fields,
+			fn ($field) => str_replace(
+				array_keys($map),
+				array_values($map),
+				$field
+			)
+		);
+		$this->update($versionId, $language, $fields);
```
Comment (bastianallgeier) [inline src/Content/MemoryContentStorageHandler.php]: Couldn't this part be in the ContentStorageHandler class as a default instead of declaring it as abstract method?

Comment (distantnative) [reply src/Content/MemoryContentStorageHandler.php]: Good idea!

File: src/Content/PlainTextContentStorageHandler.php [hunk 11]
```diff
@@ -280,6 +280,20 @@ public function read(VersionId $versionId, Language $language): array
...
+	 * @throws \Kirby\Exception\NotFoundException If the version does not exist
+	 */
+	public function replaceStrings(
+		VersionId $versionId,
+		Language $language,
+		array $map
+	): void {
+		$file = $this->contentFile($versionId, $language);
+		F::replaceStrings($file, $map);
+	}
```
Comment (bastianallgeier) [inline src/Content/PlainTextContentStorageHandler.php]: One last thought here. Do we really gain so much by using the new `F::replaceStrings` method? In theory, this could also mean that a field name is accidentally replaced, right? If we just keep the default behaviour from ContentStorageHandler::replaceStrings for text files, we would probably not hit huge performance issues, but at the same time we don't need the new F:: method and we also don't risk overwriting field names by accident.

**Review by bastianallgeier — APPROVED** [review]
Super nice!

**Comment by silllli** [comment]
Just copied a page and noticed that all referenced files, although they were copied as well, still pointed to the originals … great that a fix is already in place, thank you! @distantnative
