### PR TITLE
`Str::excerpt()`: prevent extra space

### LINKED ISSUE #4301: Extra spaces added after linked text using excerpt()
## Description
There’s a bug when links are stripped out of blocks of text using the `excerpt()` method.

If a link is followed by a punctuation mark (such as a period or comma) and that link gets stripped from a block of text, an extra space gets inserted between the original linked text and the punctuation. If the link is _not_ followed directly by any punctuation, no extra space is inserted.

Note that this behaviour does not occur in K2.

## To reproduce
I’m using the following code in my template, links in the text field are formatted using Markdown.

`<?php echo $result->text()->excerpt(200) ?>`

However, the same issue can be reproduced using:

`<?php echo Str::excerpt('Why not <a href="https://getkirby.com/">Get Kirby</a>?', 200) ?>`

This example returns:

Why not Get Kirby ?

**Expected behavior**  
When links are stripped out of text using the `excerpt()` method, extra spaces should not be added between the link text and a punctuation mark directly following the link.

The expected text being returned should be:

Why not Get Kirby?

**Screenshots**  
In the example below, the words “cursor”, “input”. and “tapped” were all linked in the the original text field.

Screen Shot 2022-05-04 at 2 37 43 PM

## Your setup
**Kirby Version**  
3.6.5

**Console output**  
n/a

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 10.13.6 High Sierra
 - Browser: Vivaldi
 - Version: 5.2.2623.41 (Chrome/100.0.4896.147)

### PR DESCRIPTION
**Pull request by distantnative**
### Fixes
- `Str::except()` does not add superfluous space after stripped tag and before interpunctuation
#4301

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] ~~Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)~~

### CODE REVIEW

File: src/Toolkit/Str.php [hunk 1]
```diff
@@ -469,7 +469,12 @@ public static function esc(string $string, string $context = 'html'): string
 	public static function excerpt($string, $chars = 140, $strip = true, $rep = ' …')
 	{
 		if ($strip === true) {
-			$string = strip_tags(str_replace('<', ' <', $string));
+			// ensure that opening tags are preceded by a space, so that
+			// when tags are skipped we can be sure that words stay separate
+			$string = preg_replace('#\s*<([^\/])#', ' <${1}', $string);
+
+			// strip tags
```
Comment (lukasbestle) [inline src/Toolkit/Str.php]: To make the comment a bit more useful than a 1:1 copy of the function name 😅

```suggestion
			// in strip mode, we always return plain text
```

Comment (distantnative) [reply src/Toolkit/Str.php]: Fair enough :D

**Review by lukasbestle — APPROVED** [review]
