### PR TITLE
Load language rules in fiber

### LINKED ISSUE #3900: [3.6.0-rc.3] Slugs are not created correctly in a multilanguage website
**Describe the bug**  
Umlauts are not "slugified" correctly in a multilanguage website.

**To Reproduce**  
1. Download plainkit
2. Update to kirby 3.6.0 rc.3
3. Add new user to panel, use German as Panel language
3. Enable languages in `config.php`: `'languages' => true`
4. Add German and English languages in Panel
5. Create new page with umlaut

**Expected behavior**  
In Kirby 3.5, umlauts are slugified correctly in a multilanguage website. Without having to add language specific slug rules (https://getkirby.com/docs/guide/languages/slug-rules).

**Screenshots**  
Screenshot

**Kirby Version**  
3.6.0-rc.3

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Added missing `rules` prop to fiber response. 

### Fixed regressions from 3.6.0-rc.3

- Fixed converting slugs incorrectly in multilanguge websites #3900

## Breaking changes

None

## Related issues/ideas

- Fixes #3900

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] CI checks pass

## When merging

- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

### CODE REVIEW

File: src/Panel/View.php [hunk 1]
```diff
@@ -168,19 +168,23 @@ public static function data(array $view = [], array $options = []): array
...
                     return $kirby->languages()->values(function ($language) {
                         return [
-                            'code'    => $language->code(),
-                            'default' => $language->isDefault(),
-                            'name'    => $language->name(),
+                            'code'      => $language->code(),
+                            'default'   => $language->isDefault(),
+                            'direction' => $language->direction(),
+                            'name'      => $language->name(),
+                            'rules'     => $language->rules(),
```
Comment (afbora) [inline src/Panel/View.php:187]: It's not needed but I've added it to be consistent with `$language` response.

**Review by bastianallgeier — APPROVED** [review]
