### PR TITLE
Injects language translations to `kirby()->translations()` #3064

### LINKED ISSUE #3064: api/translations/:code does not return custom language variables
**Describe the bug**  

As [previously discussed in the forum](https://forum.getkirby.com/t/improve-documentation-for-translations-api-endpoints/20654), the [`api/translations/:code`](https://getkirby.com/docs/reference/api/translations/get) endpoint returns all translations, including plugins, but doesn't return custom language variables as defined in the translations field of e.g. `site/languages/de.php`.

**To Reproduce**  
1. Define custom language variables in one of your translation files, e.g. `site/languages/de.php`:  
    ```php
    <?php
    
    return [
        'code' => 'de',
        'default' => true,
        'direction' => 'ltr',
        'locale' => [
            'LC_ALL' => 'de'
        ],
        'name' => 'Deutsch',
        'translations' => [
            'labelname' => 'Name',
            'labelemail' => 'E-Mail',
            'labelresidence' => 'Wohnort',
            'labelquestion' => 'Frage stellen',
            'labelquestionsubmit' => 'Frage einsenden'
        ],
        'url' => ''
    ];
   ```
2. Query the `api/translations/de` endpoint

**Expected behavior**  
The result set of the API request to include the custom language variables.

**Screenshots**  
–

**Kirby Version**  

3.5.0

**Console output**  

**Desktop (please complete the following information):**  
Not relevant

**Smartphone (please complete the following information):**  
Not relevant

**Additional context**  
–

cc @distantnative

### PR DESCRIPTION
**Pull request by afbora**
## Describe the PR

Current language translations injected to global translations.

## Related issues

- Fixes #3064 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Added in-code documentation (if needed)
- [x] CI passes (runs automatically when the PR is created or run `composer ci` locally)
  Running locally requires PHPUnit, PHP-CS-Fixer, Psalm, PHPCPD and PHPMD.

- [x] Checked whether the PR needs documentation, if needed added to the [release docs checklist](https://github.com/getkirby/getkirby.com/pulls)

### CODE REVIEW

**Review by texnixe — DISMISSED** [review]

**Comment by afbora** [comment]
@texnixe I did not see your approval, I'm sorry. I drafted it because I saw a few missing.

File: src/Cms/AppTranslations.php [hunk 1]
```diff
@@ -203,6 +208,18 @@ public function translations()
...
-        return Translations::load($this->root('i18n:translations'), $this->extensions['translations'] ?? []);
+        $translations = $this->extensions['translations'] ?? [];
+
+        // inject current language translations
+        if ($language = $this->language()) {
+            $translations = array_replace_recursive(
+                $translations,
+                [$language->code() => $language->translations()]
+            );
+        }
```
Comment (afbora) [inline src/Cms/AppTranslations.php]: I just injected the current language, but do you think we should inject translations from all languages always?

**Review by bastianallgeier — APPROVED** [review]
LGTM
