### PR TITLE
`system.exception` hook: suppress error log

### LINKED ISSUE #5028: Irrelevant failed authentication request logged in php_error.log + becoming GDPR-relevant
## Description
php_error.log is spammed with irrelevant messages, e. g. wrong password authentications. Furthermore it even contains sensitive information, e. g. the email address used for authentication thus this becomes GDPR-relevant.

**Expected behavior**  
In general I think that Kirby 3 throws too many exceptions at some points and with wrong status code. The input should be validated first and then an exception thrown in case required fields are missing or there are obvious logic fails in the input. For this case it doesn't work and in most cases I ignored this but now I just noticed that even a regular invalid authentication due to wrong password typed in is being logged to the PHP logs. This is filling them quite fast with non-helpful messages and thus makes debugging harder. I think there is no benefit in this specific log to know that a single log-in failed.

## To reproduce
Have a local WAMP setup and try to log-in to the panel with invalid credentials. Debug config option is enabled.

## Your setup
v3.9.1-rc1

**Your system (please complete the following information)**
Firefox, WAMP setup

**Additional context**  
This is the log entry in `php_error.log`:

```
[26-Jan-2023 19:38:45 UTC] Kirby\Exception\InvalidArgumentException: Falsches Passwort in […]\kirby\kirby\src\Cms\User.php:872
Stack trace:
#0 […]\kirby\kirby\src\Cms\Auth.php(534): Kirby\Cms\User->validatePassword(Object(SensitiveParameterValue))
#1 […]\kirby\kirby\src\Cms\Auth.php(402): Kirby\Cms\Auth->validatePassword('<removed>@...', Object(SensitiveParameterValue))
#2 […]\kirby\kirby\config\api\routes\auth.php(70): Kirby\Cms\Auth->login('<removed>@...', Object(SensitiveParameterValue), false)
#3 [internal function]: Kirby\Cms\Api->{closure}()
#4 […]\kirby\kirby\src\Api\Api.php(179): Closure->call(Object(Kirby\Cms\Api))
#5 […]\kirby\kirby\src\Cms\Api.php(46): Kirby\Api\Api->call('auth/login', 'POST', Array)
#6 […]\kirby\kirby\src\Api\Api.php(503): Kirby\Cms\Api->call('auth/login', 'POST', Array)
#7 […]\kirby\kirby\config\routes.php(42): Kirby\Api\Api->render('auth/login', 'POST', Array)
#8 [internal function]: Kirby\Http\Route->{closure}('auth/login')
#9 […]\kirby\kirby\src\Http\Router.php(120): Closure->call(Object(Kirby\Http\Route), 'auth/login')
#10 […]\kirby\kirby\src\Cms\App.php(341): Kirby\Http\Router->call('api/auth/login', 'POST')
#11 […]\kirby\kirby\src\Cms\App.php(1243): Kirby\Cms\App->call('api/auth/login', 'POST')
#12 […]\kirby\index.php(5): Kirby\Cms\App->render()
#13 {main}
```

### PR DESCRIPTION
**Pull request by distantnative**
### Enhancement
- `system.exception` hook: return `false` to prevent error to be logged
#5028

## Ready?

- [x] In-code documentation (wherever needed)
- [x] Unit tests for fixed bug/feature
- [x] Tests and CI checks all pass

### For review team

- [x] Add changes & docs to release notes draft in Notion

### CODE REVIEW

File: src/Cms/AppErrors.php [hunk 1]
```diff
@@ -190,8 +190,19 @@ protected function setWhoopsHandler(callable|HandlerInterface $handler): void
...
+			$isLogged = true;
+
+			// allow hook to modify whether the exception should be logged
+			$isLogged = $this->apply(
+				'system.exception',
+				compact('exception', 'isLogged'),
+				'isLogged'
+			);
+
+			if ($isLogged === true) {
```
Comment (bastianallgeier) [inline src/Cms/AppErrors.php]: `Question` Would it be better to turn this around and check for false here? It would be a bit more explicit to surpress warnings that way and I think it would also not lead to a breaking change.

**Review by bastianallgeier — APPROVED** [review]
