### PR TITLE
Fix filling default values while creating new page

### LINKED ISSUE #5140: Select field with default value in multi language site not filled
## Description
If you have a select field which has a default option, and this field is set not to translate, when you create a page in a non-default language in a multi language setup, the field remains empty. In my case the field is required, and the options are pages pulled dynamically from a query, with one page being set as the default.

**Expected behavior**  
Even in a non-default language I would except the value to be filled for the default language, otherwise the field remains empty, and is not automatically select once switching to the default language.

**Screenshots**  
Screenshot 2023-04-07 at 09 03 18

## To reproduce

1. Multi-language site
2. Create page in non-default language
3. Select field is not filled with default value

**Field example**
```
fields:
  category:
    label: Category
    translate: false
    required: true
    type: select
    default: architecture
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
```

## Your setup
**Kirby Version**  
3.9.3

### PR DESCRIPTION
**Pull request by afbora**
## This PR …

Solved this issue by [always sending the default language as an argument](https://github.com/getkirby/kirby/pull/5144/files#diff-8e8501f5cf24c63dea196abff40bfb44322604ba3a244561300db2c053d2242aR551) to get the default values since [we do this in the default language when creating a multilingual page](https://github.com/getkirby/kirby/pull/5144/files#diff-8e8501f5cf24c63dea196abff40bfb44322604ba3a244561300db2c053d2242aR568).

### Fixes
- Fix filling default values while creating new page on secondary language #5140

### Breaking changes
None

## Ready?

- [x] Unit tests for fixed bug/feature
- [x] In-code documentation (wherever needed)
- [x] Tests and checks all pass

### For review team

- [x] Add changes to release notes draft in Notion
- [x] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)

### CODE REVIEW

File: tests/Cms/Pages/PageActionsTest.php [hunk 1]
```diff
@@ -1177,4 +1177,184 @@ public function testDuplicateHooks()
 
 		$this->assertSame(2, $calls);
 	}
+
+	public function testCreateDefaultLanguage()
```
Comment (afbora) [inline tests/Cms/Pages/PageActionsTest.php:1181]: Maybe it's necessary to write a more efficient unit tests for this PR 🤷‍♂️

**Comment by afbora** [comment]
In my local the unit tests pass, but in the GitHub workflow it fails even if I make different attempts. Does anyone have any idea why?

**Comment by bastianallgeier** [comment]
I don't have time to look closer into the tests today, but the code part looks really good and useful to me.

**Comment by afbora** [comment]
Failing unit tests was related with previous unit test blueprint setup cache. I've fixed and now unit test works great and passes 👍 Now ready to review 🚀

**Comment by distantnative** [comment]
Haven't tested it myself but reading the code it looks fine.

**Review by bastianallgeier — APPROVED** [review]
